<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DMFIN1000008482</name>
   <tag></tag>
   <elementGuidId>2ef5393a-c080-497e-ad60-c6babf13c369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='allProspectEntries']/table/tbody/tr/td[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a11f339f-cce5-4c3e-8f3b-505c621b6e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:showDetail('DMFIN1000008482','1000018386','1000039002','1000008482','1000000008')</value>
      <webElementGuid>58cb745e-c5e6-40d4-b7bf-71eef033a165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DMFIN1000008482 </value>
      <webElementGuid>6f02f303-57df-40a7-b1c1-64615765d002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allProspectEntries&quot;)/table[@class=&quot;tr_list&quot;]/tbody[1]/tr[@class=&quot;tr_list&quot;]/td[3]/a[1]</value>
      <webElementGuid>474e49ca-8823-4983-b158-2729a8bffb92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allProspectEntries']/table/tbody/tr/td[3]/a</value>
      <webElementGuid>49685409-662f-42cf-8c06-ed6513672577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DMFIN1000008482')]</value>
      <webElementGuid>4ba27c9e-b94b-4ba8-b2d1-da77e222787b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW MILD HYBRID FINANCE LEASE'])[2]/following::a[1]</value>
      <webElementGuid>d05b8e16-7c22-44c9-a684-65a930b35710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNCIMF000003791'])[1]/preceding::a[1]</value>
      <webElementGuid>c39d8d33-fddd-48a2-b953-707597ecf482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DMFIN1000008482']/parent::*</value>
      <webElementGuid>83827035-b8ee-4bab-93d3-b6e0d3751dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:showDetail('DMFIN1000008482','1000018386','1000039002','1000008482','1000000008')&quot;)]</value>
      <webElementGuid>4b94a44c-5c5e-4ae2-adab-990499aa8e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>fa6a3610-460a-4de2-af79-e5cbe3557969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:showDetail(&quot; , &quot;'&quot; , &quot;DMFIN1000008482&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000018386&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000039002&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000008482&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000000008&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'DMFIN1000008482 ' or . = 'DMFIN1000008482 ')]</value>
      <webElementGuid>0f75e70e-45ef-4524-aff7-117961d0653b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
