<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dateOfInvocation</name>
   <tag></tag>
   <elementGuidId>6851b0c5-f518-4c7b-821a-cc55e4187612</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='dateOfInvocation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;dateOfInvocation&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>038c3ae6-36ef-45e1-be39-611b677c824e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>edda0c5b-3287-45f3-aed0-25843f5f2b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dateOfInvocation</value>
      <webElementGuid>a239f226-f4d0-47a8-9236-9ae71df5a729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scheparam&quot;)/tbody[1]/tr[1]/td[1]/fieldset[1]/table[@class=&quot;main_body you&quot;]/tbody[1]/tr[2]/td[3]/input[1]</value>
      <webElementGuid>f0bf869c-c93f-4bf1-b09a-61099b8fd2ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='dateOfInvocation']</value>
      <webElementGuid>664ce2fe-1a7a-411c-ab8a-6670a82625fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='scheparam']/tbody/tr/td/fieldset/table/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>0c42f481-86f9-477a-8029-3178db097000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>954db3de-e499-4bef-af84-a281bee1269e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'dateOfInvocation']</value>
      <webElementGuid>2218d2f2-56e1-42e6-901d-87df650ffbf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
