<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select-- RESTRUCTURING</name>
   <tag></tag>
   <elementGuidId>c8e068af-4642-4ca5-aba8-b44317b048fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='rescduleType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rescduleType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2a645e66-196a-484e-8444-abf17123d6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reschType</value>
      <webElementGuid>156021d4-798b-4707-8ee1-cad1de9d9994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:resetFlagValue(this.selectedIndex);</value>
      <webElementGuid>62531ff9-cfa7-4ae0-85f7-78bd001cf2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rescduleType</value>
      <webElementGuid>0acc0952-e8f4-40fd-8550-7a8aaab73b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>--Select--</value>
      <webElementGuid>1294256b-02d1-47f2-be65-6108b7be3565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select-- RESTRUCTURING</value>
      <webElementGuid>8d93c090-5f9e-4a09-b2fa-5c6046e1ad45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rescduleType&quot;)</value>
      <webElementGuid>4c65dc81-94a9-4359-b31f-2a355ebf634a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='rescduleType']</value>
      <webElementGuid>1edc53c0-3ff6-4937-9e5d-6a52a8394801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='scheparam']/tbody/tr/td/fieldset/table/tbody/tr[4]/td[3]/select</value>
      <webElementGuid>e3ae4511-2591-45c5-b576-dc2a100c1228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[6]/following::select[1]</value>
      <webElementGuid>d5718544-7ea4-401e-8bf2-e5f3897af97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rescheduling Type'])[1]/following::select[1]</value>
      <webElementGuid>33ed9c2f-9c6a-4666-980f-c94a2bfc532f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installment Type'])[1]/preceding::select[1]</value>
      <webElementGuid>d3bf8b48-8a8b-46dc-81f4-83f64ad1af9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[7]/preceding::select[1]</value>
      <webElementGuid>e54428db-f258-4606-969c-6ce419947c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/select</value>
      <webElementGuid>27f1f081-c5eb-46a7-801b-3bc244b5a14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'reschType' and @id = 'rescduleType' and @title = '--Select--' and (text() = '--Select-- RESTRUCTURING' or . = '--Select-- RESTRUCTURING')]</value>
      <webElementGuid>267c46c3-a887-458a-a8ee-191c2f3b4dc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
