<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Author Remarks_authorRemarks</name>
   <tag></tag>
   <elementGuidId>1aa69d8d-ca7e-44a3-89a7-957710da1c36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='authorRemarks']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;authorRemarks&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4f5c3afa-0018-4c70-9811-36d000f3bb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>c812717f-5662-4f02-8bc9-f01ea63ffd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>6fdd89ad-a95f-4a37-914c-1b06722314e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>authorRemarks</value>
      <webElementGuid>1b74d0d8-9c9e-4a4a-abcb-b18710229bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkRemark(this,'Author Remarks')</value>
      <webElementGuid>1165b4a8-abb3-492b-b175-7e99e48c16fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;menuHavingBody&quot;]/form[1]/table[1]/tbody[1]/tr[1]/td[1]/fieldset[1]/table[@class=&quot;main_body&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;main_body&quot;]/tbody[1]/tr[1]/td[@class=&quot;authorApprove_textarea&quot;]/span[@class=&quot;textarea-span&quot;]/textarea[1]</value>
      <webElementGuid>eafaf2c9-7354-486c-9986-54a62cc452cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='authorRemarks']</value>
      <webElementGuid>c06b037c-a91a-4d54-8d94-3b228c8a1a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9400b277-0f42-4055-aaa3-f843612adda8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'authorRemarks']</value>
      <webElementGuid>8a4b859b-373e-4dc4-a1d7-4bdae82d4280</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
