<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__mrRemarks</name>
   <tag></tag>
   <elementGuidId>6d60d3dd-a4dd-4042-bb91-27e871194745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='mrRemarks']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;mrRemarks&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>89576107-9c4c-49ee-a11c-da98344a2b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mrRemarks</value>
      <webElementGuid>4fd598d3-d6af-4167-be12-5ac0e84a1c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>57908ac5-1a2c-4c1e-b8e6-ae9b22c0a68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>19f97f0d-e1de-4b5f-b23e-ae72e97e76e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkRemark(this,'Maker Remarks')</value>
      <webElementGuid>c2c1c5d5-2313-4a8e-96c0-3ebd00266c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mrRemarksID&quot;)/span[@class=&quot;textarea-span&quot;]/textarea[1]</value>
      <webElementGuid>d091ecef-9251-4b7c-9d2c-febbe2daa6fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='mrRemarks']</value>
      <webElementGuid>66f9301f-6578-4462-b09f-00fc124f31e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='mrRemarksID']/span/textarea</value>
      <webElementGuid>9274264a-7354-4e2d-9e4c-8cb1a6122268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6575e315-8dfc-4be6-aeb4-62da1dfd360f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'mrRemarks']</value>
      <webElementGuid>a06dc697-ae3f-4c78-be10-52d9d0955391</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
