<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Hi COPSUSERM_userr_1</name>
   <tag></tag>
   <elementGuidId>3fc61bdc-a90d-48cf-ab01-d3f13e2cfb06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.userr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>65ce9a70-e6ae-4211-b50c-54b2120a4cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>userr</value>
      <webElementGuid>cab85549-29de-40b0-8aed-3aaaad29e491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/picuser_head.png</value>
      <webElementGuid>3e7095f1-6c35-4549-bbea-adf325cec25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-fluid&quot;]/form[1]/div[@class=&quot;backe_image col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[1]/div[@class=&quot;col-lg-4 col-md-4 col-sm-4 col-xs-4&quot;]/div[1]/span[@class=&quot;username_icon&quot;]/img[@class=&quot;userr&quot;]</value>
      <webElementGuid>fc665595-3e14-46f1-98fa-f78aab7307f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>61357dab-e22a-45db-9eca-5ee0f11898ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/picuser_head.png']</value>
      <webElementGuid>c3f73afd-47b1-4f1c-b590-27c0d3d8523d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
