<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SYSUSER_file_2</name>
   <tag></tag>
   <elementGuidId>fc523278-6f44-4d4e-8c5b-1bc665a6b57a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#file2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='file2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed1de3b1-9aa2-47e3-b454-1ab390bcc925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>bba39fee-03b6-400d-bdb2-878f3d51c369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>234a34d3-363c-4f2f-9174-4f4786f3d8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file2</value>
      <webElementGuid>94c444ec-a910-4c20-b862-c9084d0ee9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;file2&quot;)</value>
      <webElementGuid>bc113777-58a4-414c-a9a8-82db759bc037</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='file2']</value>
      <webElementGuid>eb9532c6-0de3-4b95-aa0e-b6b0702b7a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='fileTD2']/input</value>
      <webElementGuid>2853b965-86ed-4c08-a0a0-6344c0174fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[6]/input</value>
      <webElementGuid>ceeda6c0-28a0-48d1-9b84-561b24f18e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'file' and @id = 'file2']</value>
      <webElementGuid>4e116a38-cc43-484f-8a8d-363a3bec68e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
