<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LEASE RESIDUAL VALUE UPLOAD_bar2</name>
   <tag></tag>
   <elementGuidId>74b84b65-58a8-4557-819f-b3fef36cd659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.bar2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toggle-button']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b811eae6-cdfb-4e41-8f2c-793c48068759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bar2</value>
      <webElementGuid>ddccb37b-f893-4760-b716-c0f3d5f8fd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggle-button&quot;)/div[@class=&quot;bar2&quot;]</value>
      <webElementGuid>a4519c05-251d-4ee1-85fd-dd89ac602000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toggle-button']/div[2]</value>
      <webElementGuid>c6ce4a25-0b0b-42bc-a977-c6e3ed026e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]</value>
      <webElementGuid>4c67c4a6-80ff-4c37-ae89-18c5b580fe9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
