<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_DM APPLICATION_img1200004003</name>
   <tag></tag>
   <elementGuidId>393f3dd4-b5b5-42ab-b541-fc1bc03c29a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img1200004003</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='img1200004003']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e2114a99-163e-47b9-9a26-380e167b5b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img1200004003</value>
      <webElementGuid>f6bcfd3e-8821-46d7-a876-b18af3918cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>ea75bf8f-d26b-469a-86ba-f57741cb41b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b0e145ad-59da-4685-8a41-997908f4ec41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img1200004003&quot;)</value>
      <webElementGuid>8b8498b1-aad9-4ee5-8961-b7c015adc893</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='img1200004003']</value>
      <webElementGuid>5d01dd04-071c-4c7e-b798-a31239681508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='imgDiv']/i)[16]</value>
      <webElementGuid>957d754e-9711-4f7b-8079-30222eb987bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[56]/div/div/i</value>
      <webElementGuid>1294b310-1e43-4883-a41f-328e7859af07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'img1200004003']</value>
      <webElementGuid>ea7e2678-69bd-45bc-b0ad-c6b1e4eb3066</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
