<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_DM VIEWER_img1000000017</name>
   <tag></tag>
   <elementGuidId>212a90c5-fe70-4c3e-93bc-e0f68360f96c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img1000000017</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='img1000000017']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ccdb6f21-a6dc-4c36-9c38-56401a465616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img1000000017</value>
      <webElementGuid>877ab9ca-beca-40c9-97bd-9bf360f7199c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>88276a14-6b7a-4b6f-a895-6e251da42a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3ef3b956-c516-4b49-80b5-dd7f76115d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img1000000017&quot;)</value>
      <webElementGuid>84911048-47a8-4fdb-bdbc-86413f73efe1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='img1000000017']</value>
      <webElementGuid>6994a2a6-067d-4af5-914e-123263fd2c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='imgDiv']/i)[18]</value>
      <webElementGuid>a1448798-d455-4ca9-9404-dc7458d81481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[68]/div/div/i</value>
      <webElementGuid>48285e62-30eb-422c-97af-155537609938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'img1000000017']</value>
      <webElementGuid>8848757d-f4e3-44dd-976f-0fb54e09d813</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
