<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_VIEWER_img1000001980</name>
   <tag></tag>
   <elementGuidId>e46d2a8c-a891-4c16-92fd-926d8b2845b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img1000001980</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='img1000001980']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a2e0f6dc-fc6a-413f-b287-088b78ddcda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img1000001980</value>
      <webElementGuid>f8fe1c27-e85d-4ed8-8017-20fbc4acdab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>9ccd122f-b829-4cb2-a735-54ca3a329a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8dc442d1-9f1e-4960-b40f-787bf23e5dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img1000001980&quot;)</value>
      <webElementGuid>367ec67c-111a-407b-9b72-67230626599e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='img1000001980']</value>
      <webElementGuid>e54e258c-6aa5-4bf0-8c0e-6f7b7082a502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='imgDiv']/i)[24]</value>
      <webElementGuid>5cdf086e-4f3c-4636-956a-9579785f57c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[88]/div/div/i</value>
      <webElementGuid>e608e9f7-2647-4c74-a1cb-7f377c1a5f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'img1000001980']</value>
      <webElementGuid>6ea9e4bd-60aa-4d55-943c-81360e465b4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
