<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CIM_Regression</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>210755a0-4faf-44f9-afb3-22fda1270fac</testSuiteGuid>
   <testCaseLink>
      <guid>59d3db5e-c9b1-4e36-be31-b9f567edc402</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Customer creation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54cb314a-6003-4752-a204-e21c43acc3b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17db29b5-8aaa-471f-aa8c-5b1294384b81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a03386a6-b0b9-4680-a1f9-2cfe94b86868</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cca82043-1c68-4833-92ae-e9d86984eaca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72132da1-02c8-4740-b0e4-5507c1d00d92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10d83f2f-560b-456e-ba3a-0cabbad6533a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2aad6ca7-35f8-4bda-8b06-1e1df54edb08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c1c2118-b6b0-488b-97aa-594bfe3e4ccc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>337977bd-c9b5-4ddb-a2ef-0ad935cefb76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d06cc18-8e2a-4a45-9a39-70456c5572b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>36819356-f8c1-42db-ba08-8bafe16279d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Customer limit creation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8135b0d6-287e-4f7d-ad90-3667777f0d0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7e07c06-19c6-4f61-ad2c-9f92e770232c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5801a298-a77c-4e6b-9610-71b7dab6c31a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>269a69db-9dba-4297-a28a-bd36bac91b51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/New_Cust_approval</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cc71e29-83a1-460d-a126-925929e41741</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb98d28b-6082-43e1-bd22-984b857e082d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ee912ce-138a-463a-b291-f4d2530a5088</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c94b4fa5-a503-4b0c-95a3-60f784e6137c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/New Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9b42913-00a0-45b8-9190-1286432577b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b83d8554-644c-46a9-aec5-5a186a3f3052</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f065981-cfec-4d4c-8924-ca06f614485e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f41b0750-8bb2-4eca-9dec-a83e24c092d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/New Quotation - Acceptance</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba6ef40a-4802-4d67-b4f1-9a5ee0a5490c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2fb8f70-2f42-4a0b-9671-c58c7b3540d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ba6d36a-9d67-4ad9-849e-99c61392ee8d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/DM Creation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a63c94b3-4269-44fe-bfed-3461d8dbdf5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddd915ea-727a-43e7-9d8b-b1c0d3a73bdd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d97adcd6-f0a4-457a-a32b-e66605f36bbd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f477d51b-0935-4605-827a-cdf7aa35768c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/DM Quotation to Partially disbursed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acba746d-3553-411c-b2b4-dfb75f2c2967</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>840ae853-0698-4fc0-bbdc-4f9ddcd8216c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ea80f81-89af-4946-8db7-895402370626</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a93716e0-41c6-4b41-9db0-9a7a1b98cfff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f1c7e7e-8d2a-40c8-a833-fdb17f8fb4db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/DM_Approval</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7036656-6ae1-42f6-b994-1e99c11752f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1fe36df3-1b03-4344-a307-13a02da557f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Post_Sanction_Documents</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53d5283e-87a4-4ad1-ac9f-63c7b3c02e7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f64141c-68ab-4b5b-9c35-6efdd577b6f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17bbf1c6-4838-4504-89b9-a8d4464958e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45eadd37-6cb1-4bdf-a43b-497845074357</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c36a4006-c5f0-4b95-a3c6-0ce9b7f41b80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/receipt approval</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3b6b1ae-5ee5-4599-8e1e-463ca0ef8b91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c669c12b-2238-4ad1-b8b4-03feaeed4d2a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Receipt creation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a498de17-94d8-467e-a885-a9df7ca14a45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3f85278-ed6c-4b9a-98c9-4b41b16ead02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1aac7426-4935-4111-9624-68499cbd1c3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1544a7e2-8290-45a7-b756-e7ddeca0872b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3739aa6-b08a-4aa7-b746-51ea592c1f6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Captalization_maker_Author</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85e94811-c82c-4637-8c77-b7e692cfa57c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
