<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CIM_Regression</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>210755a0-4faf-44f9-afb3-22fda1270fac</testSuiteGuid>
   <testCaseLink>
      <guid>d616dc69-741a-4a00-99d5-3ad1f3b884b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Customer creation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54cb314a-6003-4752-a204-e21c43acc3b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17db29b5-8aaa-471f-aa8c-5b1294384b81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a03386a6-b0b9-4680-a1f9-2cfe94b86868</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cca82043-1c68-4833-92ae-e9d86984eaca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72132da1-02c8-4740-b0e4-5507c1d00d92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10d83f2f-560b-456e-ba3a-0cabbad6533a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2aad6ca7-35f8-4bda-8b06-1e1df54edb08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c1c2118-b6b0-488b-97aa-594bfe3e4ccc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>337977bd-c9b5-4ddb-a2ef-0ad935cefb76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d06cc18-8e2a-4a45-9a39-70456c5572b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b48cb3a-a888-4cfc-aaa6-49665837aba3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/New_Cust_approval</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cc71e29-83a1-460d-a126-925929e41741</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb98d28b-6082-43e1-bd22-984b857e082d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ee912ce-138a-463a-b291-f4d2530a5088</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d14f600-b76d-4641-a0cd-1a0b893d7700</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/New Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9b42913-00a0-45b8-9190-1286432577b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b83d8554-644c-46a9-aec5-5a186a3f3052</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f065981-cfec-4d4c-8924-ca06f614485e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d57e8387-70a5-4aed-8e4b-f00dca0767ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Customer limit creation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8135b0d6-287e-4f7d-ad90-3667777f0d0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7e07c06-19c6-4f61-ad2c-9f92e770232c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5801a298-a77c-4e6b-9610-71b7dab6c31a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a0284f8-63a9-4cfe-b57d-24e4e03ea3b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/New Quotation - Acceptance</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba6ef40a-4802-4d67-b4f1-9a5ee0a5490c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2fb8f70-2f42-4a0b-9671-c58c7b3540d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2feb1c5e-76bc-4f2a-8fdc-99b8c252cbbd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/DM Creation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a63c94b3-4269-44fe-bfed-3461d8dbdf5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddd915ea-727a-43e7-9d8b-b1c0d3a73bdd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d97adcd6-f0a4-457a-a32b-e66605f36bbd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e8df0e6-1ed4-4bc5-a2bb-155da929b7c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/DM_Approval</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7036656-6ae1-42f6-b994-1e99c11752f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c4d8e412-b9e7-4987-96c6-a18db585dd12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Post_Sanction_Documents</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53d5283e-87a4-4ad1-ac9f-63c7b3c02e7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f64141c-68ab-4b5b-9c35-6efdd577b6f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17bbf1c6-4838-4504-89b9-a8d4464958e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45eadd37-6cb1-4bdf-a43b-497845074357</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f4083e84-7834-4792-ad91-95213f326a8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Receipt creation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a498de17-94d8-467e-a885-a9df7ca14a45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3f85278-ed6c-4b9a-98c9-4b41b16ead02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1aac7426-4935-4111-9624-68499cbd1c3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1544a7e2-8290-45a7-b756-e7ddeca0872b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>19344cf6-8377-401f-a148-6773794ecb02</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/receipt approval</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3b6b1ae-5ee5-4599-8e1e-463ca0ef8b91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc152af8-28fc-426d-a910-13e1f8d624d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Captalization_maker_Author</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85e94811-c82c-4637-8c77-b7e692cfa57c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a061491-3331-431a-aac6-2dca8173c0a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Post_Disbursal_Document</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b20a1f2-f13f-40ac-87a4-1b8cd96b421c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e87253c-6b8a-4fb5-a45f-0d2822691d3d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>44f85259-1b21-4d60-a530-5f47349833b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Payment_Schedule_Maker_Author</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4eb30119-578d-4f2f-b81c-dcda7fbfa35f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3a9636e-d216-4207-9b4f-952c1e02497e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/ManualAdvice_maker_Author</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>def5aa43-8586-45a2-956c-0a09c2372e99</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4cc89976-f920-48a9-b397-d69cf473af1c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/KnockOff_Maker_Author</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4d9f58e-2dab-40e1-89d3-ee69b89d5ce1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>de4e52b9-f6df-418f-9390-ac4edc752620</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Waive off</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62de8551-62eb-40ac-a4f2-6547a2ffbb17</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
