<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Assignation in favour of CFSL_POLICY_NO0</name>
   <tag></tag>
   <elementGuidId>944b8ef7-5aa1-4a8f-9c8d-281186eebafa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#POLICY_NO0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='POLICY_NO0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d950032d-e50e-49c8-be2c-16750a75c3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a33c796-32f0-4d61-a603-5d04afc01616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>POLICY_NO0</value>
      <webElementGuid>a6d64f59-171e-49ee-ba1d-36ee30d337f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inflow.POLICY_NO</value>
      <webElementGuid>fc5cf112-5d72-4e8e-a606-e8fa00bdcecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>1b7800db-b8cd-4727-8265-1c8ed37e9ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ((event.keyCode>47 &amp;&amp; event.keyCode&lt;58) || (event.keyCode>64 &amp;&amp; event.keyCode&lt;91) || (event.keyCode>96 &amp;&amp; event.keyCode&lt;123) || event.keyCode==45 || event.keyCode==47);</value>
      <webElementGuid>aa2356b8-e3d9-47e6-85e0-5da22ac66309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-valid-maxlength</value>
      <webElementGuid>b2e937c6-ab1e-4cc5-9a81-8d713d50b997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;POLICY_NO0&quot;)</value>
      <webElementGuid>7602ea58-65ac-4037-8db4-352439fbedcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='POLICY_NO0']</value>
      <webElementGuid>b07e911e-1074-4f59-a589-30c1e1a43aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/fieldset/fieldset[3]/div[2]/table/tbody/tr[3]/td[6]/input</value>
      <webElementGuid>9982620f-8b6f-4b4e-b50c-31f1e2fab555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>06540457-1a7d-4702-b7b8-f842eccecc93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'POLICY_NO0']</value>
      <webElementGuid>fdf0da76-f89e-4e50-bf45-f24636e4d002</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
