<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Assignation in favour of CFSL_SUM_INSURED0</name>
   <tag></tag>
   <elementGuidId>b6b38280-2497-4b18-bb0c-6d3fa6da1186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SUM_INSURED0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SUM_INSURED0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dca1c57c-e0b1-4a94-aa3b-06e308b2fa29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>25c7354c-32c7-47c4-9c5e-ab09d10a0a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SUM_INSURED0</value>
      <webElementGuid>e9bdd06f-bafe-4f05-b82d-dc2bf7772531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inflow.SUM_INSURED</value>
      <webElementGuid>3011360d-0cf4-4908-92ff-5ba9baaf5fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return (event.charCode >= 48 &amp;&amp; event.charCode &lt;= 57 )</value>
      <webElementGuid>95bc6a56-0c4a-4898-a416-1c5bc41fe604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>88dbd7d6-65e5-4b23-a634-f26d7913e093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SUM_INSURED0&quot;)</value>
      <webElementGuid>e83c4161-d2fe-41ed-91b7-838e8c5a434f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SUM_INSURED0']</value>
      <webElementGuid>94d52a0c-4ebf-4c9f-a66c-7b136d8ac1e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/fieldset/fieldset[3]/div[2]/table/tbody/tr[3]/td[7]/input</value>
      <webElementGuid>d92c5aef-26a2-41c5-9c35-dda9fe8514b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/input</value>
      <webElementGuid>22bcbc23-eacc-441e-9e5f-2ddb92cd88e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'SUM_INSURED0']</value>
      <webElementGuid>73a34943-f7a0-4dac-9a29-b9c2542cb86e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
