<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address 2_FLOORNO</name>
   <tag></tag>
   <elementGuidId>656f0968-05f9-4f47-b6ef-f7bc40f7dbff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FLOORNO']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FLOORNO</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3da4bf3c-fe0a-4a5c-971c-b78f99d2db81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd321f0e-fbbf-4801-853e-95dfb83b99c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FLOORNO</value>
      <webElementGuid>935bd000-d56e-4eec-a1a4-0ab88b8efd55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>address.FLOORNO</value>
      <webElementGuid>04a6e59a-fdf8-4119-9b1d-474a099952f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>140</value>
      <webElementGuid>1bd035fd-6cba-406b-a2a1-f4481c4e01eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>{'background-color': address.ADDRESS_TYPE!='1200000009' ?  '#ffffff' : '#ebf3ff'}</value>
      <webElementGuid>216dd0de-a9c9-402f-89a6-2167a2d57582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-valid-maxlength</value>
      <webElementGuid>1d137707-37bf-4c48-8a0f-20a1e51d6fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FLOORNO&quot;)</value>
      <webElementGuid>875fb83a-9948-41e1-aa07-fcd8729973c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FLOORNO']</value>
      <webElementGuid>0d2541eb-6238-43f2-84c2-a34fcef2f54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addressDivForDisabled']/div[6]/input</value>
      <webElementGuid>e353d006-ec1c-4621-82b5-5191e7432650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/fieldset/div/div[6]/input</value>
      <webElementGuid>12fc67b8-bdfb-4f22-9969-6f7d7bbaf228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FLOORNO']</value>
      <webElementGuid>644491d8-e067-424b-a966-d660a7312f9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
