<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_APPLICANT</name>
   <tag></tag>
   <elementGuidId>d1c693bb-8971-48f9-8e5b-f9c9f8c6e275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.noLine</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>444927e6-1aee-40ae-96b4-3d1b5b9dfd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>pdeApplicantList.do?actionPerformed=displayPDECustomerList&amp;screenId=1000000090&amp;mode=E&amp;disName=APPLICANT</value>
      <webElementGuid>1ff0ca82-4a19-4654-9829-fdc68db42701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noLine</value>
      <webElementGuid>ce99fa57-ff69-4e0d-96c3-e86e22f2f87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>APPLICANT</value>
      <webElementGuid>e4875c12-1b23-46b1-8c35-c5d099974549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;menu col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[1]/a[@class=&quot;noLine&quot;]</value>
      <webElementGuid>0987977c-7206-4a89-a802-13afa1cfbfb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div/div/a</value>
      <webElementGuid>5c8d220c-4110-4ca9-9e42-105a9d2d2e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'APPLICANT')]</value>
      <webElementGuid>70f6b138-dd11-4435-a939-bb86a33a50d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::a[1]</value>
      <webElementGuid>84cb288b-a5b0-4f55-ac54-18fecb679d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save &amp; Exit'])[1]/following::a[2]</value>
      <webElementGuid>0150ff9d-43c1-4bf2-a9d9-57f6c7ba1140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOCUMENT'])[1]/preceding::a[1]</value>
      <webElementGuid>7a8447f4-1c41-4eca-8b3b-08b579c7fd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTEPAD'])[1]/preceding::a[2]</value>
      <webElementGuid>13bd4c1f-576e-4bb8-8802-53f09940803d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='APPLICANT']/parent::*</value>
      <webElementGuid>056fab8d-d98e-4cfa-b61c-91fcf3e637f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'pdeApplicantList.do?actionPerformed=displayPDECustomerList&amp;screenId=1000000090&amp;mode=E&amp;disName=APPLICANT')]</value>
      <webElementGuid>2d0bbc4a-b689-4bd9-bfe0-785cee2020ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a</value>
      <webElementGuid>04062810-0247-48ce-8de4-547624a90180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'pdeApplicantList.do?actionPerformed=displayPDECustomerList&amp;screenId=1000000090&amp;mode=E&amp;disName=APPLICANT' and (text() = 'APPLICANT' or . = 'APPLICANT')]</value>
      <webElementGuid>ed27b0bb-350e-4035-8e4b-d3d0327f74b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
