<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_DM VIEWER_img1000000017</name>
   <tag></tag>
   <elementGuidId>b0a74087-a22e-4767-bb38-215c0b179ab7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img1000000017</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='img1000000017']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>95b072d3-f0a8-4d7d-ae7d-dba222c07df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img1000000017</value>
      <webElementGuid>e183dc9a-7177-4464-89e6-6de860c0641c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>befce919-bcf1-48bb-892a-987495c336ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9c0f41ff-49f0-4b73-8767-0915afc490ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img1000000017&quot;)</value>
      <webElementGuid>9173c33b-99ed-4e39-9b7d-07162dff35ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='img1000000017']</value>
      <webElementGuid>0593fed4-c2bd-492f-8b81-365055c71292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='imgDiv']/i)[19]</value>
      <webElementGuid>9f28f2ad-9625-4dce-a55b-e719e25988fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[74]/div/div/i</value>
      <webElementGuid>f1ac4f24-d7fb-40a7-be1d-11f03d7f5103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'img1000000017']</value>
      <webElementGuid>ae34f53e-9c79-4f7b-89e7-84aa9a44729a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
