<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_INVOICE_img1200106858</name>
   <tag></tag>
   <elementGuidId>686a6a95-9b83-435a-89eb-4c4ca37db997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img1200106858</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='img1200106858']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>18ad8e29-2a13-400a-ba11-1c0d6d56a7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img1200106858</value>
      <webElementGuid>f51d9cd9-581a-4969-9d86-1437ba5c71ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>5d054809-918a-4e9b-b13e-80ed3ae286a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dac66e53-5a6c-478b-9bb1-55eba591ff0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img1200106858&quot;)</value>
      <webElementGuid>dec360f7-42c2-4286-9966-4a85ea37cfd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='img1200106858']</value>
      <webElementGuid>44522756-6458-49d2-8173-0d70d30ae210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='imgDiv']/i)[21]</value>
      <webElementGuid>beebe9eb-e6a3-4d14-bdde-1521de1960b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[78]/div/div/i</value>
      <webElementGuid>deeb0f5f-fae1-4060-acdb-f9c831d7e2b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'img1200106858']</value>
      <webElementGuid>b3d6c0a0-d37a-4613-986c-42be6a3625d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
