<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_VIEWER_img1200004000</name>
   <tag></tag>
   <elementGuidId>c2c51d90-ceb7-420b-bca0-1a4df30ec0da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img1200004000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='img1200004000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b6c201d4-20a5-4af3-a0be-1676305ed94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img1200004000</value>
      <webElementGuid>b9914a12-43fd-4d65-977d-b9aebe97fb10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>7ca89af3-c28d-49ec-ba3f-9d3b2ae512a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b8d38a5-9f16-4b6a-9b0f-104e3ba678b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img1200004000&quot;)</value>
      <webElementGuid>dca443af-a644-4a5a-93c4-ac34489a7342</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='img1200004000']</value>
      <webElementGuid>ffc3feb2-ab95-49a1-b5ac-687f5b903116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='imgDiv']/i)[14]</value>
      <webElementGuid>d258a8b2-361f-46d6-9fe1-b59fae0dd91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[52]/div/div/i</value>
      <webElementGuid>cc8db25f-75f3-4616-9f8e-50f966aff5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'img1200004000']</value>
      <webElementGuid>78a02855-9c0f-4e1e-8738-c2ba34b3b3ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
