<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Hi FARZANAN_userr_1</name>
   <tag></tag>
   <elementGuidId>57e1a3fe-15a5-4e18-8e7d-d5bc24dac1ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.userr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>437c97b0-3c3c-42f1-89ce-5ab0bf52f1db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>userr</value>
      <webElementGuid>58bc69d9-af39-4e8b-b98b-cdae7ac422c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/picuser_head.png</value>
      <webElementGuid>3960b4f2-72a9-4fcf-a32d-951bb2193616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-scope menuHavingBody&quot;]/form[@class=&quot;ng-pristine ng-valid&quot;]/div[@class=&quot;backe_image col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[1]/div[@class=&quot;col-lg-4 col-md-4 col-sm-4 col-xs-4&quot;]/div[1]/span[@class=&quot;username_icon&quot;]/img[@class=&quot;userr&quot;]</value>
      <webElementGuid>667ac6e7-d202-4575-b237-10d6e0799355</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>6778d037-8985-4abe-87a2-72501a07f016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/picuser_head.png']</value>
      <webElementGuid>cb5144b5-3fea-4321-ad4e-f9521999072b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
