<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MICR Code_btnEditBankName</name>
   <tag></tag>
   <elementGuidId>1c32c1c5-d2be-40ba-8f43-d21a186e9b98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;btnEditBankName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='btnEditBankName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>efe55910-02ea-45b8-a281-651107c5ef19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d6d1cd62-5f05-4848-9ed4-d34360b95c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blueBotton</value>
      <webElementGuid>2590482d-71fa-4c69-a952-e4d6d042be66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnEditBankName</value>
      <webElementGuid>6bc60d90-a2f9-4f0b-8344-00460a3353ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>39175971-16e8-4f7f-ac09-1e8a7727605d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:bankValueChooser(this,'branchNameId','accountNameId','ifscCode','micrCode');</value>
      <webElementGuid>24807c54-c31d-4cb2-a810-edac0094e2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>f32e0364-f93a-4067-9796-41b0735b9959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bankInfo&quot;)/tbody[1]/tr[2]/td[3]/input[@class=&quot;blueBotton&quot;]</value>
      <webElementGuid>cc2344cd-6966-4f84-8aa9-d4be66fd99f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='btnEditBankName']</value>
      <webElementGuid>9e79a54d-05f0-4282-ad39-0cc85207e92e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='bankInfo']/tbody/tr[2]/td[3]/input[3]</value>
      <webElementGuid>eec5ac12-9a3c-4974-b618-9f25caa51561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input[3]</value>
      <webElementGuid>d49aa73c-7d9a-4ca5-80c6-9e73c1aedadd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btnEditBankName' and @title = '...']</value>
      <webElementGuid>ddd88d6d-8a95-4ac8-bc83-496ceb7066db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
