<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_National IDBRNPP No_generalFilter</name>
   <tag></tag>
   <elementGuidId>a3bc85a1-a0b6-405f-b0b0-f3642888ee6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#generalFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='generalFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d43c1a6-d88c-471e-a442-ef2dc89916fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_header_cost ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>c4884fbf-d042-4ba2-8ecd-753ab5229bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73ebdd40-16e2-41e9-908d-dcad15b9c605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>generalFilter</value>
      <webElementGuid>72d51143-0553-4dfc-9e68-3fd7607ef3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>searchData.generalFilter</value>
      <webElementGuid>20f4d6b0-337b-4b4e-a190-16ae2ba33da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;generalFilter&quot;)</value>
      <webElementGuid>1e66a8c7-7114-4a52-9307-054c43cde36c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='generalFilter']</value>
      <webElementGuid>c689bf1f-02d7-47ea-9a94-396c02f28796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='dashbord_main']/form/div[5]/div/div/div[18]/input</value>
      <webElementGuid>a14b03d0-612b-4f96-9f9d-5bac44d76215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/input</value>
      <webElementGuid>d1c1be23-26c4-4d40-b677-2ccf7d7944de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'generalFilter']</value>
      <webElementGuid>b81dcb5a-04ea-4aca-8fe5-79ea28071155</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
