<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Y_sendToAuthor</name>
   <tag></tag>
   <elementGuidId>11bab017-fe3b-441c-bda3-5b69e7d7ede8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;sendToAuthor&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='sendToAuthor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6bc5a1f7-be86-4f7f-acb3-ff092da8ddb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5eca3f40-af01-4bcf-a610-256954deec60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm</value>
      <webElementGuid>6ccd866f-e537-43bb-9a28-44b87c840484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sendToAuthor</value>
      <webElementGuid>a0c01029-d01a-40b4-a08a-ff7333afe376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Send To Author</value>
      <webElementGuid>196606be-5b00-487e-a73d-3c46ff8be90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:sendStatusToAuthor(1000038416,1000000001)</value>
      <webElementGuid>04538251-0cdc-4265-8c34-de769da53658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;disableForClosedForeclsedCase&quot;)/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/table[1]/tbody[1]/tr[@class=&quot;alt_grid_style&quot;]/td[8]/input[@class=&quot;btn btn-primary btn-sm&quot;]</value>
      <webElementGuid>fc9a4af6-9c5b-426c-ac17-1a3ebee30698</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='sendToAuthor']</value>
      <webElementGuid>92f952dc-49c4-4952-9a74-ad72af36cb8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='disableForClosedForeclsedCase']/div[3]/div/table/tbody/tr[3]/td[8]/input</value>
      <webElementGuid>12f8fcf9-6387-4744-96f5-64887c63c9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/input</value>
      <webElementGuid>f770ff3d-dae1-462e-b8b6-557dda53a02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'sendToAuthor']</value>
      <webElementGuid>c2b69f45-f18a-45bf-a01f-44cf25706c3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
