<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Assignation in favour of CFSL_INS_START_DATE0 (1)</name>
   <tag></tag>
   <elementGuidId>339ed621-9aa8-467e-b4e5-0ac17f11d3a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#INS_START_DATE0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='INS_START_DATE0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6dc99a86-11b2-48e9-8cec-3575f356439b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_header_cost ng-pristine ng-untouched ng-valid ng-valid-maxlength</value>
      <webElementGuid>f4d2b1fa-715f-44ac-95b5-07b1ceec48c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>57e0f813-0a02-4a98-af36-a8e1e4a1fc1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>INS_START_DATE0</value>
      <webElementGuid>3412e26d-e153-46c1-94b7-4f04b7f68415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>itr_obj.INS_START_DATE</value>
      <webElementGuid>23b0e253-cd85-4315-b113-5b7a43f13cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f9531b7d-15cb-416a-bee8-02cf7625887e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:checkDateFormat(this,'INS. START DATE');</value>
      <webElementGuid>1f083e32-bcf7-4105-85fb-9c2266dfaab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD-MON-YYYY</value>
      <webElementGuid>415c7b32-270b-46f7-8ede-6f998b52742d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>rowDisabled</value>
      <webElementGuid>a34ddb27-3610-425e-9147-7e8c87b72575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;INS_START_DATE0&quot;)</value>
      <webElementGuid>7172062c-ca86-406c-b5e1-1162ae57729f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='INS_START_DATE0']</value>
      <webElementGuid>25601bb1-a7a3-4736-974e-601a5e18e003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='disableForClosedForeclsedCase']/div[9]/table/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>c3c1a477-3560-4f83-a8fe-acf8ea81dc73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>e48abf6d-9a92-4f8d-a260-0d3324320f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'INS_START_DATE0' and @placeholder = 'DD-MON-YYYY']</value>
      <webElementGuid>35576c65-a282-4c7b-a1e2-c2f6f2e64933</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
