<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Engine No_ENGINE_NO</name>
   <tag></tag>
   <elementGuidId>75bda864-4da3-4fcf-890c-44b8b8bcfd73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ENGINE_NO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ENGINE_NO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed6c83a3-8c12-4fff-afe3-6da2f90e651e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8a8c122-5f49-4769-817a-4ad4de1c60bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ENGINE_NO</value>
      <webElementGuid>8e99c567-2e4b-487d-846f-70e6ed3dc591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>user.ENGINE_NO</value>
      <webElementGuid>85797ad7-73c6-4bf4-af32-b25eb67ef936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>333ac7a9-439a-41d3-8fad-4903ac5b2f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newIndSect&quot;)/div[@class=&quot;col-lg-2 col-md-2 col-sm-3 col-xs-6&quot;]/input[@id=&quot;ENGINE_NO&quot;]</value>
      <webElementGuid>d640e931-0d94-47ca-973a-9ffb4b1587f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ENGINE_NO']</value>
      <webElementGuid>86174d50-83a9-4c1e-aac3-dd2611682477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newIndSect']/div[28]/input</value>
      <webElementGuid>d24c5b4e-bf68-4c2f-979d-cbaa92fd5b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/input</value>
      <webElementGuid>9080bbde-a5a8-4cb1-bf54-3d5556992b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ENGINE_NO']</value>
      <webElementGuid>595f8c99-47f7-46d0-a9df-44fd47fe5e01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
