<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Assignation in favour of CFSL_INS_START_DATE0</name>
   <tag></tag>
   <elementGuidId>7e195560-f24b-4572-86af-3375cdd10e8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#INS_START_DATE0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='INS_START_DATE0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19903f2b-605f-47b6-8215-6c629ccfa6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_header_cost ng-pristine ng-untouched ng-valid ng-valid-maxlength</value>
      <webElementGuid>8cdc0dc6-34c7-4b73-afbb-34b123a08cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba25df9f-9b31-435a-9d98-1ffc303ac752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>INS_START_DATE0</value>
      <webElementGuid>1a9b290d-06a4-410b-8fe1-3d5779fcae0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>itr_obj.INS_START_DATE</value>
      <webElementGuid>6ad9d028-89d4-46e4-85b6-7f853e0a1c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>2a081720-0500-4241-b2f3-8e47417af5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:checkDateFormat(this,'INS. START DATE');</value>
      <webElementGuid>e94ecf66-7b20-45e3-869a-e0ce546ce43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD-MON-YYYY</value>
      <webElementGuid>d2384061-ad03-4b1c-b639-a42a14ce2f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>rowDisabled</value>
      <webElementGuid>4cb44273-45fa-4bae-b372-18ee131dbbbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;INS_START_DATE0&quot;)</value>
      <webElementGuid>815e872c-11a3-429e-af36-3f53d30439ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='INS_START_DATE0']</value>
      <webElementGuid>f89d8eeb-bab9-4a19-8524-61a5c1c3f1fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='disableForClosedForeclsedCase']/div[9]/table/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>93135a25-a6e8-40d5-8b3a-30d44685e6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>6d3a1fe7-a12c-42d2-878c-1f6444ead164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'INS_START_DATE0' and @placeholder = 'DD-MON-YYYY']</value>
      <webElementGuid>486f5ce1-0f61-4bfb-a93f-bdadec6ae977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
