<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECTUSDGBPEURMUR</name>
   <tag></tag>
   <elementGuidId>ab5a305d-6ed9-4398-8157-0e1d29bd6fb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;currency&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='currency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>50e70e73-2eb2-4c6d-8aba-9afb9fea1213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>f9d1745f-0e01-4348-a220-8eac8c475c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
														    SELECT									
														USDGBPEURMUR</value>
      <webElementGuid>b3bededb-7a76-43be-9ac7-af789166f625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bankInfo&quot;)/tbody[1]/tr[2]/td[7]/select[1]</value>
      <webElementGuid>9690997b-2b69-46da-8b7d-9204cfc24ec3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='currency']</value>
      <webElementGuid>ae3e5ebe-726b-45ef-9f22-91f371064236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='bankInfo']/tbody/tr[2]/td[7]/select</value>
      <webElementGuid>8e30e800-ea22-4bf8-b77d-0a67ee5efde4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MICR Code'])[1]/following::select[2]</value>
      <webElementGuid>dc05888e-91c1-4b86-9205-c8c93c43bf06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/following::select[2]</value>
      <webElementGuid>83101577-cfd9-4aa6-9be1-3abf5e6444c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OTHER LOANS DETAILS'])[1]/preceding::select[2]</value>
      <webElementGuid>c8ec7468-1474-41bd-ae5d-dd03dbd508f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Institution From'])[1]/preceding::select[2]</value>
      <webElementGuid>cc494f4d-4b83-4db3-9f32-38cfc0d846b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/select</value>
      <webElementGuid>326f30b5-927b-4dd9-8061-d0561b05d6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'currency' and (text() = '
														    SELECT									
														USDGBPEURMUR' or . = '
														    SELECT									
														USDGBPEURMUR')]</value>
      <webElementGuid>b45fc0a1-33a1-426d-9368-caf44026bfa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
