<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>font_123456789</name>
   <tag></tag>
   <elementGuidId>8a6e1f6b-d2aa-44cb-9bff-f3e90005dc8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='123456789']/table/tbody/tr/td[2]/a/font</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>font.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>7e4a9343-1ea6-42d6-9157-db98c54b8e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>2px</value>
      <webElementGuid>c064b325-f372-4b40-9f20-914829fb0b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>9368417b-1627-4960-92e8-57d6be8cf7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>123456789</value>
      <webElementGuid>011303ad-5e18-4efb-bb70-685980ac0802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;123456789&quot;)/table[1]/tbody[1]/tr[1]/td[2]/a[1]/font[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>3f3f3d78-9953-4435-a92e-687e7c87452c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='123456789']/table/tbody/tr/td[2]/a/font</value>
      <webElementGuid>3c5125d1-ad33-4f91-8eff-8c41472af4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/following::font[1]</value>
      <webElementGuid>cc71818f-985c-4b93-b76f-508481c1abcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[1]/following::font[2]</value>
      <webElementGuid>92a49ceb-e9b7-4555-ad68-9c0b7af4af36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/font</value>
      <webElementGuid>8296692e-e84f-4f70-872d-f9230c3409fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//font[(text() = '123456789' or . = '123456789')]</value>
      <webElementGuid>45166913-8eeb-4fbd-a09b-27ab76223e46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
