<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_OK</name>
   <tag></tag>
   <elementGuidId>b3b89e4d-c40f-4b59-b351-9928d10b8f1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='OK']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;OK&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3c98823-b1d3-4c72-af30-a236be35f1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>01ed4e43-10d9-4086-995b-7bb18d125911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm</value>
      <webElementGuid>6639c530-ddcd-4084-9d1a-e5276dd8fb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>505d8237-eac4-41f0-83a7-898fcf132ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>ae487ca3-1182-414e-afd0-1e0f4d95aa04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>submitForm();</value>
      <webElementGuid>4f71e910-b7c8-4d99-bf67-4e8c08cb7b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LovParent&quot;)/table[2]/tbody[1]/tr[@class=&quot;gray_tr&quot;]/td[1]/input[@class=&quot;btn btn-primary btn-sm&quot;]</value>
      <webElementGuid>472121e9-1d46-4276-af81-e6ff265bd9b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='OK']</value>
      <webElementGuid>2a49fcbd-1cec-4999-9524-fb8cd05eaec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LovParent']/table[2]/tbody/tr/td/input</value>
      <webElementGuid>45b82714-60bf-4a37-b9d2-4a4da8aab059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>a2dc08cb-7330-49f2-9521-d03198b01c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'OK']</value>
      <webElementGuid>4404f720-6c0d-40de-aaa8-562c44d99b04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
