<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DOCUMENT</name>
   <tag></tag>
   <elementGuidId>8796c8f6-c342-43a0-a042-836faf89c7c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div/div[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e2f0e062-3e00-46d1-b5e7-1efc0304667a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>documentEntryAction.do?actionPerformed=displayDocumentEntry&amp;screenId=1000000082&amp;mode=E&amp;disName=DOCUMENT</value>
      <webElementGuid>ffd5279c-be43-4dd0-baad-342892ad527d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noLine</value>
      <webElementGuid>340d2dd2-7b97-443f-9ec0-3e48b08c4e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DOCUMENT</value>
      <webElementGuid>2c9354ef-248e-4b2a-8205-0ba43da0a761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;menu col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[5]/a[@class=&quot;noLine&quot;]</value>
      <webElementGuid>56322594-fee5-42ea-9e68-00b410c9e568</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div/div[5]/a</value>
      <webElementGuid>ebec70ab-accb-42d6-b219-6fc801e6f7dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DOCUMENT')]</value>
      <webElementGuid>7b952c67-e048-4e6e-b59a-ea912f2a896e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CR REVIEW'])[2]/following::a[1]</value>
      <webElementGuid>87957027-d5d5-403d-a94c-d8269bf9c86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTEPAD'])[1]/following::a[2]</value>
      <webElementGuid>5f216fe5-5b2a-420c-87e6-f853c91d550d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPLICANT CODE'])[1]/preceding::a[1]</value>
      <webElementGuid>9fed3731-b7af-4649-a0b7-d1c961c70bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNCIMF000003113'])[1]/preceding::a[1]</value>
      <webElementGuid>37f7ba97-29f8-4af8-8427-e23278aa47a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DOCUMENT']/parent::*</value>
      <webElementGuid>518b7652-fa32-443b-b1b2-0893d999bf82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'documentEntryAction.do?actionPerformed=displayDocumentEntry&amp;screenId=1000000082&amp;mode=E&amp;disName=DOCUMENT')]</value>
      <webElementGuid>fe5ce8f2-c776-4128-8b53-0e50885b0344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>133def9c-38bb-4717-ae78-50a4e9812ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'documentEntryAction.do?actionPerformed=displayDocumentEntry&amp;screenId=1000000082&amp;mode=E&amp;disName=DOCUMENT' and (text() = 'DOCUMENT' or . = 'DOCUMENT')]</value>
      <webElementGuid>4fa9b3a1-c294-43e5-9c8b-44a0c2a8d099</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
