<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_National IDBRNPP No_pageneation</name>
   <tag></tag>
   <elementGuidId>8ea0bf1f-b38c-48ed-a4aa-70d1f2b57800</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pageneation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pageneation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a1ccb3ab-b214-452a-8802-4e380715cf76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pageneation</value>
      <webElementGuid>1e373d7e-baaf-4b10-9302-e3ad996fe958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageneation&quot;)</value>
      <webElementGuid>ab3c54e4-0539-412a-a09c-f7a9aac852a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pageneation']</value>
      <webElementGuid>ff1e0088-68fb-47e2-b5bd-01c60e679eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dasiTd']/div/div[17]</value>
      <webElementGuid>774d1c8a-2166-45ac-b0d4-44f3c7b15395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='National ID/BRN/PP No.'])[1]/following::div[4]</value>
      <webElementGuid>157586a4-9dbf-488d-9d35-d78ccff31f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/following::div[6]</value>
      <webElementGuid>2cca1d4e-5846-461f-8cfd-e95a6db67fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qualtech Consultants Pvt. Ltd.'])[1]/preceding::div[1]</value>
      <webElementGuid>31d86349-ca80-486d-9235-33b6065c8723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VERSION 1.0.1.176.2'])[1]/preceding::div[2]</value>
      <webElementGuid>084c95bc-e453-4a89-aba7-f3bde533c093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr/td/div/div[17]</value>
      <webElementGuid>f7dc0dcc-3348-4341-93cf-c57c23ede99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pageneation']</value>
      <webElementGuid>729c712e-cbd6-49ca-ac4c-072a4c4bed96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
