<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DMFIN1000008443</name>
   <tag></tag>
   <elementGuidId>e504d5e6-e9b6-4fe6-88c6-0388becdd398</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='allProspectEntries']/table/tbody/tr/td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>445fd3d2-d451-4e43-a6d2-97a7499202c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:showDetail('DMFIN1000008443','1000090854','1000038935','1000008443','1000000008')</value>
      <webElementGuid>1f34e057-ae9b-4e1a-8d0f-850e877493a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DMFIN1000008443 </value>
      <webElementGuid>9e01ac9b-cad5-45aa-a060-4275584a330e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allProspectEntries&quot;)/table[@class=&quot;tr_list&quot;]/tbody[1]/tr[@class=&quot;tr_list_bgred&quot;]/td[3]/a[1]</value>
      <webElementGuid>bb03f85b-1d4b-43f3-a557-9078d1217aef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allProspectEntries']/table/tbody/tr/td[3]/a</value>
      <webElementGuid>dc59f1a4-9af9-48ad-a31d-1e089c9bc2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DMFIN1000008443')]</value>
      <webElementGuid>09b1a1ce-711e-4782-bfb8-6ed6da82ff23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FL + FLOATING + MAINTENANCE'])[2]/following::a[1]</value>
      <webElementGuid>101b1bc7-d9b8-4490-bab7-f7074832e94b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNCIMF000003724'])[1]/preceding::a[1]</value>
      <webElementGuid>b2d24f5f-5e30-4a44-884b-1ccbc12551b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DMFIN1000008443']/parent::*</value>
      <webElementGuid>ebeeb97b-bc75-4eca-a211-e0fb4a63a77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:showDetail('DMFIN1000008443','1000090854','1000038935','1000008443','1000000008')&quot;)]</value>
      <webElementGuid>38176e6f-5eb9-4069-b84d-d87e8ab38a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>43d85624-9182-48bf-b3e1-45f1245fe535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:showDetail(&quot; , &quot;'&quot; , &quot;DMFIN1000008443&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000090854&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000038935&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000008443&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000000008&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'DMFIN1000008443 ' or . = 'DMFIN1000008443 ')]</value>
      <webElementGuid>237cf63a-470e-4225-adc7-21fdcc5597a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
