<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_miFIN_userId</name>
   <tag></tag>
   <elementGuidId>a0d36f44-3197-4394-af81-b44c1d287fac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='userId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;userId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c56d981-94f1-42dc-a6d5-cc34e4fb56e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userId</value>
      <webElementGuid>9362241c-7251-4d8a-b951-611ac23b69fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>513f17c8-d091-4bf2-9229-01ad990c84cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>c760f68e-e69c-4072-b2a0-e40afa966ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>a7d723a2-6b6b-4209-8b21-b2efffeb087a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b018fe9c-293b-4298-bd13-c8a46d312fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginPage_id&quot;)/form[1]/div[@class=&quot;main_divlogin&quot;]/div[@class=&quot;row-centered&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12 col-centered&quot;]/div[@class=&quot;login_inputBox&quot;]/div[@class=&quot;user_td&quot;]/input[1]</value>
      <webElementGuid>6565c285-47bf-43dc-89ed-0c21c497567f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='userId']</value>
      <webElementGuid>2735659b-404e-4672-af00-67acf691da55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='loginPage_id']/form/div[2]/div/div/div/div/input</value>
      <webElementGuid>0d84ef17-c1b0-41b4-be1f-0ba9984d5241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3dd58bf7-ea66-4f5e-b59b-7646cc81afa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'userId' and @type = 'text']</value>
      <webElementGuid>10e3e3ff-0580-47ad-804c-773e8af1cce6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
