<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DM Code_dmCode</name>
   <tag></tag>
   <elementGuidId>b71bd7c7-1e52-482f-95b4-8cbd281f8036</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dmCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dmCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>822b7f11-e3bc-46b8-aa71-1182ce8757b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_header_cost ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>932ca8fa-a617-4159-a9f9-40fe3fb1c695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f28d838-5e28-4eb8-a6e2-c4ccfbf4df06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dmCode</value>
      <webElementGuid>66fb9459-04ec-4ad7-85b6-9193ccf6d4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>searchData.dmCode</value>
      <webElementGuid>50bbde85-3b37-4319-adf0-f0c7d1e5e982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dmCode&quot;)</value>
      <webElementGuid>d8d3e4c7-4b34-4ba3-a618-2a8b64dc1966</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dmCode']</value>
      <webElementGuid>0c41f155-a2a8-4276-8ed3-3531c7d8fce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='dashbord_main']/form/div[5]/div/div/div[12]/input</value>
      <webElementGuid>a8eef715-2295-44f0-bdb8-54bac8c0748a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/input</value>
      <webElementGuid>860acebc-1a4b-484f-8a13-0db8b534444d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dmCode']</value>
      <webElementGuid>6a9c82a8-aaed-4ec4-93ab-f7bb9feda609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
