<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Remarks_arRemarks</name>
   <tag></tag>
   <elementGuidId>543a6ef9-56cc-4189-bf25-4404a22d9d5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='arRemarksId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#arRemarksId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b5fb09d4-8a3a-4a47-b34c-99b9c17178ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>arRemarks</value>
      <webElementGuid>e41379aa-e3e8-4936-8bb0-ab612cdc39c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>57d53db6-97bc-401e-8ed1-9e2c68082143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e3ff91b1-efe1-404c-8312-5fdbb3e4d861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkRemark(this,'Author Remark')</value>
      <webElementGuid>657f4fae-b484-41ae-a556-94a900d9fbd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arRemarksId</value>
      <webElementGuid>f8f04fe1-6e5d-41f5-875a-a7aaad33c2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arRemarksId&quot;)</value>
      <webElementGuid>6287c5fd-7a0c-4dc2-b19d-e8054c3cf63f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='arRemarksId']</value>
      <webElementGuid>b518de91-d1ba-4b27-915c-772d5004e8ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fieldSetId']/div[3]/div/div[2]/textarea</value>
      <webElementGuid>90c52767-0463-415b-b1e4-756b1d617b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/textarea</value>
      <webElementGuid>1cdf3fd7-f5f9-4ab8-89ea-3181fea40fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'arRemarks' and @id = 'arRemarksId']</value>
      <webElementGuid>57633fb4-314a-402d-88bc-94956d84ec11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
