<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_APPLICANT</name>
   <tag></tag>
   <elementGuidId>23122c57-9b42-4ed6-830e-d84c120ba16f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.noLine</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e5953722-5875-46b6-8c11-02c12260034f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>applicantList.do?actionPerformed=displayCustomerList&amp;screenId=1000000079&amp;mode=E&amp;disName=APPLICANT</value>
      <webElementGuid>d756c0e6-1e7d-490d-80fc-2bda6a684cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noLine</value>
      <webElementGuid>93ed9494-22ba-4d50-a14a-2daef2d9661e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>APPLICANT</value>
      <webElementGuid>c90a48ef-41d8-493e-86ca-0e66563712d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;menu col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[1]/a[@class=&quot;noLine&quot;]</value>
      <webElementGuid>940c3973-4fbb-455b-89e6-cccfcd58d372</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div/div/a</value>
      <webElementGuid>dcf98729-a968-4c2a-9d92-a9cc7889c21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'APPLICANT')]</value>
      <webElementGuid>2314b67d-3159-499c-b7ca-2f9b92916561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::a[1]</value>
      <webElementGuid>e378f967-fd6d-41ac-80ce-c938301fda14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save &amp; Exit'])[1]/following::a[2]</value>
      <webElementGuid>ae904f94-6ff0-4d49-aabc-d84dfe5f4bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEDUPE'])[1]/preceding::a[1]</value>
      <webElementGuid>e0f7cd34-92f4-41f8-8279-18da6884fd5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTEPAD'])[1]/preceding::a[2]</value>
      <webElementGuid>4b59aabb-ac8e-4082-9228-548c27370c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='APPLICANT']/parent::*</value>
      <webElementGuid>c39fb01d-4911-4b26-bd0d-f90129873ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'applicantList.do?actionPerformed=displayCustomerList&amp;screenId=1000000079&amp;mode=E&amp;disName=APPLICANT')]</value>
      <webElementGuid>d45aeccf-e379-4e54-bc3d-96795d36ada5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/a</value>
      <webElementGuid>8a3ad972-9323-4da4-814e-45677d1c7488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'applicantList.do?actionPerformed=displayCustomerList&amp;screenId=1000000079&amp;mode=E&amp;disName=APPLICANT' and (text() = 'APPLICANT' or . = 'APPLICANT')]</value>
      <webElementGuid>a073daa1-a0b2-4cf2-85a3-da0956c053a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
