<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FINANCIAL  OTHER INFO</name>
   <tag></tag>
   <elementGuidId>7649ea65-ccf9-4460-9a9d-2ea553b22ff0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='FINANCIA0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FINANCIA0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>05661258-09ff-408b-b6db-4046ff051b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FINANCIA0</value>
      <webElementGuid>8b1e03d9-3594-463a-aee6-c428ef6f81ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>otherInfoNav.do?actionPerformed=displayCustomerOtherInfo&amp;screenId=1000001013&amp;ajaxCall=&amp;mode=E&amp;appType=1000000001&amp;appId=1000036775&amp;oldApplicantId=1000036775</value>
      <webElementGuid>aaa72bb2-dc5f-4c0c-ab0a-5389ea1e7cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FINANCIAL &amp; OTHER INFO</value>
      <webElementGuid>efad3d85-5a42-4563-afa2-cdbd04cf278a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FINANCIA0&quot;)</value>
      <webElementGuid>d5421070-d64f-4a31-ad4a-036c2b54c1d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='FINANCIA0']</value>
      <webElementGuid>a1179824-1383-4416-ab84-343d604cd385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='rowCheck0']/td[6]/a</value>
      <webElementGuid>94fd86e0-fa00-449b-97ac-f28c469e1b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'FINANCIAL &amp; OTHER INFO')]</value>
      <webElementGuid>6d58d628-8a8f-4afa-9758-bf4c68ce6f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPLICANT DETAIL'])[2]/following::a[1]</value>
      <webElementGuid>91f8cdbf-8e57-4115-9852-e02011fcddc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INDIVIDUAL'])[2]/following::a[2]</value>
      <webElementGuid>71ccd815-ace0-4abf-96c5-d3636ff9720f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LEAD DETAILS'])[2]/preceding::a[1]</value>
      <webElementGuid>d5aa2e55-9f1e-46fd-889c-4664cf1b1d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Y'])[1]/preceding::a[2]</value>
      <webElementGuid>23e8e80e-ce1e-48c4-b5cc-8393928983ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FINANCIAL &amp; OTHER INFO']/parent::*</value>
      <webElementGuid>ff283252-2828-47ea-8c48-f01ad735b7ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'otherInfoNav.do?actionPerformed=displayCustomerOtherInfo&amp;screenId=1000001013&amp;ajaxCall=&amp;mode=E&amp;appType=1000000001&amp;appId=1000036775&amp;oldApplicantId=1000036775')]</value>
      <webElementGuid>fc8d6124-96db-4546-a689-b6507833459f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>a282354a-d52e-4d3a-aabb-08f00561d0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'FINANCIA0' and @href = 'otherInfoNav.do?actionPerformed=displayCustomerOtherInfo&amp;screenId=1000001013&amp;ajaxCall=&amp;mode=E&amp;appType=1000000001&amp;appId=1000036775&amp;oldApplicantId=1000036775' and (text() = 'FINANCIAL &amp; OTHER INFO' or . = 'FINANCIAL &amp; OTHER INFO')]</value>
      <webElementGuid>263130bd-8dcf-4392-9102-b461dff42e31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
