<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_YearsMonth_noOfMonthAtResidence</name>
   <tag></tag>
   <elementGuidId>db5fe9fc-1f86-434f-a1c1-0d0275d0c050</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='noOfMonthAtResidence']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;noOfMonthAtResidence&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dcb83ad4-7300-432f-a254-f8f7f99919e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02d699bb-4665-49ff-a621-1a47348a4c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>noOfMonthAtResidence</value>
      <webElementGuid>bd70e50f-b2a1-40c8-8683-e10018a2d7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e129f3d0-dc4a-47f8-85f8-8616cd6e63d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>0b2ddfca-d525-4401-a347-3a351925e7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkNumeric(this,'MONTHS')</value>
      <webElementGuid>b4ab742c-3b7b-4318-8792-5899bcd7d2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;residence&quot;)/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;yrsInput col-lg-2 col-md-2 col-sm-3 col-xs-6&quot;]/input[2]</value>
      <webElementGuid>8e16b3cf-2200-4b66-a0bb-3ada929b91ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='noOfMonthAtResidence']</value>
      <webElementGuid>a851f824-394b-4a95-93ed-63d5bc028596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='residence']/div/div[2]/div[30]/input[2]</value>
      <webElementGuid>4da9e49e-c073-4e1d-a528-2034704dc1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[30]/input[2]</value>
      <webElementGuid>83edd20a-6db7-4c97-8b1c-025314aabe66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'noOfMonthAtResidence']</value>
      <webElementGuid>4e775cd9-4ad4-4031-a0d6-331f752a749e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
