<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_N_reInitiate</name>
   <tag></tag>
   <elementGuidId>52f9662b-c53d-49f8-a2b6-ef253ce6d256</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reInitiate0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reInitiate0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a13af5bc-aaaa-40dc-9ddd-b2079f773fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e12aee5-cb2a-484d-b5bb-1cc771b500a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reInitiate</value>
      <webElementGuid>9c518dca-cc9d-472a-9820-8a5682d48ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reInitiate0</value>
      <webElementGuid>3e4baad5-0580-4cf3-b414-de82484dfb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>INITIATE DEDUPE</value>
      <webElementGuid>69a34918-b0bd-4b9e-936a-95edc8e0f581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>blockClick();reInitiateDedupe('1000036775');</value>
      <webElementGuid>a64f97ad-191f-42fd-bd56-fcbfee966c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blueBotton</value>
      <webElementGuid>3bbaf244-0ba2-45d7-95eb-6ef340a368d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>INITIATE DEDUPE</value>
      <webElementGuid>bd410578-c50e-44f1-b474-22190c8a7728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reInitiate0&quot;)</value>
      <webElementGuid>4ed902e2-633f-4b51-8518-700a2f11837b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reInitiate0']</value>
      <webElementGuid>c2917be9-b0a1-413e-bc51-007c1074ad06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='rowCheck0']/td[12]/input</value>
      <webElementGuid>ab7f857e-5dfb-46c0-8a2a-97ad372de052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/input</value>
      <webElementGuid>1e759f06-a06a-4bea-a615-3dc65e3b281b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'reInitiate' and @id = 'reInitiate0' and @title = 'INITIATE DEDUPE']</value>
      <webElementGuid>410bedd2-31d3-4772-81ad-a00bb390eeb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
