<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select Document_updated</name>
   <tag></tag>
   <elementGuidId>8f04c561-d755-47e8-a31c-ced8301e75aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[2]/td[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#updated0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78cae341-5f69-4e68-abcf-5f5dcc922a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0d72de81-3a02-4197-b2d8-2fd9308b729a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>updated</value>
      <webElementGuid>6b35114d-3888-41ec-b670-f1d7640058b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>updated0</value>
      <webElementGuid>8207f4e1-16e5-4936-8123-e8409c1e5928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>enableRecord(0
); toggleBrowse(this,'F' );</value>
      <webElementGuid>5f06a0d4-3c53-4fb9-a97b-1e76a12eecb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;updated0&quot;)</value>
      <webElementGuid>27fb19b2-c33a-4b92-9d9a-077e605624d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='updated0']</value>
      <webElementGuid>dbc8c728-dd4f-4690-b4f6-f404ba901dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='documentDataTable1']/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>e9c4f9f4-f6b5-432b-8770-17e4fd6acea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>7f13d99a-0f0b-4284-80ca-39f938686878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'updated' and @id = 'updated0']</value>
      <webElementGuid>0e3e88a3-11e0-4ae5-9ca2-eabb1510d2bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
