<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECTRECEIVEDPENDINGDEFERRED</name>
   <tag></tag>
   <elementGuidId>b5ba48e1-f456-4962-8468-248d89ceca1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='documentStatusId0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#documentStatusId0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4193281a-b6ed-46ba-8d08-397233d37c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>documentStatusId</value>
      <webElementGuid>df96095d-8939-4378-b71e-e65fee5b5b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentStatusId0</value>
      <webElementGuid>336d16ea-73d1-46ea-936f-5563993d8bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>disableReceivedDate(0
); toggleBrowse(this,'F');</value>
      <webElementGuid>55bbbc04-c512-402b-a9a6-3f1f44e2bdd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PENDING</value>
      <webElementGuid>8f0e2e9e-16bb-46d7-aa86-3d959713dd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
											
												SELECT
											
										RECEIVEDPENDINGDEFERRED</value>
      <webElementGuid>653c5b04-9001-4e98-ac82-7c7a9e6609de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;documentStatusId0&quot;)</value>
      <webElementGuid>da9d3e41-25dc-4ea7-962b-d921592cbf8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='documentStatusId0']</value>
      <webElementGuid>286784da-0f28-456c-95cc-19b6f135b915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='documentDataTable1']/tbody/tr[2]/td[6]/select</value>
      <webElementGuid>efded865-914d-426c-9e15-56bd03fd2aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Document'])[1]/following::select[3]</value>
      <webElementGuid>66779d71-816e-4b44-afd9-13c4fac40d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Updated Date'])[1]/following::select[3]</value>
      <webElementGuid>9081c5af-2668-44ad-b946-7cb316b30728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYSUSER'])[1]/preceding::select[2]</value>
      <webElementGuid>4b36b94d-465b-4808-914e-a23200556da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYSUSER'])[2]/preceding::select[6]</value>
      <webElementGuid>4c5239ac-0a29-4a48-b4fd-1a4799234c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/select</value>
      <webElementGuid>b9856409-a50a-4ded-8bd1-b1a98460ffb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'documentStatusId' and @id = 'documentStatusId0' and @title = 'PENDING' and (text() = '
											
												SELECT
											
										RECEIVEDPENDINGDEFERRED' or . = '
											
												SELECT
											
										RECEIVEDPENDINGDEFERRED')]</value>
      <webElementGuid>d0193354-4eec-449f-855f-08151167e14c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
