<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_DEDUPE COMP</name>
   <tag></tag>
   <elementGuidId>1c8a8bf8-47f4-4600-9bf5-9da6327095c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='dedupeId']/tbody/tr/td[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c3259daf-eb72-41f1-8026-3a111173a7bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>98d3c5ac-59ba-4522-afa5-0521dd195271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>9%</value>
      <webElementGuid>38c44686-d830-4d6d-bf3f-fb1ee28f7aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DEDUPE COMP</value>
      <webElementGuid>087581f7-e41d-4e1c-8391-51f82ae92d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dedupeId&quot;)/tbody[1]/tr[@class=&quot;list_header&quot;]/td[10]</value>
      <webElementGuid>dc01cd46-fc79-4746-9a79-d118be41dc99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dedupeId']/tbody/tr/td[10]</value>
      <webElementGuid>77f400b6-cb61-4342-87a0-59b6be1a63ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OTHERS COMP'])[1]/following::td[1]</value>
      <webElementGuid>b2b047cf-e271-4f40-afd6-7030db33cb67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPLICANT COMP'])[1]/following::td[2]</value>
      <webElementGuid>66422e87-06d1-49ec-9160-f32287788d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIBIL CHECK COMP'])[1]/preceding::td[1]</value>
      <webElementGuid>d85db102-ba19-417a-9d9b-4d55434c101f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEDUPE'])[3]/preceding::td[2]</value>
      <webElementGuid>c1d8990f-789a-4115-97c5-a7ca008ab2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DEDUPE COMP']/parent::*</value>
      <webElementGuid>99799102-8942-40e7-ad4c-ce9537b9ef7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]</value>
      <webElementGuid>b84f1647-12f9-4d6d-8090-1da7b514d6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'DEDUPE COMP' or . = 'DEDUPE COMP')]</value>
      <webElementGuid>bdb6bf77-d29c-4c00-944c-8936693f692a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
