<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Remarks_remarks_1</name>
   <tag></tag>
   <elementGuidId>8638ce0a-d36c-4289-8798-4af3836b1f1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textarea']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e67fbe89-501b-458a-9564-fb1749366dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>356f672e-fe7d-4dc7-b3cd-1d33743af484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>remarks</value>
      <webElementGuid>1bd38fff-f675-4f1a-9929-7783aa8bf16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>72</value>
      <webElementGuid>d5b477ab-5d08-4f05-bd00-ba8f3e72bfab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>o</value>
      <webElementGuid>7f0d5edb-1cef-45ef-b6b6-eb49a6ffbf46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textarea&quot;)</value>
      <webElementGuid>de996dde-e714-495d-a055-900da1d9ff9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textarea']</value>
      <webElementGuid>a3710299-44c2-43b5-8580-563af4d086c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notepadId']/div/div[2]/div[8]/span/textarea</value>
      <webElementGuid>540e9b41-b553-4016-8d17-e35ed27fc5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/span/textarea</value>
      <webElementGuid>b78185cf-d2bb-4bd3-b1b9-2700d1b54f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'textarea' and @name = 'remarks' and @title = 'o']</value>
      <webElementGuid>93eb5d9d-11b4-4218-bb2a-c1c9871e1567</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
