<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_SYSUSER_remarks</name>
   <tag></tag>
   <elementGuidId>5571f609-ec92-4294-a312-c4b53838d26c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='remarks1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#remarks1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b3cd945a-06ac-4fd4-90a2-bc651f4c6f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>remarks</value>
      <webElementGuid>c33ac097-6b6d-4deb-a8d2-d2c6d519e53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remarks1</value>
      <webElementGuid>d63d01d9-9e1f-4ec1-a8dd-43d3faffd88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkRemark(this,'Document Description');</value>
      <webElementGuid>4a9c0087-c368-4caf-ad40-b4b81e0cd9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>fd837e25-4161-4ea2-b84c-5a2b2e8be853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remarks1&quot;)</value>
      <webElementGuid>38bec46c-9fab-4506-af48-730457d3db86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='remarks1']</value>
      <webElementGuid>a7b7e47f-3fdf-4533-bbf2-b7303ec90d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='documentDataTable1']/tbody/tr[3]/td[5]/span/textarea</value>
      <webElementGuid>6ed841fd-8cc5-4297-8f32-f77881775117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/span/textarea</value>
      <webElementGuid>35606da0-2766-417f-a2d1-1653d7573958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'remarks' and @id = 'remarks1']</value>
      <webElementGuid>f8ff17a1-27d9-496f-b4d3-e84ed8a8c928</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
