<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_SYSUSER_remarks_1</name>
   <tag></tag>
   <elementGuidId>c801b0a7-96a2-4915-90a8-8e993e620bed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='remarks2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#remarks2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d7c6a109-3ec4-4c5d-8099-c22e61c2b0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>remarks</value>
      <webElementGuid>31a238fe-4d85-4f1c-af20-8bfbd388cc2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remarks2</value>
      <webElementGuid>b081d35a-2575-476c-85e4-cd4ac2e3a760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkRemark(this,'Document Description');</value>
      <webElementGuid>89559f5a-c193-42ca-bcb0-d39db0cba674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>d0cfc667-5542-4940-9de2-a286eaae2966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remarks2&quot;)</value>
      <webElementGuid>62afe101-341f-4ff0-9263-9d762cd8c1aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='remarks2']</value>
      <webElementGuid>1f988e43-7ae4-4622-8ef2-950f8dec26d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='documentDataTable1']/tbody/tr[4]/td[5]/span/textarea</value>
      <webElementGuid>779a20d4-bbc2-4446-b9a8-3df458bb0ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[5]/span/textarea</value>
      <webElementGuid>58569363-95c9-471b-b5de-d9503a9c32b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'remarks' and @id = 'remarks2']</value>
      <webElementGuid>7aa7678f-b09f-4729-92bd-2b6c011991ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
