<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Adjusted Amount_chbx_knockOffPayableToBeAdjusted(2)</name>
   <tag></tag>
   <elementGuidId>8194e111-30f9-4033-971e-147950fb99da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='chbx_knockOffPayableToBeAdjusted'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6da37cec-81f1-42ca-9ce3-896699b53291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>568b04fe-2b0c-4171-a43e-b0e4f17801f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chbx_knockOffPayableToBeAdjusted</value>
      <webElementGuid>0ee464b1-615a-4586-a5d8-8a2cd192f8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:reflectKnockOffChecked();</value>
      <webElementGuid>1c3f6410-0fe2-4c6f-b346-79a5b7871e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;menuHavingBody&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/form[1]/table[1]/tbody[1]/tr[1]/td[1]/fieldset[1]/table[@class=&quot;main_body&quot;]/tbody[1]/tr[3]/td[6]/input[1]</value>
      <webElementGuid>8e423193-f5ae-4c47-95e8-e41be02c3996</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='chbx_knockOffPayableToBeAdjusted'])[2]</value>
      <webElementGuid>670684b5-2a9c-42f1-a388-6a0adc46dafc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]/input</value>
      <webElementGuid>5e8d80f6-d84d-411c-8f27-1f0fd85aae57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'chbx_knockOffPayableToBeAdjusted']</value>
      <webElementGuid>80e02259-955b-479d-85db-224cbf794702</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
