<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Adjusted Amount_txtf_knockOffPayableAdjustedAmount</name>
   <tag></tag>
   <elementGuidId>4de6bf8d-be73-4e40-97b9-1d3768b630ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;txtf_knockOffPayableAdjustedAmount&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='txtf_knockOffPayableAdjustedAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9665ae10-e72f-403a-bd70-d1e990d845c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>38149219-92bb-4f50-97b1-bb8a64f045a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtf_knockOffPayableAdjustedAmount</value>
      <webElementGuid>f0265c19-19a5-436c-9c1f-47b89f0bd8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>82e672bb-831e-4803-9f2c-5915cc1c61da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>changeNumberCommaSeparated(this);javascript:paybleAmountOnBlur()</value>
      <webElementGuid>aa916068-8aa6-4be5-a390-4c056e5dbb28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c7176685-e5b5-4262-8ed9-32e90fffe3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;menuHavingBody&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/form[1]/table[1]/tbody[1]/tr[1]/td[1]/fieldset[1]/table[@class=&quot;main_body&quot;]/tbody[1]/tr[2]/td[7]/input[1]</value>
      <webElementGuid>0e032c9f-cc84-4f61-bde0-af567d816621</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='txtf_knockOffPayableAdjustedAmount']</value>
      <webElementGuid>2245e42b-8c56-41c0-815d-c2fbe65341cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/input</value>
      <webElementGuid>784ed210-15ac-48c5-8f43-058b21cc042c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txtf_knockOffPayableAdjustedAmount' and @title = '0']</value>
      <webElementGuid>8d72d303-c275-40cc-8d75-576c5c63f755</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
