<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Manual Adjustment_chbx_knockOffManualAllocation</name>
   <tag></tag>
   <elementGuidId>cf41de95-f658-441b-ac8d-4987544bb8c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;chbx_knockOffManualAllocation&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='chbx_knockOffManualAllocation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c757f209-8e16-44c4-85c6-4ecaff900ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fbdd03d8-f960-4043-8ae2-ba28f6b2f876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chbx_knockOffManualAllocation</value>
      <webElementGuid>a7be890b-3236-402c-b906-58fb7db77756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu_text</value>
      <webElementGuid>fcf7d68f-486d-4348-84e4-2992a1f3d230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:reflectKnockOffManualChecked(this)</value>
      <webElementGuid>bd53f212-73b8-4780-be52-5367a53854be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;menuHavingBody&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/form[1]/table[@class=&quot;main_body&quot;]/tbody[1]/tr[1]/td[1]/input[@class=&quot;menu_text&quot;]</value>
      <webElementGuid>986685e3-9a0d-49c0-9c8b-0521c70eff4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='chbx_knockOffManualAllocation']</value>
      <webElementGuid>44279655-1e7a-4163-b032-279c73d68bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td/input</value>
      <webElementGuid>8dea9224-fa8e-441b-be92-aac516985dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'chbx_knockOffManualAllocation']</value>
      <webElementGuid>adea3363-768a-42f0-bf85-665904effd37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
