<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OperationsUser_SCHEDULE_PAYMENT2</name>
   <tag></tag>
   <elementGuidId>32994f70-1bbb-443a-9f41-d68d969b9b8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SCHEDULE_PAYMENT2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SCHEDULE_PAYMENT2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a908ec2-37ee-4520-a5e3-daf77196aa68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d42fb329-43b5-4a44-a818-e7eeaa133c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SCHEDULE_PAYMENT2</value>
      <webElementGuid>77c8caae-9eb4-444c-8b32-a5db696778dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>itr_dealerObj.SCHEDULE_PAYMENT</value>
      <webElementGuid>87633108-2561-4021-b14a-cd4bfe8937a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>(offlineDtlObj.CAPITALISATION_FLG=='N')?true:false</value>
      <webElementGuid>8da88234-e0d5-460a-8e98-2747542b77c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>changePaymentStatus(itr_dealerObj,'sp')</value>
      <webElementGuid>bd90d820-385e-45dd-8a0c-1000ed5db630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>2279657e-8f80-4883-9bb7-4a8274d12158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SCHEDULE_PAYMENT2&quot;)</value>
      <webElementGuid>d83d3aba-9bcb-477c-a916-6cfad2b78e86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SCHEDULE_PAYMENT2']</value>
      <webElementGuid>45c28274-53a2-460c-b7d2-f611c8807638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/fieldset[2]/div[2]/div[7]/table/tbody/tr[4]/td[4]/input</value>
      <webElementGuid>6b4e28ee-bc7c-4c49-8ce8-d5a4e92c1640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/input</value>
      <webElementGuid>e671ea3c-cc1b-4258-bcfb-f386b098056e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'SCHEDULE_PAYMENT2']</value>
      <webElementGuid>ba346832-1b65-49c7-9d88-940a0e53b233</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
