<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECTTHE CAR CONNEXION LTD</name>
   <tag></tag>
   <elementGuidId>2cdf36e6-8e94-4d32-bcd3-21d64279c2e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ENTITY_NAME']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ENTITY_NAME</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1979c9a1-2799-4db6-835c-c11b60c6895c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ENTITY_NAME</value>
      <webElementGuid>2a9a4e23-52dd-42e6-81b7-26be6290e147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>offlineDtlObj.ENTITY_NAME</value>
      <webElementGuid>6e677457-d762-4ed0-afd4-e386d6820456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>setInsturmentType(offlineDtlObj)</value>
      <webElementGuid>ce5f58f0-aa6b-4967-9e06-a5a1db125840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>(user_Type=='MKT'?false:true) || (offlineDtlObj.CAPITALISATION_FLG=='Y'?false:offlineDtlObj.CHK_DRY_CAPITALISE_ACQ==true?true:false )</value>
      <webElementGuid>ba7951e7-0b2b-4cbf-90e8-d67ec37dbc0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>THE CAR CONNEXION LTD</value>
      <webElementGuid>e371b0a5-0195-44a2-9ae2-3c93a6427a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-valid ng-dirty ng-valid-parse ng-touched</value>
      <webElementGuid>aa7de5aa-21e8-4fe6-977f-e21ef13842ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  
					SELECT
					THE CAR CONNEXION LTD
					</value>
      <webElementGuid>8452e19c-a538-4c0b-993e-4cf5def3d51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ENTITY_NAME&quot;)</value>
      <webElementGuid>17d50db4-2b76-4eb4-a108-9ae899809777</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ENTITY_NAME']</value>
      <webElementGuid>484b1cf9-1afa-45fd-aab6-9f282c954bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/fieldset[2]/div[2]/div[2]/select</value>
      <webElementGuid>c8596f79-6c1a-4ad5-944c-7a09f9cefb99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dealer Name'])[1]/following::select[1]</value>
      <webElementGuid>6ef7bee4-f989-416d-9e0a-445a4cb5d794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R'])[1]/following::select[1]</value>
      <webElementGuid>8625e56b-c242-4cd5-92cd-68c5f7b3312f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instrument Type'])[1]/preceding::select[1]</value>
      <webElementGuid>50e8ef2e-0595-4745-a3c6-1fbb55940f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SCHEDULE PAYMENTS'])[1]/preceding::select[2]</value>
      <webElementGuid>f4763f8d-ad0c-4acb-bf18-ca3d0aca2e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>8c021cec-140a-43db-b5ff-bc589ac92682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ENTITY_NAME' and @title = 'THE CAR CONNEXION LTD' and (text() = '  
					SELECT
					THE CAR CONNEXION LTD
					' or . = '  
					SELECT
					THE CAR CONNEXION LTD
					')]</value>
      <webElementGuid>a6b00660-24ce-4c8c-901a-cc7611506625</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
