<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MOBILE NO_selectApplicant</name>
   <tag></tag>
   <elementGuidId>56e55ba1-c45d-4ec4-8efc-29c6d01425ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;selectApplicant&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[2]/td/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aceab2a4-e692-4fb0-afb4-8be375667f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b5fc6478-3fb2-4bcc-a9cd-e25a6c569de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectApplicant</value>
      <webElementGuid>bae675db-a6e2-4112-a1cc-dc7d3030ddc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1000036924</value>
      <webElementGuid>a23722ea-23a0-4279-aeb0-baffd83a46c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allProspectEntries&quot;)/table[@class=&quot;cmnTable&quot;]/tbody[1]/tr[@class=&quot;tr_list&quot;]/td[1]/input[1]</value>
      <webElementGuid>95a7e321-5015-46c1-a6d3-dc7ce04e8ce9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='selectApplicant']</value>
      <webElementGuid>c0c76510-0f90-4754-a24c-18176ccc98a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allProspectEntries']/table/tbody/tr[2]/td/input</value>
      <webElementGuid>b0d08bbb-0a16-42dc-8c76-863834b00eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>a7f83965-9aac-4bb3-945e-2b6f5610afc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'selectApplicant']</value>
      <webElementGuid>03f93253-91ca-4443-b22f-f79166492354</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
