<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CASHFLOW (2)</name>
   <tag></tag>
   <elementGuidId>51e74f48-aee4-4975-92b3-2a3b986562b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div/div[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ef498338-1b01-416e-b3fd-4219d19663be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>quotationCashflowDetail.sprg?&amp;screenId=1200004022&amp;mode=E&amp;screenName=CASHFLOW</value>
      <webElementGuid>f15e9371-73fa-47da-bd8b-e93281d8d66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noLine</value>
      <webElementGuid>0df69d9e-49d7-4afd-973c-b3f1bee78811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CASHFLOW</value>
      <webElementGuid>d43ea002-ea99-40d4-8b32-90f362fd7c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;menu col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[6]/a[@class=&quot;noLine&quot;]</value>
      <webElementGuid>5657c32c-8861-44c5-a057-c4a4c9753efc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div/div[6]/a</value>
      <webElementGuid>b0cc7e30-4af1-4793-90b7-5f5f1e0bb4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'CASHFLOW')])[3]</value>
      <webElementGuid>765d92b1-2f8a-488a-990e-f2c756b7ca3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INSURANCE'])[2]/following::a[1]</value>
      <webElementGuid>a4279e8a-63a2-4f7d-8d52-815dab8b889b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUOTATION'])[5]/following::a[2]</value>
      <webElementGuid>418930a3-53fc-4029-9a33-2756bb295a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGISTRATION DETAILS'])[2]/preceding::a[1]</value>
      <webElementGuid>d69937d0-65ef-4cbd-a720-c92957e80d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEVIATION'])[1]/preceding::a[2]</value>
      <webElementGuid>37d8ff09-23fe-4bf5-9daf-57e648a88b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'quotationCashflowDetail.sprg?&amp;screenId=1200004022&amp;mode=E&amp;screenName=CASHFLOW')]</value>
      <webElementGuid>9dfa8e27-21a9-4be7-90e1-ec4b5c0edc1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>37f67d99-5d13-4a7e-b50b-43dd640d5d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'quotationCashflowDetail.sprg?&amp;screenId=1200004022&amp;mode=E&amp;screenName=CASHFLOW' and (text() = 'CASHFLOW' or . = 'CASHFLOW')]</value>
      <webElementGuid>ac425491-2f2e-4a0e-bdc5-ec3536772adc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
