<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DMFIN1000008405</name>
   <tag></tag>
   <elementGuidId>f1059772-fc6c-44e1-8a52-ae50ee6ef340</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='existingTable']/tbody/tr/td[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7a5b83a-3ba8-4625-aff3-831841334709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6a1f1c1a-09b5-4ab4-b837-dc2f9e879ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>showDetail(quotation.DM_ID,quotation.DM_CODE,quotation.ASSET_FROM,quotation.LIMIT_EDIT_FLAG)</value>
      <webElementGuid>6aaa43d5-fb3f-449c-81aa-e78316069233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>b316d41c-320f-4923-8349-c76d960fa309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9a3a80f4-6461-42d9-b579-c9b568fb839d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DMFIN1000008405 </value>
      <webElementGuid>9c648e06-9c5b-407c-b03c-7bbd72831cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;existingTable&quot;)/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[5]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>98dec165-ec6a-4d54-8dcc-f660909fd94d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='existingTable']/tbody/tr/td[5]/a</value>
      <webElementGuid>f2128caf-fd85-4d4c-a101-89dff9179d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DMFIN1000008405')]</value>
      <webElementGuid>4fea35af-bfdb-44da-a4c9-ff57a2c93635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QU00023084'])[1]/following::a[1]</value>
      <webElementGuid>4d6e6069-19e2-497b-ad06-fdb02f5269a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN00023083'])[1]/following::a[1]</value>
      <webElementGuid>32624a5a-52ad-4577-9c3d-1fa5ada4c02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAYSON RUNGASAMY'])[1]/preceding::a[1]</value>
      <webElementGuid>6c69ed89-36fa-4ac6-975c-de78a9ddd671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNCIMF000003641'])[1]/preceding::a[1]</value>
      <webElementGuid>f21113d2-c2e4-4ebe-bb28-617787c22484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DMFIN1000008405']/parent::*</value>
      <webElementGuid>621d5c88-12ea-45c3-9236-631f8366248c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>39e0720f-09ba-435d-8d55-5d1ced2332e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>805a9e61-4d84-450a-8961-afbfca0cc01c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'DMFIN1000008405 ' or . = 'DMFIN1000008405 ')]</value>
      <webElementGuid>c70cd527-0b5f-42b0-be1f-b9fd596b395d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
