<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_QUOTATION</name>
   <tag></tag>
   <elementGuidId>e655f222-f62b-4f9c-8b98-9cc0780d3d2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2895de15-d2a6-4e95-acc4-4503eba814d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>quotationDetails.sprg?&amp;screenId=1200004020&amp;mode=E&amp;screenName=QUOTATION</value>
      <webElementGuid>7bd85d59-d045-44d3-87ef-ddaedf5ed70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noLine</value>
      <webElementGuid>28809643-373f-4cff-8643-c1e1661c3c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QUOTATION</value>
      <webElementGuid>e4c93bff-4252-4d28-937a-c4e5e0faadf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;menu col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[4]/a[@class=&quot;noLine&quot;]</value>
      <webElementGuid>d381d84c-a90f-4cfd-b0c9-6f6b22005ff8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div/div[4]/a</value>
      <webElementGuid>6f76855f-d63c-4caf-aa4a-4d565fb3794a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'QUOTATION')]</value>
      <webElementGuid>49d13cf8-d997-4fb7-83da-8ef32680a65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASSET DETAILS'])[1]/following::a[1]</value>
      <webElementGuid>2f413dde-0385-4f05-8980-881112e1ad39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEDUPE'])[1]/following::a[2]</value>
      <webElementGuid>38df56d8-0dc5-4cad-9b5a-c9b27bc23a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INSURANCE'])[1]/preceding::a[1]</value>
      <webElementGuid>2100f569-d5f5-402e-b106-33d287f3b36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASHFLOW'])[1]/preceding::a[2]</value>
      <webElementGuid>e91ac8f9-aaa9-42b6-be18-a3a2beab3d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='QUOTATION']/parent::*</value>
      <webElementGuid>5a0504ac-a683-474b-a5f4-33a13152de10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'quotationDetails.sprg?&amp;screenId=1200004020&amp;mode=E&amp;screenName=QUOTATION')]</value>
      <webElementGuid>26a25a3f-946f-4483-a3e9-67b8c4e5005a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>29cf6827-a631-44bc-aaf6-86c5a88e0210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'quotationDetails.sprg?&amp;screenId=1200004020&amp;mode=E&amp;screenName=QUOTATION' and (text() = 'QUOTATION' or . = 'QUOTATION')]</value>
      <webElementGuid>7121596b-82c6-42fd-855c-e3825c7d3aef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
