<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_QUOTATION_tab</name>
   <tag></tag>
   <elementGuidId>47146d44-2531-4ee8-8230-ac6bc7ef51e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dca5a57d-73d0-41c4-88db-3c34146a7a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>quotationDetails.sprg?&amp;screenId=1200004020&amp;mode=E&amp;screenName=QUOTATION</value>
      <webElementGuid>ecf1efef-642c-46e7-b66c-b41e167de6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noLine</value>
      <webElementGuid>0e21fd0b-22fe-445b-a8ff-6c4a97152392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QUOTATION</value>
      <webElementGuid>70c202c2-4a19-4e83-ae17-67c9769f6f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;menu col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[4]/a[@class=&quot;noLine&quot;]</value>
      <webElementGuid>aabdada7-7e36-4349-b1b6-5113939720ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div/div[4]/a</value>
      <webElementGuid>3e88b18d-1872-460a-985e-aa99f27e6c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'QUOTATION')])[6]</value>
      <webElementGuid>47438fee-7f64-4e06-b73c-0ea366d04035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASSET DETAILS'])[4]/following::a[1]</value>
      <webElementGuid>eedbe1cc-dd0f-4734-819a-ecd086dfd135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEDUPE'])[2]/following::a[2]</value>
      <webElementGuid>677bf31a-3386-4b74-b0e8-d0e67a9ab04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INSURANCE'])[2]/preceding::a[1]</value>
      <webElementGuid>1fa657be-75fa-44e1-942c-3fcdc8c42fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASHFLOW'])[3]/preceding::a[2]</value>
      <webElementGuid>ddb1aecb-8bed-48ff-aa40-a00ae7b81222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'quotationDetails.sprg?&amp;screenId=1200004020&amp;mode=E&amp;screenName=QUOTATION')]</value>
      <webElementGuid>05774832-d312-4220-969b-bbf903037046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>9b9f99b6-c111-4224-85ee-70665e9ade3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'quotationDetails.sprg?&amp;screenId=1200004020&amp;mode=E&amp;screenName=QUOTATION' and (text() = 'QUOTATION' or . = 'QUOTATION')]</value>
      <webElementGuid>4c21fab3-f344-4b74-bfe8-1c494904ec11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
