<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_QUOTATION (1)</name>
   <tag></tag>
   <elementGuidId>74c1b033-f0a0-4fd8-9e42-021f86145e2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>55d7dc8d-6bb9-4038-902d-7433b5aaeb78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>quotationDetails.sprg?&amp;screenId=1200004020&amp;mode=E&amp;screenName=QUOTATION</value>
      <webElementGuid>6a3d4954-d369-444b-88b8-946000300ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noLine</value>
      <webElementGuid>d64a1607-1433-41c7-aa4b-a37f4d07f327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QUOTATION</value>
      <webElementGuid>bf963702-5c85-4d05-b2a0-b811965bad40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;menu col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[4]/a[@class=&quot;noLine&quot;]</value>
      <webElementGuid>276c3832-9edd-4b73-86bb-7214b9cc803d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div/div[4]/a</value>
      <webElementGuid>6658701b-4b2c-44ca-92aa-93ea1931a5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'QUOTATION')]</value>
      <webElementGuid>c21f2d8b-df56-4564-99d0-e2dfb27310a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASSET DETAILS'])[1]/following::a[1]</value>
      <webElementGuid>ace9b786-6943-4578-b974-b16c81ae8b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEDUPE'])[1]/following::a[2]</value>
      <webElementGuid>b97d43d9-952c-45bc-920c-6da50359c562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INSURANCE'])[1]/preceding::a[1]</value>
      <webElementGuid>65c689aa-065f-46c7-8104-69f84158f517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASHFLOW'])[1]/preceding::a[2]</value>
      <webElementGuid>9223e803-5d16-40be-b99e-104b2c5d369e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='QUOTATION']/parent::*</value>
      <webElementGuid>f094353c-f9c8-44d5-b267-a9ba16f6cdc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'quotationDetails.sprg?&amp;screenId=1200004020&amp;mode=E&amp;screenName=QUOTATION')]</value>
      <webElementGuid>dcce98c6-c310-4775-a023-548f4c728831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>c450ad6f-ff9b-45a3-ba10-4e6d9d4ae5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'quotationDetails.sprg?&amp;screenId=1200004020&amp;mode=E&amp;screenName=QUOTATION' and (text() = 'QUOTATION' or . = 'QUOTATION')]</value>
      <webElementGuid>33ffb889-79e0-4678-8e9e-bb772265e6db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
