<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dealer Code_CHARGE_AMOUNT3</name>
   <tag></tag>
   <elementGuidId>2b3e7393-2b3b-4168-acd6-93f96a2fcac3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CHARGE_AMOUNT3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CHARGE_AMOUNT3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>288166dc-c79e-41b1-a10a-18b0ef471c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2edaeac3-a61c-427c-bc9f-3cb33bda1dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qt_txt_Align ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>0da24123-132c-437b-9ea6-2fbb5a2d0ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CHARGE_AMOUNT3</value>
      <webElementGuid>bbdbb429-508a-4c7c-b724-09ca8b2fd624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return event.charCode >= 48 &amp;&amp; event.charCode &lt;= 57 || event.charCode == 46</value>
      <webElementGuid>dfc7db5d-fa85-403d-9f48-7da1b99d53e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>format</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>3a5dc854-41fc-4eeb-b21e-09381a2615cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inflow.CHARGE_AMOUNT</value>
      <webElementGuid>91614494-7dde-45cc-ac97-3cc125bd77a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>inflow.CHARGE_ID == '1200000001' || inflow.CHARGE_ID == '1200000046'?true:false</value>
      <webElementGuid>315c7f12-608e-4b03-a76a-d158b56101ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keyup</name>
      <type>Main</type>
      <value>checkLength('cashFlowInFlowDtl','CHARGE_AMOUNT',$index);calculateVat('cashFlowInFlowDtl',$index)</value>
      <webElementGuid>2f793d57-2516-4120-adf4-696287a0098a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CHARGE_AMOUNT3&quot;)</value>
      <webElementGuid>46d6918e-8536-4621-934d-c83228eb43ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CHARGE_AMOUNT3']</value>
      <webElementGuid>7678a4c7-e9cc-4bba-85fb-16abd1019888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='existingTable']/tbody/tr[5]/td[4]/input</value>
      <webElementGuid>6188ff9f-6a2c-4c28-8d95-7b81d4ddaa5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[4]/input</value>
      <webElementGuid>2a66f039-73d4-4de1-88de-c352d78a8fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CHARGE_AMOUNT3']</value>
      <webElementGuid>6613b6b0-2eef-4d1c-871b-e5881090358d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
