<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dealer Code_CHARGE_AMOUNT2</name>
   <tag></tag>
   <elementGuidId>a7ff3beb-9885-4339-8ada-2d907d08a230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CHARGE_AMOUNT2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CHARGE_AMOUNT2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1c1e285-8e7e-4314-afcb-3263c9cb8e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc543283-c5aa-4bd7-8552-9f294a533ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qt_txt_Align ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>593ece61-4213-4680-8c8d-ea44eaac6eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CHARGE_AMOUNT2</value>
      <webElementGuid>087e742f-06f3-4408-9b79-d15b1190be62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return event.charCode >= 48 &amp;&amp; event.charCode &lt;= 57 || event.charCode == 46</value>
      <webElementGuid>4afc4ec4-be46-4d0a-bf49-9e655e3fb974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>format</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>96bb450f-18dd-418d-b644-11175b9aff5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inflow.CHARGE_AMOUNT</value>
      <webElementGuid>1be4b978-288c-47c0-8d6e-9f59e7c33bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>inflow.CHARGE_ID == '1200000001' || inflow.CHARGE_ID == '1200000046'?true:false</value>
      <webElementGuid>8d75bb1c-bd50-4dde-8229-220620b8cdba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keyup</name>
      <type>Main</type>
      <value>checkLength('cashFlowInFlowDtl','CHARGE_AMOUNT',$index);calculateVat('cashFlowInFlowDtl',$index)</value>
      <webElementGuid>f054bcee-3a81-4813-b2fb-2d137c4b38e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CHARGE_AMOUNT2&quot;)</value>
      <webElementGuid>7c712046-1c13-4774-870e-c2adbb074753</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CHARGE_AMOUNT2']</value>
      <webElementGuid>45f99756-524e-4938-a4bc-f4069fca7e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='existingTable']/tbody/tr[4]/td[4]/input</value>
      <webElementGuid>1ad6608a-d7b2-4297-892a-a9a7c37c2e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/input</value>
      <webElementGuid>2b95ab87-1c34-45bc-99ec-677c03f229d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CHARGE_AMOUNT2']</value>
      <webElementGuid>f448f903-2540-4050-bf9a-b34b508f19c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
