<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ADDITIONAL CHARGE DETAILS_btn btn-primary btn-sm</name>
   <tag></tag>
   <elementGuidId>e1825170-549f-4da1-a7e5-1de8586d93f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chargeDetailsDiv > div.col-lg-12.col-md-12.col-sm-12.col-xs-12 > div.legend.legendFloat.col-lg-12.col-md-12.col-sm-12.col-xs-12 > div.col-lg-8.col-md-8.col-sm-8.col-xs-8.main_body.text-right > input.btn.btn-primary.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='ADD'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80815aab-eca8-4e8c-9440-aac6f3d70c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>19562ba5-8f6c-48e1-aba3-fa928451dfc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ADD</value>
      <webElementGuid>647a2e57-a54b-4b1f-ac30-cc48fea0ac7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>addOutFLowChargeDetail()</value>
      <webElementGuid>70028aed-418c-4345-9cc9-8845a81d677d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm</value>
      <webElementGuid>78ec2b71-54c3-4a3a-a1ef-482f184bce4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chargeDetailsDiv&quot;)/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;legend legendFloat col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-lg-8 col-md-8 col-sm-8 col-xs-8  main_body text-right&quot;]/input[@class=&quot;btn btn-primary btn-sm&quot;]</value>
      <webElementGuid>e8479ac6-4d25-403c-8bec-746a5c0efd77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='ADD'])[2]</value>
      <webElementGuid>5fa51faf-815a-48fb-82a8-61debd0a0df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chargeDetailsDiv']/div[2]/div/div[2]/input</value>
      <webElementGuid>012650df-63d3-4475-89b8-7c3f9b85d678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/input</value>
      <webElementGuid>9f995d5c-42de-4869-bc0e-8e43b272821f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>cdffcebf-90ef-4ddf-b8ca-e3cb6db4d093</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
