<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dealer Code_CHARGE_AMOUNT4</name>
   <tag></tag>
   <elementGuidId>99e505d6-6c41-4830-83b5-a68ad376a48f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CHARGE_AMOUNT4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CHARGE_AMOUNT4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4913c6f2-3593-4ef4-9033-2e251a7bd997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0b9022a1-a7d9-4844-a87c-d2a569f76962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qt_txt_Align ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>d6c05ef9-a4aa-4850-a7f4-80ac46ec9464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CHARGE_AMOUNT4</value>
      <webElementGuid>77b58864-ceb6-49d0-a4c1-8c5823475997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return event.charCode >= 48 &amp;&amp; event.charCode &lt;= 57 || event.charCode == 46</value>
      <webElementGuid>e5474252-7441-49f2-89df-36faf509c26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>format</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>26bcea99-13dc-40a5-b350-f0df211cdff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inflow.CHARGE_AMOUNT</value>
      <webElementGuid>9bbd3a4c-0e3c-4dcc-a808-96d566d592e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>inflow.CHARGE_ID == '1200000001' || inflow.CHARGE_ID == '1200000046'?true:false</value>
      <webElementGuid>b1426285-9bce-47f3-b858-a05e241f8926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keyup</name>
      <type>Main</type>
      <value>checkLength('cashFlowInFlowDtl','CHARGE_AMOUNT',$index);calculateVat('cashFlowInFlowDtl',$index)</value>
      <webElementGuid>97bf51c2-0fba-4e4d-826b-66f110f8951c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CHARGE_AMOUNT4&quot;)</value>
      <webElementGuid>42146128-5105-47a5-9db9-8c1f881ee115</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CHARGE_AMOUNT4']</value>
      <webElementGuid>edfc7692-747c-4201-886a-8d99d8137e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='existingTable']/tbody/tr[6]/td[4]/input</value>
      <webElementGuid>686c2eec-b1f4-4407-aca8-a174a6ae6ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[4]/input</value>
      <webElementGuid>1e14fe23-7332-4395-a3eb-bd0cbf213724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CHARGE_AMOUNT4']</value>
      <webElementGuid>37049829-2cf2-4f39-b280-679e3a744279</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
