<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECT17142128 (1)</name>
   <tag></tag>
   <elementGuidId>573b5bb6-1686-41be-abb9-86187209cac3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#INSTALMENT_DAY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='INSTALMENT_DAY']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0cad8ffe-ab62-45e8-b013-6be490587b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_header_cost ng-pristine ng-valid ng-touched</value>
      <webElementGuid>46e78270-dd8f-4139-a8aa-37e27656e61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>INSTALMENT_DAY</value>
      <webElementGuid>114c7546-31c5-4bf1-92c4-ad8b62f4cc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>INSTALMENT_DAY</value>
      <webElementGuid>a61fb8f3-9c36-4cca-9161-0ac2e88b24c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>getRsd()</value>
      <webElementGuid>5486f564-e2e0-4b66-a47d-04f80005a874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						SELECT
					17142128
					</value>
      <webElementGuid>458a0608-9eee-4e12-ab01-3ece9eda99c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;INSTALMENT_DAY&quot;)</value>
      <webElementGuid>b1499f9d-14f4-45dd-8746-09ae19f4393c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='INSTALMENT_DAY']</value>
      <webElementGuid>f6488b68-4713-44ba-93f7-59c531b31e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='quotationBodyId']/div[7]/div/form/fieldset[2]/div/div[29]/select</value>
      <webElementGuid>ae8aa60d-aa46-4f9c-b805-34b677e323dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Day'])[1]/following::select[1]</value>
      <webElementGuid>aa66a950-d2c9-4faf-846f-c9557c0d3c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RSD (Rent Start Date)'])[1]/preceding::select[1]</value>
      <webElementGuid>b83ed70b-58e8-4f9e-a12a-7fc3d95af3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Type'])[1]/preceding::select[1]</value>
      <webElementGuid>a5efdbdd-deaf-4a16-8ece-91a28e26354c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[29]/select</value>
      <webElementGuid>c1ec8cc4-6e53-4591-a308-8386a63dd18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'INSTALMENT_DAY' and (text() = '
						SELECT
					17142128
					' or . = '
						SELECT
					17142128
					')]</value>
      <webElementGuid>48fa0432-a830-4782-824e-6b19d44ef8a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
