<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECT17142128</name>
   <tag></tag>
   <elementGuidId>ede7cbea-4e99-481f-a10d-9c13986a10b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='INSTALMENT_DAY']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#INSTALMENT_DAY</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1dda3e59-13ad-48a0-a97a-c36aff50ea8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_header_cost ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>1b8066b0-159b-415d-b461-f6fb46aa9b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>INSTALMENT_DAY</value>
      <webElementGuid>f286c2ae-7352-4899-b95e-508edd302aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>INSTALMENT_DAY</value>
      <webElementGuid>92096234-982d-4df2-afd5-b4e7e5c9c261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>getRsd()</value>
      <webElementGuid>c0e08f57-9855-479d-b601-265790cebafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						SELECT
					17142128
					</value>
      <webElementGuid>50ded1f9-6e7e-4855-91aa-9c218a32512d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;INSTALMENT_DAY&quot;)</value>
      <webElementGuid>9dde524b-076b-4c55-926e-a86a293565f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='INSTALMENT_DAY']</value>
      <webElementGuid>ac1f88c5-ff68-4ea0-90d0-3b25b0ac7de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='quotationBodyId']/div[7]/div/form/fieldset[2]/div/div[29]/select</value>
      <webElementGuid>30711544-4c24-4771-bb4f-1057c32914c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Day'])[1]/following::select[1]</value>
      <webElementGuid>8941f03e-c8ec-4c48-9117-c04b22de36c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RSD (Rent Start Date)'])[1]/preceding::select[1]</value>
      <webElementGuid>dec0be52-7c1b-49b9-90c7-36346aee06c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Type'])[1]/preceding::select[1]</value>
      <webElementGuid>e7057161-afd4-4e52-9ebb-d149419aeeba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[29]/select</value>
      <webElementGuid>71cd74b5-9eaf-4f54-98d1-f4440d867de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'INSTALMENT_DAY' and (text() = '
						SELECT
					17142128
					' or . = '
						SELECT
					17142128
					')]</value>
      <webElementGuid>6b3e98f7-5849-4bd2-a860-34cd1a288f95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
