<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECTYESNO</name>
   <tag></tag>
   <elementGuidId>f33e9c56-be62-46ff-9f49-db55d7f8924e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IMPACT_ON_FINANCE_AMT2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IMPACT_ON_FINANCE_AMT2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>486a511f-f00a-4fbc-89b5-15423738769b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IMPACT_ON_FINANCE_AMT2</value>
      <webElementGuid>f0847d93-7370-47d6-b8cb-cdd7fdb73015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inflow.IMPACT_ON_FINANCE_AMT</value>
      <webElementGuid>7633f0fd-208a-445a-b26d-885d9cd06ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>inflow.CHARGE_ID == '1200000001' || inflow.CHARGE_ID == '1200000046' ?true:false</value>
      <webElementGuid>3cff0050-5690-4814-9611-674d2fbf216e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>43ec7caf-79f5-40da-b9e2-193abcd4f199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						SELECT
						YES
						NO
					</value>
      <webElementGuid>6338eec5-bb63-41b7-9da8-5138a1fe7c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IMPACT_ON_FINANCE_AMT2&quot;)</value>
      <webElementGuid>7db78a18-d6a1-47ff-840f-2619630efdf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IMPACT_ON_FINANCE_AMT2']</value>
      <webElementGuid>3fb07cc3-2570-44a5-a32c-8016f10d050c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='existingTable']/tbody/tr[4]/td[7]/select</value>
      <webElementGuid>9833d13a-aedc-4615-91c8-034775a20cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dealer Code'])[2]/following::select[9]</value>
      <webElementGuid>b09692df-c398-4c2e-9f2a-7b783c5b266f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dealer Name'])[2]/following::select[9]</value>
      <webElementGuid>fd14d333-ac20-4143-9a0f-50e534ed9aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COST (Amount In Rs.)'])[1]/preceding::select[7]</value>
      <webElementGuid>55aed559-0cd0-405a-a543-c95712f10a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finance Amount'])[1]/preceding::select[7]</value>
      <webElementGuid>3309353a-e163-44b9-bfa4-3c18478ff482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[7]/select</value>
      <webElementGuid>93738829-d951-4587-8fee-63115c60539b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IMPACT_ON_FINANCE_AMT2' and (text() = '
						SELECT
						YES
						NO
					' or . = '
						SELECT
						YES
						NO
					')]</value>
      <webElementGuid>ae091822-bd26-494f-90db-f3eb40347f70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
