<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECTRENTALISEOPE TO LESSEBY LESSE</name>
   <tag></tag>
   <elementGuidId>b2b10dc2-9934-4db4-a2f4-82f34717502c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#STRUCTURE_ACTIONABLE_ID2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='STRUCTURE_ACTIONABLE_ID2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>55711eba-f29e-4822-a56c-d71f136ea0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>STRUCTURE_ACTIONABLE_ID2</value>
      <webElementGuid>3233255f-34cd-4906-b0da-d739ef057b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inflow.STRUCTURE_ACTIONABLE_ID</value>
      <webElementGuid>cb470e41-c32b-4d74-ae26-0006de59fed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>(inflow.CHARGE_ID == '1200000001' || inflow.CHARGE_ID == '1200000046'?true:false) || (inflow.CHARGE_ID == '1200000039' &amp;&amp; inflow.STRUCTURE_ACTIONABLE_ID == '1000000004'?true:false) || (inflow.CHARGE_ID == '1200000041' &amp;&amp; inflow.STRUCTURE_ACTIONABLE_ID == '1000000002'?true:false) || (inflow.CHARGE_ID == '1200003055' &amp;&amp; inflow.STRUCTURE_ACTIONABLE_ID == '1000000002'?true:false)</value>
      <webElementGuid>87513f80-09e4-42ca-b229-3a576f7bb9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>setImpactonFA();</value>
      <webElementGuid>558e656b-11af-49f5-afc9-0a33468e0adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>27a51328-b8b4-4735-a694-30d8248dca10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						SELECTRENTALISEOPE TO LESSEBY LESSE
					  </value>
      <webElementGuid>6fdadbd0-3025-426c-88e3-d504a08056dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;STRUCTURE_ACTIONABLE_ID2&quot;)</value>
      <webElementGuid>b1e86d2a-67ec-49ce-957e-caa0d30cbb5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='STRUCTURE_ACTIONABLE_ID2']</value>
      <webElementGuid>df5d0405-b5df-46db-a016-58ae79457d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='existingTable']/tbody/tr[4]/td[3]/span/select</value>
      <webElementGuid>92348a0a-5c8d-4853-9573-1fe2584a40f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dealer Code'])[2]/following::select[8]</value>
      <webElementGuid>5579159f-3a20-44a0-b23d-254ecbb7f504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dealer Name'])[2]/following::select[8]</value>
      <webElementGuid>ada80e0f-b0ff-404a-9023-289d196fa1a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COST (Amount In Rs.)'])[1]/preceding::select[8]</value>
      <webElementGuid>25777d70-25b3-4e3e-bc16-4b4746b4e790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finance Amount'])[1]/preceding::select[8]</value>
      <webElementGuid>ccb6886b-071e-45f3-ad5c-b6061b2d1489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/span/select</value>
      <webElementGuid>1694a72d-7255-4556-84a8-044f64627ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'STRUCTURE_ACTIONABLE_ID2' and (text() = '
						SELECTRENTALISEOPE TO LESSEBY LESSE
					  ' or . = '
						SELECTRENTALISEOPE TO LESSEBY LESSE
					  ')]</value>
      <webElementGuid>f04e9abe-a6a4-43cb-a288-d754b28eefd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
