<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECTYESNO_1_2</name>
   <tag></tag>
   <elementGuidId>4685212c-79b5-4e34-b3b6-ab92651f386e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IMPACT_ON_FINANCE_AMT4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IMPACT_ON_FINANCE_AMT4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>22dff674-c7f8-4692-8c37-893ea3c93dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IMPACT_ON_FINANCE_AMT4</value>
      <webElementGuid>259f0edf-ed9e-4f10-97fa-0cccbfb91c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inflow.IMPACT_ON_FINANCE_AMT</value>
      <webElementGuid>976e4fd3-15bc-4caf-8910-87bc0b8ac5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>inflow.CHARGE_ID == '1200000001' || inflow.CHARGE_ID == '1200000046' ?true:false</value>
      <webElementGuid>e0d90b7c-f65c-4282-b9f0-649964e78ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>6468d8c3-f4c5-4013-9279-799d0bf93548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						SELECT
						YES
						NO
					</value>
      <webElementGuid>f436fde3-f883-4fbc-bad1-e0aa05e351ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IMPACT_ON_FINANCE_AMT4&quot;)</value>
      <webElementGuid>0e35c0f8-2d43-45d5-b38b-59bc4b88e59c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IMPACT_ON_FINANCE_AMT4']</value>
      <webElementGuid>02fd7dac-1c88-405f-9a22-cb21c1820b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='existingTable']/tbody/tr[6]/td[7]/select</value>
      <webElementGuid>d9563b31-6ad9-4928-a72b-9deb3c885117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dealer Code'])[2]/following::select[15]</value>
      <webElementGuid>24b2b1a9-5dc1-41ec-b5be-a744ad2a1691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dealer Name'])[2]/following::select[15]</value>
      <webElementGuid>386eb164-4abe-4091-945e-132df6388b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COST (Amount In Rs.)'])[1]/preceding::select[1]</value>
      <webElementGuid>8512e5ec-300a-4035-9630-6cc70c8a92cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finance Amount'])[1]/preceding::select[1]</value>
      <webElementGuid>14ed546d-c63b-4e8a-9e5d-0b970e2d6d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[7]/select</value>
      <webElementGuid>3c8a33c2-4e58-4c82-9957-8a6a0e7d4740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IMPACT_ON_FINANCE_AMT4' and (text() = '
						SELECT
						YES
						NO
					' or . = '
						SELECT
						YES
						NO
					')]</value>
      <webElementGuid>9f842249-050d-487f-9888-b24c52f1371f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
