<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MAKER</name>
   <tag></tag>
   <elementGuidId>b42b61aa-1616-49fe-94ef-4b74c94881e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#action1200106859 > div.fgfg.MenuLevel2Parent > div.modules_anchor1.MenuLevel2 > a.menu_L3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;callLink('1200106859');return blockClick()&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32ba4a9a-5d77-4714-a012-36729285dcb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu_L3</value>
      <webElementGuid>ebfc5c3b-1a21-430f-ac65-023515b492ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>prospectListFrmNavAction.do?actionPerformed=displayProspectListInfo&amp;screenId=1200106859&amp;screenName=MAKER</value>
      <webElementGuid>6f2d106e-bf9e-480e-88ac-b73339fd950a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>callLink('1200106859');return blockClick()</value>
      <webElementGuid>f31c9006-455a-4d22-a9fe-3a5d9fa20b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MAKER</value>
      <webElementGuid>65ae3f87-db5e-46df-9096-878a2b0817c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;action1200106859&quot;)/div[@class=&quot;fgfg MenuLevel2Parent&quot;]/div[@class=&quot;modules_anchor1 MenuLevel2&quot;]/a[@class=&quot;menu_L3&quot;]</value>
      <webElementGuid>937913e2-bb87-4f1b-89b7-fb5d3fff0b25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;callLink('1200106859');return blockClick()&quot;]</value>
      <webElementGuid>73b32094-01f1-4b06-b6eb-d5f875ddaa84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action1200106859']/div/div/a</value>
      <webElementGuid>e42e5b7e-b6bf-42af-8a99-3fe56740af19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'MAKER')])[4]</value>
      <webElementGuid>5a6325bd-ac46-4028-b32f-bea9d37bdf7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DM PDE'])[1]/following::a[1]</value>
      <webElementGuid>572e8634-17da-4473-a0d2-53b1ce4a42f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INVOICE'])[2]/following::a[2]</value>
      <webElementGuid>73ce9402-a1a1-4970-9900-7ecdef152af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RECEIPT'])[1]/preceding::a[1]</value>
      <webElementGuid>2401a3f1-3df6-45dd-a72b-c5e1dd487d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAKER'])[4]/preceding::a[2]</value>
      <webElementGuid>81321c38-8b74-48fb-ae5b-efbb76a9574c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'prospectListFrmNavAction.do?actionPerformed=displayProspectListInfo&amp;screenId=1200106859&amp;screenName=MAKER')]</value>
      <webElementGuid>7dfcf772-fa0a-43b9-ab8d-3cec7340a3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[79]/div/div/a</value>
      <webElementGuid>343400a1-361d-432e-a6df-35403c8f5d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'prospectListFrmNavAction.do?actionPerformed=displayProspectListInfo&amp;screenId=1200106859&amp;screenName=MAKER' and (text() = 'MAKER' or . = 'MAKER')]</value>
      <webElementGuid>a68a2562-7e60-4805-9e20-e38a39653ee2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
