<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Hi COPSUSERM_userr</name>
   <tag></tag>
   <elementGuidId>89937fd5-ef77-43ea-84cb-81b0b3f404a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.userr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='dashbord_main']/form/div/div/div[3]/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4e65727b-1ef3-4855-82cc-6954c2bb778c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>userr</value>
      <webElementGuid>4f35a626-8ca6-43d6-b023-6ac402bdf2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/picuser_head.png</value>
      <webElementGuid>2c52147a-ea4b-4b1a-bbb5-6e24915bb0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashbord_main&quot;)/form[1]/div[@class=&quot;backe_image col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[1]/div[@class=&quot;col-lg-4 col-md-4 col-sm-4 col-xs-4&quot;]/div[1]/span[@class=&quot;username_icon&quot;]/img[@class=&quot;userr&quot;]</value>
      <webElementGuid>2aaf5a7d-1b9b-45a3-8d23-bc0f28964897</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='dashbord_main']/form/div/div/div[3]/div/span/img</value>
      <webElementGuid>f0f71896-15f1-4056-8120-c1608db4e279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>6cf23d26-e091-4b75-b419-dd5fdd9d2292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/picuser_head.png']</value>
      <webElementGuid>48f0c7ea-4c1f-48eb-b59f-436124e51b17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
