<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_INVOICE_img1200106858</name>
   <tag></tag>
   <elementGuidId>cba6f6c5-3b99-401f-aa02-7f11db527593</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img1200106858</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='img1200106858']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4574f802-f140-474d-854d-3a2fad283c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img1200106858</value>
      <webElementGuid>4bf39e80-a86f-43e4-a110-3f1566b21a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>9909b3f4-7b4a-4e11-a8bb-03faae2acf42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>41a118a5-e5f2-4c0a-87fe-91b61957a750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img1200106858&quot;)</value>
      <webElementGuid>c27c72cb-7e9f-461f-8cb6-9a769940aff8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='img1200106858']</value>
      <webElementGuid>b938d0fd-d841-45d5-811d-34ad4f0f4fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='imgDiv']/i)[20]</value>
      <webElementGuid>d91f9a6b-88f1-4f83-ab53-e5117387fcd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[72]/div/div/i</value>
      <webElementGuid>0bd5fc50-5a3f-4373-9532-2d4496a55897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'img1200106858']</value>
      <webElementGuid>9180dbb3-6fea-4ca1-8a69-5e92e8d64e26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
