<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_LOGIN</name>
   <tag></tag>
   <elementGuidId>bb82a1cd-9d86-4636-9a00-5323906ddcc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7953c403-3dcb-49c6-a762-a4e9a6183d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd227941-e279-4952-b9d4-35f1ae62b70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>348f4eb2-62df-43b9-9bbc-6ef3346279ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>loginform()</value>
      <webElementGuid>f6eba6fe-53a5-422f-a33e-761c70f50dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>d9d22aa9-7f30-4a34-b093-62a8ab299da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginPage_id&quot;)/form[1]/div[@class=&quot;main_divlogin&quot;]/div[@class=&quot;row-centered&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12 col-centered&quot;]/div[@class=&quot;login_inputButtons&quot;]/div[1]/button[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>f5683c09-de39-4f9a-b6aa-69d8b0ae680c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>9eed5d00-3009-4fa3-8b94-155472b6e46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='loginPage_id']/form/div[2]/div/div/div[2]/div/button</value>
      <webElementGuid>cf844f07-c5db-4a0f-8e8b-9c22382d441f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='miFIN'])[2]/following::button[1]</value>
      <webElementGuid>c6c1ff97-c3ef-4c86-b8c1-b40be7ad415a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUALTECH CONSULTANTS PVT LTD'])[1]/preceding::button[1]</value>
      <webElementGuid>9940352e-1bb9-4921-b07e-3ecca5ce5c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VERSION 1.0.1.295'])[1]/preceding::button[1]</value>
      <webElementGuid>4a5e91b8-4f61-494a-bcbc-e6b71dfc3b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGIN']/parent::*</value>
      <webElementGuid>c2cd5314-ed4a-487b-aad7-00087003578f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>6f219a42-63e4-4002-aac3-a4b5f4e40e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'LOGIN' or . = 'LOGIN')]</value>
      <webElementGuid>f10bbde2-d965-44eb-af56-83f23d869404</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
