<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_National IDBRNPP No_pageneation</name>
   <tag></tag>
   <elementGuidId>55e1257b-22c6-47a9-a67d-69d3716e06cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pageneation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pageneation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5d80eab-b493-4271-a7b2-e761c33fd776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pageneation</value>
      <webElementGuid>5b416c4f-a1de-446a-8ce8-79dd20ff15f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageneation&quot;)</value>
      <webElementGuid>29402dea-f4e1-425a-aadb-6ebb511f54fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pageneation']</value>
      <webElementGuid>fecd6203-ddbc-464e-bc47-8c2b19ca1191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dasiTd']/div/div[17]</value>
      <webElementGuid>0f90a851-6b34-4b61-8664-2a7f094acb71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='National ID/BRN/PP No.'])[1]/following::div[4]</value>
      <webElementGuid>ca5a3b74-9546-40d4-bfce-a5136132969f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/following::div[6]</value>
      <webElementGuid>83502b74-02ee-4bb8-8c76-bcd5169bd252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qualtech Consultants Pvt. Ltd.'])[1]/preceding::div[1]</value>
      <webElementGuid>5885906f-744f-495b-ae6b-bc58b3b1055c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VERSION 1.0.1.176.2'])[1]/preceding::div[2]</value>
      <webElementGuid>217f8eaf-52a4-4241-8194-84219ee0c828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr/td/div/div[17]</value>
      <webElementGuid>7abcff2a-9003-4acc-8541-b9948eabd9b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pageneation']</value>
      <webElementGuid>97bfb893-44ab-4436-83f0-fe4d4847dcdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
