<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_LIMIT(LEASE)_img1200007001</name>
   <tag></tag>
   <elementGuidId>4bc8b398-5231-4da8-b706-60ffb917defc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='img1200007001']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img1200007001</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d2925fe9-cd5d-40bc-b97f-2f6df14223f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img1200007001</value>
      <webElementGuid>33bac81b-8267-42f7-b4c2-1d2dfa31b9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>0dfa6bf5-5fc3-4421-ba31-4f7e6d7d1335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>604759cc-f42e-42f3-a310-3540007e1cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img1200007001&quot;)</value>
      <webElementGuid>1c8feb7e-9fd8-46d9-87ee-54b31fa27461</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='img1200007001']</value>
      <webElementGuid>a336653a-9f95-4440-a302-7c54e3edb3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='imgDiv']/i)[6]</value>
      <webElementGuid>5b6fbba6-baea-4087-b6f1-ce43b3660546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/i</value>
      <webElementGuid>030aa8ce-d134-4889-8b2b-ab29736da13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'img1200007001']</value>
      <webElementGuid>943b690f-26ad-40bd-8053-63cffa1fd891</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
