<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_VIEWER_img1200004000 (1)</name>
   <tag></tag>
   <elementGuidId>8f254079-b320-4fd4-b3c5-dcd64ef79595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img1200004000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='img1200004000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7d4130db-787f-4872-9021-f636ddebeda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img1200004000</value>
      <webElementGuid>655019f1-7504-45d4-9455-7465f96e6a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>004f2474-75ee-4161-879f-8712b5e6dbc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fbc5dedf-2559-48c0-9215-f64added4485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img1200004000&quot;)</value>
      <webElementGuid>fc67709b-9fc0-4dd2-9ac2-9e6bd3ad7caa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='img1200004000']</value>
      <webElementGuid>caf0e39c-5d18-40fd-9aef-46b14bf9ef3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='imgDiv']/i)[14]</value>
      <webElementGuid>31af0e65-1337-4e33-8433-036b9c3a5176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[52]/div/div/i</value>
      <webElementGuid>128ab008-412a-4dee-8053-47ff9373b86c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'img1200004000']</value>
      <webElementGuid>c8f34b27-d629-47f5-923a-45b10f770f35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
