<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save  Continue</name>
   <tag></tag>
   <elementGuidId>50e5194f-1a1a-4187-93de-39734f1d388a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='dmNewApplicantId']/div[4]/div/div[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a0729e0-340e-47d5-bb92-6a6baf1389cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>15414ae4-30d5-451d-a23f-41888f597ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>save('C')</value>
      <webElementGuid>a343ef95-5ca1-451e-8377-b6b95617a875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>disabledAllFields</value>
      <webElementGuid>ee173406-8113-4e48-962a-df6b00049bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>e712aa65-cbf5-41cd-b8a8-14a8076894b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						Save &amp; Continue   </value>
      <webElementGuid>3ddc89d2-9fb7-4cea-8439-0e0d796508ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dmNewApplicantId&quot;)/div[@class=&quot;container-fluid subheaderSection&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-lg-8 col-md-8 col-sm-8 col-xs-6 text-right secndDivSubhdr&quot;]/a[2]</value>
      <webElementGuid>8fed8445-69c2-4a9e-963c-2a495dad7454</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='dmNewApplicantId']/div[4]/div/div[2]/a[2]</value>
      <webElementGuid>f3e19750-148e-4ce2-8abd-70c4f331600f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save &amp; Continue')]</value>
      <webElementGuid>5f169570-938d-4624-8565-ad8e92df18eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Dashboard'])[1]/following::a[1]</value>
      <webElementGuid>2a617d6f-5e9c-44d2-bb31-0e2cc3e9d12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW DM APPLICATION'])[1]/following::a[2]</value>
      <webElementGuid>b822d3d6-fce5-4dc4-9d7c-60130e8403ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRODUCT DETAILS'])[1]/preceding::a[3]</value>
      <webElementGuid>7ffb2637-0ce1-419a-8233-7d8e4311bb48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quotation Id'])[1]/preceding::a[3]</value>
      <webElementGuid>651b5560-2abe-4ebb-9ee8-2b2d55cf7b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save &amp; Continue']/parent::*</value>
      <webElementGuid>04d2dc6f-6ef8-420e-abde-ea1680e6d697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>8e831f97-a9e4-44db-861b-818df9654579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]</value>
      <webElementGuid>f24419f8-4990-4b68-ad4f-a2007050b7ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '
						Save &amp; Continue   ' or . = '
						Save &amp; Continue   ')]</value>
      <webElementGuid>728af8d7-7c68-4fd5-b5e8-d266a15b07ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
