<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer Id_isExisting (1)</name>
   <tag></tag>
   <elementGuidId>05009743-7801-4fc1-a57a-ac72c851c2ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='isExisting'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#existing > #isExisting</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>435b0d91-4318-426d-ab64-ff03547383e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a51d7882-9542-4f39-bf7a-3c031b96dbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isExisting</value>
      <webElementGuid>7fb7520c-d07f-421c-a074-7baf4f63889d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>c097f4b3-afe2-4898-bf7e-98ac457ec38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>toggleExistingDetails(true, this); checkforAppType(this);</value>
      <webElementGuid>a90d34ab-e4cc-4cf9-8f0b-a11e7515c96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isExisting</value>
      <webElementGuid>f463efa7-f38e-4bb3-a09c-9d0c15b9c899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;existing&quot;)/input[@id=&quot;isExisting&quot;]</value>
      <webElementGuid>5c8f165b-1969-4fe7-8b97-c45e7e692ecd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='isExisting'])[2]</value>
      <webElementGuid>8e8d68fb-30a6-4ae8-9827-973ef28cbe30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='existing']/input</value>
      <webElementGuid>1d7a7873-2fe2-4ab8-a4e2-645c6a76155b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span/input</value>
      <webElementGuid>825cb5d3-2e40-4365-834f-69a6c334f7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'isExisting' and @id = 'isExisting']</value>
      <webElementGuid>630a8a96-3c28-4bea-b5cf-a1c3babe66dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
