<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MOBILE NO_selectApplicant (1)</name>
   <tag></tag>
   <elementGuidId>b818b263-e256-447a-b623-2668a7d7a1ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/table/tbody/tr[2]/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;selectApplicant&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16c97e1b-d4ac-445f-bdac-b6a85228bd2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>aa0042fd-ad32-4463-ab31-71ea91ed64d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectApplicant</value>
      <webElementGuid>3969cf4b-a4e3-4a34-a4b6-e37845e8af7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>CNCIMF000003308</value>
      <webElementGuid>f51d5682-f3f0-4e98-8ef1-ed030368caf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selectResult(this.value)</value>
      <webElementGuid>7e5f3908-c8dc-4992-8fc2-5eca89668a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;menuHavingBody&quot;]/form[1]/div[@class=&quot;container-fluid&quot;]/table[1]/tbody[1]/tr[1]/td[2]/div[1]/table[1]/tbody[1]/tr[@class=&quot;tr_list&quot;]/td[@class=&quot;tr_list_alternate&quot;]/input[1]</value>
      <webElementGuid>e6d53d88-3b7e-40e0-9130-c9a2b774787d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='selectApplicant']</value>
      <webElementGuid>8b33f350-473c-4648-95b7-f1cf7948d903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>8c58ea7b-e651-4adf-8b58-fc837a9e15ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'selectApplicant']</value>
      <webElementGuid>c1e5dfa1-8030-4ee2-9056-610aa287082f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
