<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>font_123456789</name>
   <tag></tag>
   <elementGuidId>e0ab1fb6-4296-4149-954f-8c05708bf9e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='123456789']/table/tbody/tr/td[2]/a/font</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>font.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>fea28b28-afb0-42ed-95d6-fd7cbe95f4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>2px</value>
      <webElementGuid>fd131097-8b9b-4db3-89c0-83b9f124f4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>8ea7c1f8-4e3d-4953-bb95-d732eb3f29c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>123456789</value>
      <webElementGuid>9b6239de-6dad-4cc9-8bc1-1e4b8c0aa262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;123456789&quot;)/table[1]/tbody[1]/tr[1]/td[2]/a[1]/font[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>558312d0-c3af-4928-ae12-82304dd0f348</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='123456789']/table/tbody/tr/td[2]/a/font</value>
      <webElementGuid>88a50983-6d40-4bc2-87bb-57d284de9fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/following::font[1]</value>
      <webElementGuid>3c15bdbe-f51b-4b60-8f59-a7ecf57f7e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[1]/following::font[2]</value>
      <webElementGuid>4b6c7567-a4dc-45da-b547-64ba26c7cfba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/font</value>
      <webElementGuid>debfce69-44b6-4c41-8345-3cc4d6c2f380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//font[(text() = '123456789' or . = '123456789')]</value>
      <webElementGuid>f5924fb1-7a54-4d5a-a3d9-af0fdf913e7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
