<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hi SUPERUSER_bar3</name>
   <tag></tag>
   <elementGuidId>5e40b34d-40e9-4b9b-b1bd-e9a6680a6259</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toggle-button']/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.bar3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7c9e9459-b39e-409b-bee5-61a332755e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bar3</value>
      <webElementGuid>312e5416-2d7d-486c-bb85-44f83b88c88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggle-button&quot;)/div[@class=&quot;bar3&quot;]</value>
      <webElementGuid>f8ceeda7-d9fd-4027-8e1b-de0902820e9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toggle-button']/div[3]</value>
      <webElementGuid>cff5449d-7c48-4d81-b5a5-29a64ef329c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]</value>
      <webElementGuid>9b2a641d-0f25-4d6d-8700-57ad63d0fce2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
