<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CONVERT TOCUSTOMER DETAILS_customerIDButton</name>
   <tag></tag>
   <elementGuidId>0d83e8fd-8a37-4234-98b4-83fee6f6ace0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customerIDButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customerIDButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7f1e163-2e43-43c1-a16e-01b5fd0e4a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8317667e-ccca-4a6a-ac5c-b4c64d3bf70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerIDButton</value>
      <webElementGuid>464fa0e6-478f-4588-8131-5525a4ebb936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Convert to Customer</value>
      <webElementGuid>c1310049-2b0e-4384-bcb3-d2b52934a79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customerIDButton</value>
      <webElementGuid>3dfdb2d8-c495-4599-a9dd-a968c98ffdb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:validate();</value>
      <webElementGuid>e5d9e3b4-8756-4fad-8dcf-5006deab987f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customerIDButton&quot;)</value>
      <webElementGuid>a26d21ff-2a9f-48a8-ada6-1ae59bc0e39c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customerIDButton']</value>
      <webElementGuid>86273c4d-6e43-4ed3-9836-a74145b8666a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='productForm']/div/div[3]/div[2]/input</value>
      <webElementGuid>c40575eb-53aa-4516-8705-813448fe93ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>8454c3b2-b520-4087-afae-257984c13822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'customerIDButton' and @id = 'customerIDButton']</value>
      <webElementGuid>ba84d15c-9aa3-49c4-96d9-d3e7eefb9ceb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
