<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECTYESNO</name>
   <tag></tag>
   <elementGuidId>3e3d0f91-4ff4-4cbd-9a98-7a95c005bd38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='clientApprovalDropDown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#clientApprovalDropDown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>183e2355-055f-43ff-9390-827767f67341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>approvalFlag</value>
      <webElementGuid>4281291d-ca58-48ae-993c-0d3a2e038edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clientApprovalDropDown</value>
      <webElementGuid>17ba33e6-70c0-4ee8-ab2e-8eb055bd5bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>setDate()</value>
      <webElementGuid>f478a366-8055-44d0-9293-c1b1dcb164af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validField</value>
      <webElementGuid>f687dd8f-74ef-4778-80d9-68b5baf07a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							SELECT
							YES
							NO
						</value>
      <webElementGuid>fee2b3c7-ef8c-4dda-ab4b-82755b69fb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clientApprovalDropDown&quot;)</value>
      <webElementGuid>8b46b20f-9d8e-4d1c-8c38-5bcc4530d8bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='clientApprovalDropDown']</value>
      <webElementGuid>f8830bf4-9289-44b7-8ab2-d89a67c03770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='productForm']/div/div[4]/div[24]/select</value>
      <webElementGuid>7edfe4e6-74d1-4a60-b1e5-4a258730c10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Approval'])[1]/following::select[1]</value>
      <webElementGuid>fec043d6-520c-41b0-8dc7-92c58b8d1b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer ID'])[1]/following::select[1]</value>
      <webElementGuid>ddbe2a9b-389e-44ad-aa51-8c35c00cd77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Approved/Declined Date'])[1]/preceding::select[1]</value>
      <webElementGuid>08c688f1-67d1-4d9b-b661-39b93599b332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'clientApprovalDropDown', '&quot;', ')')])[1]/preceding::select[1]</value>
      <webElementGuid>a2f47940-69c5-4de5-8ddb-46b8683650af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/select</value>
      <webElementGuid>4d01ab1b-ae27-4706-af6e-1602f47bb0b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'approvalFlag' and @id = 'clientApprovalDropDown' and (text() = '
							SELECT
							YES
							NO
						' or . = '
							SELECT
							YES
							NO
						')]</value>
      <webElementGuid>1eb1f21e-7129-4628-b4bb-123363ae4f0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
