<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_payment_Row</name>
   <tag></tag>
   <elementGuidId>4ab92124-0afa-42c8-8d4a-8edcff63eaaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment_Row1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment_Row1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cec7bb0-1a63-4d44-88de-6a96d7b514ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment_Row1</value>
      <webElementGuid>b136caba-1c5d-4471-af9a-f54572a6aa5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_Row</value>
      <webElementGuid>b036d2ef-95a8-4dbd-8d6a-449c130899b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>55fa866b-8168-41b3-8504-bbc861070c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5294236b-9330-427a-b968-a0c8014da16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>togglePaymentRow(this);</value>
      <webElementGuid>8894e46f-d9de-45e8-afd2-c74fef6001d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_Row1&quot;)</value>
      <webElementGuid>95e43245-8239-4d79-a562-4d49de41ba83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment_Row1']</value>
      <webElementGuid>cdf941e2-aaea-416b-a7f9-f31ddfc2fc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='addRow']/tbody/tr[2]/td/input</value>
      <webElementGuid>a5bb6b47-bbe0-47dc-aa92-05276ce52e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>c3ad95d8-53a1-487f-8610-14837d24b8b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment_Row1' and @name = 'payment_Row' and @type = 'checkbox']</value>
      <webElementGuid>b015a7d7-308d-416f-b2c2-93b57e3d048e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
