<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DMFIN1000008427_aRemarks_1</name>
   <tag></tag>
   <elementGuidId>50112cef-c0b3-4b23-be68-dde0fb9dd112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aRemarks1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='aRemarks1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b24769d-9207-41d4-9daa-ba5fe87e04d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf957f4d-9e58-474c-9e44-83c6c8eae732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aRemarks</value>
      <webElementGuid>26a21c60-4e4d-4410-83eb-a1b6fb9d32da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aRemarks1</value>
      <webElementGuid>9e53c149-f242-44ad-bbec-684ec67f13d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>e7a2684e-b778-4325-803c-38e4bb536f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>3e7b3408-7d63-4890-85ee-d9f9502bbfd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>o</value>
      <webElementGuid>11001cb2-1496-4c19-a03f-a403d425a22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aRemarks1&quot;)</value>
      <webElementGuid>2da44f57-c3b0-4546-9dd2-fb96990e3bb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='aRemarks1']</value>
      <webElementGuid>d1d93f02-3ac4-4d65-a87d-78e40638dc50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='addRow']/tbody/tr[2]/td[23]/input</value>
      <webElementGuid>f6b0535e-9235-475b-900d-c3f4702097d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[23]/input</value>
      <webElementGuid>fa83c7f5-b535-4c97-992a-cea6fb7adae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'aRemarks' and @id = 'aRemarks1' and @title = 'o']</value>
      <webElementGuid>ae367f6b-573d-4543-b4ae-d2cc79fa1660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
