<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DM VIEWER_imgDiv</name>
   <tag></tag>
   <elementGuidId>c4705cd9-7147-455b-a237-9c0857f05fc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#action1000000017 > div.fgfg.MenuLevel0Parent > #imgDiv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='imgDiv'])[19]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ca2148c9-9e8f-4198-8956-f547cea83f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgDiv</value>
      <webElementGuid>15160a96-70e2-4b7d-bad8-cac1a94856cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>toggleChildren('1000000017')</value>
      <webElementGuid>5a941911-26c5-4fc8-9854-9fd80dae593f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7c6a9394-998f-4efc-adf3-a93db01febb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>5b012241-7c89-4da0-b1ff-e28e78edfa12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>partentTgl</value>
      <webElementGuid>2d8a7233-e954-420e-bfd7-b3621180d2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;action1000000017&quot;)/div[@class=&quot;fgfg MenuLevel0Parent&quot;]/div[@id=&quot;imgDiv&quot;]</value>
      <webElementGuid>f0c4f1a0-2580-4550-a0e8-5307ea136c34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='imgDiv'])[19]</value>
      <webElementGuid>393c2059-a1a5-4ae8-bcdf-dbbc70c74966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action1000000017']/div/div</value>
      <webElementGuid>55e20965-2fbf-4b7a-bc74-1e11f3780fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DM VIEWER'])[1]/following::div[4]</value>
      <webElementGuid>4c40901f-0252-4298-968c-9fc1f0236299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEWER'])[3]/following::div[8]</value>
      <webElementGuid>d8b85241-08cb-4c86-83bf-917c3824efab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LMS'])[1]/preceding::div[1]</value>
      <webElementGuid>b4e78097-38dc-4cf0-9b4a-b9fecdf04983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INVOICE'])[1]/preceding::div[3]</value>
      <webElementGuid>7325f521-0caa-4735-8a5c-f852af075d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[74]/div/div</value>
      <webElementGuid>9429dfda-d9dc-455d-aeae-da1005f44ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'imgDiv']</value>
      <webElementGuid>eea5972e-7857-4dd0-9d7c-01d74c3983e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
