<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Remarks_arRemarks</name>
   <tag></tag>
   <elementGuidId>a840a22f-b597-4fc8-bc0f-aa33ac0c485a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#arRemarksId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='arRemarksId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>58b547e3-c555-481a-9143-3022487373f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>arRemarks</value>
      <webElementGuid>ee247161-10bb-48d3-9192-d5f6aed4979b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>fa8d3c70-b0a8-432e-8c04-af034548219b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d480199a-1278-4b82-b669-7554f6d07233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkRemark(this,'Author Remark')</value>
      <webElementGuid>aecb2ddb-1a2f-4907-a278-f906e1f325f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arRemarksId</value>
      <webElementGuid>79012690-a8a1-4aa8-8bb7-bb6bcabc1fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arRemarksId&quot;)</value>
      <webElementGuid>727ab02a-9a39-4cfb-b463-c8ad785ef363</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='arRemarksId']</value>
      <webElementGuid>53da7a34-67f4-467b-9b35-bec914bc1394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fieldSetId']/div[3]/div/div[2]/textarea</value>
      <webElementGuid>1499fc31-f399-4213-bb68-a7a122f720b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/textarea</value>
      <webElementGuid>323993e7-b3df-4802-8f9f-b5cec329bd83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'arRemarks' and @id = 'arRemarksId']</value>
      <webElementGuid>2254d750-e813-46e8-b413-d432933256d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
