<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LMCST0000006131</name>
   <tag></tag>
   <elementGuidId>9b2f51ed-15c1-4172-b141-3e1e49eeac6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='allApplicantEntries']/table/tbody/tr[3]/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.tr_list_alternate > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>281577fb-8cb3-4cfb-a249-54cad1bb6c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:showDetail('1000007978');</value>
      <webElementGuid>eb8619c0-1439-49af-ac59-3f78b161a6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LMCST0000006131</value>
      <webElementGuid>b0c19060-7707-444b-bc0a-0122a84a1d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allApplicantEntries&quot;)/table[@class=&quot;tr_list&quot;]/tbody[1]/tr[3]/td[@class=&quot;tr_list_alternate&quot;]/a[1]</value>
      <webElementGuid>1116efb5-0f3d-4de0-81e6-db8c0029c2a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allApplicantEntries']/table/tbody/tr[3]/td/a</value>
      <webElementGuid>ad9aa8a8-9901-4cd2-813c-72f0c3ac4fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LMCST0000006131')]</value>
      <webElementGuid>6694327c-9238-49e4-b302-e34dd8810914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limit Status'])[2]/following::a[1]</value>
      <webElementGuid>cf4f5c8a-70a3-46c9-b787-b284f19d1129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiry Date'])[1]/following::a[1]</value>
      <webElementGuid>e9e26b14-279d-43e4-ad2d-32138be17a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNCIMF000003116'])[1]/preceding::a[1]</value>
      <webElementGuid>98688d53-1b9b-4338-bacf-f71ff47894f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROHAN TESTQA'])[1]/preceding::a[1]</value>
      <webElementGuid>addaa50a-0c3f-4b8a-a99d-cab062b45d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LMCST0000006131']/parent::*</value>
      <webElementGuid>1ef38469-a9b2-4b21-92b3-71e710f78e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:showDetail('1000007978');&quot;)]</value>
      <webElementGuid>3ea6f558-4d8d-4ba7-85de-dc102ea0b2eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>1e567195-ff74-407e-8b4d-9c3b39b61265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:showDetail(&quot; , &quot;'&quot; , &quot;1000007978&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = 'LMCST0000006131' or . = 'LMCST0000006131')]</value>
      <webElementGuid>27913463-52b8-4ec3-9553-78274284c014</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
