<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save_1</name>
   <tag></tag>
   <elementGuidId>5d9506db-3274-4cc8-a5eb-28ea46e2acf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Save')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SaveLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2f8f7754-1f0f-4236-badf-0ab13e7593f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:save()</value>
      <webElementGuid>db6c2f83-3a6b-4b57-a596-d7d4486cd8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SaveLink</value>
      <webElementGuid>c747788d-7a91-423f-9a0f-48a52e131e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SaveLink</value>
      <webElementGuid>015c0614-ee8c-41e0-8a64-4b6befac7ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						Save</value>
      <webElementGuid>e918d1d9-5c19-4d6b-8cc7-e86a8ca2542b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SaveLink&quot;)</value>
      <webElementGuid>2d44296c-7062-4c41-892b-5c1cac87c087</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='SaveLink']</value>
      <webElementGuid>12e90e14-dced-4c42-a8f1-2af924efbe35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subHeaderMenuDiv']/a[4]</value>
      <webElementGuid>77b724ef-e40e-4828-a5e8-789045063d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Save')])[2]</value>
      <webElementGuid>f686900d-fae9-4252-998d-90727b5b40e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save &amp; Exit'])[1]/following::a[1]</value>
      <webElementGuid>99b35282-f825-4529-8bb2-0e206ff5eeb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Worklist'])[1]/following::a[2]</value>
      <webElementGuid>b3d70f78-725f-4706-b5c8-1576494d2ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIMIT EDIT'])[1]/preceding::a[1]</value>
      <webElementGuid>702b6b26-85a7-4fb3-920d-fd9e87d668a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FINANCIAL AND BANKING'])[1]/preceding::a[2]</value>
      <webElementGuid>1ea49b97-bfb9-4191-abaf-e9611155606e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>a68121eb-c27e-4c83-b2a9-6394db1ad44d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:save()')]</value>
      <webElementGuid>d3d992c9-e4ba-4617-bee8-85d46d45d1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>659e4c21-e55b-4972-892a-b6e2c4b5110e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:save()' and @id = 'SaveLink' and @name = 'SaveLink' and (text() = '
						Save' or . = '
						Save')]</value>
      <webElementGuid>ede1c363-744f-4d0d-8647-c42da05e1c08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
