<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_GROUP EDIT_img1200006000</name>
   <tag></tag>
   <elementGuidId>00517e15-68d3-49d8-9bec-a2561168fb60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='img1200006000']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img1200006000</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>07504953-50e1-48bd-8d05-d370a0eb0687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img1200006000</value>
      <webElementGuid>8c164025-3ec9-499d-b0d4-78d3848631de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>8f9f0625-868a-446b-a7eb-0e3a4b56a7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3854d1bf-7c03-4f9d-9d38-31c1039c6534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img1200006000&quot;)</value>
      <webElementGuid>52ecf78a-9d4d-48c1-bf47-dbfe56bce480</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='img1200006000']</value>
      <webElementGuid>b0b50e98-32ea-41d7-ad82-cf79566aca54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='imgDiv']/i)[9]</value>
      <webElementGuid>fc1d6c89-118e-4a1d-b987-90071d215c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[30]/div/div/i</value>
      <webElementGuid>a143cd79-d129-42ec-b4e5-5584d3053721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'img1200006000']</value>
      <webElementGuid>5302b66b-713d-48d2-933e-02ce955f78fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
