<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Hi NAVINS_userr</name>
   <tag></tag>
   <elementGuidId>d557f5e8-d96e-44f7-9be5-e6fd0f172b12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.userr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f1ae9b32-0a26-4716-b8b3-41a2c58afe8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>userr</value>
      <webElementGuid>6a1fb1fe-de42-4069-8c63-3c8e6419092d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/picuser_head.png</value>
      <webElementGuid>05d77020-4bf3-4863-9c06-758551dc8150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditDetailId&quot;)/form[@class=&quot;ng-pristine ng-valid&quot;]/div[@class=&quot;backe_image col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[1]/div[@class=&quot;col-lg-4 col-md-4 col-sm-4 col-xs-4&quot;]/div[1]/span[@class=&quot;username_icon&quot;]/img[@class=&quot;userr&quot;]</value>
      <webElementGuid>20a2e640-15e6-439e-9cdd-a738da1ee943</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='creditDetailId']/form/div/div/div[3]/div/span/img</value>
      <webElementGuid>44133eaa-79d4-4a72-84c0-619b8e06690b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>0b8be61a-2bb4-4bf2-9795-4e2b1e8f4d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/picuser_head.png']</value>
      <webElementGuid>a1e5022e-8472-4bc7-af73-c275d27b71aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
