<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SYSUSER_UPDATED_CHK2</name>
   <tag></tag>
   <elementGuidId>ad99cc32-eaa3-4afe-9710-e5d03a83202f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UPDATED_CHK2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#UPDATED_CHK2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>693f8c16-838d-4b02-baa2-6093fce4b7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fc6706b6-f30a-49a4-94f9-56a7b8a56da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UPDATED_CHK2</value>
      <webElementGuid>a6cc18c6-149c-48f8-bbce-427de7138253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>docDetail.UPDATED</value>
      <webElementGuid>89ce77c5-701d-4e84-82ea-c0817cd552d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-checked</name>
      <type>Main</type>
      <value>docDetail.UPDATED=='Y'?true:false</value>
      <webElementGuid>56dea679-902b-4ac3-a0fe-db6624716048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>deleteUpdateChecked(docDetail,'U',$index)</value>
      <webElementGuid>aae777e4-58b2-41fc-98ba-7796f5824843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>docDetail.ALLOW_UPDATE_FLAG=='N'?true:false</value>
      <webElementGuid>b080d80b-622d-4759-9705-105ead3e5901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>482f807f-3f8f-4f4c-8878-eabed07364bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UPDATED_CHK2&quot;)</value>
      <webElementGuid>3309dd75-5cb8-4174-8aa6-3c306bbb6d0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UPDATED_CHK2']</value>
      <webElementGuid>0092d38e-f733-438f-8d2b-d311ea8110e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='documentTable']/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>1496c2f8-f96a-4a00-a69a-ca37d931b4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>24e995d1-ea02-4578-905e-c228324ea84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'UPDATED_CHK2']</value>
      <webElementGuid>9183c905-ab35-49c1-b013-fd442798f5d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
