<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SYSUSER_DOCUMENT_DESCRIPTION1</name>
   <tag></tag>
   <elementGuidId>a29858e5-2f4f-47e5-872f-0f13ece0d139</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DOCUMENT_DESCRIPTION1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DOCUMENT_DESCRIPTION1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84dd230b-94d4-46cf-a875-5a2d2293cbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ed35036-6af3-4b13-bc50-1674e43281ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DOCUMENT_DESCRIPTION1</value>
      <webElementGuid>ee56314f-7a39-4947-808e-0f6315e3f78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>docDetail.REMARKS</value>
      <webElementGuid>e559e59f-99c5-47cc-9ef4-27a656d131ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>24fcd749-2ef2-4acd-bf7d-5b55acfe8e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-valid-maxlength</value>
      <webElementGuid>97047699-8b95-490d-85de-e624f7cef957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DOCUMENT_DESCRIPTION1&quot;)</value>
      <webElementGuid>44dd4915-2e7c-4e8e-8037-88f622c66935</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DOCUMENT_DESCRIPTION1']</value>
      <webElementGuid>e0c23f77-7dfe-4c81-a241-f9906f5be054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='documentTable']/tbody/tr[3]/td[7]/input</value>
      <webElementGuid>3ef36e3c-4ce4-4dec-a0cd-8c6b5914fcb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[7]/input</value>
      <webElementGuid>eb7b41bb-db04-4a5b-8aad-d6d688025c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DOCUMENT_DESCRIPTION1']</value>
      <webElementGuid>df2c57da-c06b-4543-8a6b-5cf07f43d62e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
