<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SYSUSER_DOCUMENT_DESCRIPTION2</name>
   <tag></tag>
   <elementGuidId>45b28ab3-ec0b-4162-b02d-d7f29f06ce0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DOCUMENT_DESCRIPTION2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DOCUMENT_DESCRIPTION2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6200659-b69c-4b15-b42a-e1255dde39a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6df61f5c-6e52-4d40-bf2d-abf0b2326456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DOCUMENT_DESCRIPTION2</value>
      <webElementGuid>600a05b6-ba97-4af1-8132-8249be25e95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>docDetail.REMARKS</value>
      <webElementGuid>713ce315-5a2b-4012-9601-1f8859f5bab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>fe7ee0e2-397c-4f15-96f8-174500faeb30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-valid-maxlength</value>
      <webElementGuid>29cd2a59-7640-41e2-8fa2-40c5f7fab4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DOCUMENT_DESCRIPTION2&quot;)</value>
      <webElementGuid>fe4f6c75-dd19-40af-b485-5909e28e4e64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DOCUMENT_DESCRIPTION2']</value>
      <webElementGuid>a679bd1b-f9f5-4df7-8692-3ddc2edd8b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='documentTable']/tbody/tr[4]/td[7]/input</value>
      <webElementGuid>3810ecfd-5424-4475-9c29-9dba83d772cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[7]/input</value>
      <webElementGuid>adba0989-4253-4faa-adaf-03133b8a6977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DOCUMENT_DESCRIPTION2']</value>
      <webElementGuid>b28f673e-a66f-4047-8164-27d275bb2a35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
