<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectRECEIVEDPENDINGDEFERRED_1_2_3</name>
   <tag></tag>
   <elementGuidId>7eb58f37-70b5-43b5-952e-9d88ff009d18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DOCCOLLECTION_STATUS3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DOCCOLLECTION_STATUS3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e82b2397-4f76-483f-a4a5-512cea08b8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DOCCOLLECTION_STATUS3</value>
      <webElementGuid>bf315927-9d69-4dee-9769-c085b9c422de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>setStatusDates(docDetail,$index)</value>
      <webElementGuid>d85e38df-db4c-4de9-9890-2ab286a79cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>docDetail.DOCCOLLECTIONSTATUSID</value>
      <webElementGuid>37db343e-55d9-42df-8885-b376de862e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>d62d061f-a0a5-4d3c-a6e7-bb531cb692cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					   Select
						RECEIVEDPENDINGDEFERRED
						</value>
      <webElementGuid>9ee057fa-0bc9-44e9-b921-78a19b360aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DOCCOLLECTION_STATUS3&quot;)</value>
      <webElementGuid>9740df14-6674-41f4-a955-1e6ed9c80f58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DOCCOLLECTION_STATUS3']</value>
      <webElementGuid>853cadc7-dfab-4972-b783-57e41396c386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='documentTable']/tbody/tr[5]/td[10]/select</value>
      <webElementGuid>e0a7a30e-f7a3-4df1-ae7c-e7827d6ac8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYSUSER'])[3]/following::select[5]</value>
      <webElementGuid>96d7c63a-d692-4b99-ad32-64c817c87f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Document'])[3]/following::select[7]</value>
      <webElementGuid>95853cdd-abb1-484a-902a-7fefc850c614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYSUSER'])[4]/preceding::select[2]</value>
      <webElementGuid>88e25c8f-fc73-41ce-8878-61e731297363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qualtech Consultants Pvt. Ltd.'])[1]/preceding::select[2]</value>
      <webElementGuid>c7e73445-5268-4e0b-b60d-3b5be385c2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[10]/select</value>
      <webElementGuid>92079f6f-2b3b-4c6c-89d5-b42d1a8bb411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DOCCOLLECTION_STATUS3' and (text() = '
					   Select
						RECEIVEDPENDINGDEFERRED
						' or . = '
					   Select
						RECEIVEDPENDINGDEFERRED
						')]</value>
      <webElementGuid>203ff995-822d-466b-8abb-6dbe2a93f5a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
