<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectRECEIVEDPENDINGDEFERRED_1</name>
   <tag></tag>
   <elementGuidId>6a109801-5a55-41bb-a2c5-9762a32f81a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DOCCOLLECTION_STATUS1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DOCCOLLECTION_STATUS1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f11a7d3d-5b37-464e-9eda-720c9eeace4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DOCCOLLECTION_STATUS1</value>
      <webElementGuid>e9cd2a84-85ff-4339-b323-e480b072c221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>setStatusDates(docDetail,$index)</value>
      <webElementGuid>437709b7-e121-4ca8-ad0a-cf1476363f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>docDetail.DOCCOLLECTIONSTATUSID</value>
      <webElementGuid>43d029e8-7b9a-4dc5-971b-6c5344096c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>4b8e13ef-665c-46ae-a580-06471437e0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					   Select
						RECEIVEDPENDINGDEFERRED
						</value>
      <webElementGuid>2a6650bd-4695-4f67-aa14-7891632848a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DOCCOLLECTION_STATUS1&quot;)</value>
      <webElementGuid>807ee0d7-af4b-4465-84f3-845e34c2ea7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DOCCOLLECTION_STATUS1']</value>
      <webElementGuid>65e6d918-e6d6-44a0-8b32-358a067e98a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='documentTable']/tbody/tr[3]/td[10]/select</value>
      <webElementGuid>3aa97d1f-d991-469b-8ab7-5f7386b73ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYSUSER'])[1]/following::select[5]</value>
      <webElementGuid>e82e3f9b-eb30-46f3-8855-adb8f5ab141f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Document'])[1]/following::select[7]</value>
      <webElementGuid>94512660-5941-40d3-b46d-1b70eaaaf7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYSUSER'])[2]/preceding::select[2]</value>
      <webElementGuid>e508d055-0f42-4984-b7ab-4608354053a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYSUSER'])[3]/preceding::select[8]</value>
      <webElementGuid>2159dc1a-35d4-4325-ac2a-1e59a347684e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[10]/select</value>
      <webElementGuid>1daef42c-ba6b-4ad0-87b5-3b95eb724a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DOCCOLLECTION_STATUS1' and (text() = '
					   Select
						RECEIVEDPENDINGDEFERRED
						' or . = '
					   Select
						RECEIVEDPENDINGDEFERRED
						')]</value>
      <webElementGuid>0c6afde6-c72d-4bff-b1ec-ca94b3532d83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
