<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remarks_remark_1</name>
   <tag></tag>
   <elementGuidId>014be6ac-b6ad-4806-af66-58374c99b34a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='remark']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#remark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0382b5a0-3628-4695-9027-7fbfc7dcbd11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0af1134c-6f80-409f-8db3-ca2552ac7e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>61e16f82-3387-4d3f-b932-30120229f96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>03b811d6-14a7-4022-a971-9a71c148deae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>remark</value>
      <webElementGuid>254f6a44-ff1c-42da-bde9-9522909bd782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remark</value>
      <webElementGuid>c460f017-cd1a-4f17-9f59-d560f7baf0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>o</value>
      <webElementGuid>763fca8f-891c-4898-a294-cb44109dc87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remark&quot;)</value>
      <webElementGuid>7a337f7f-a55f-42a7-bb35-ccf25e130feb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='remark']</value>
      <webElementGuid>612419cf-4e89-402c-be00-95defaa07656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='emiinfo']/tbody/tr[4]/td[10]/input</value>
      <webElementGuid>4bd0e2f4-dc92-46f0-bbc1-59006bc20db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/input</value>
      <webElementGuid>6d416de0-d676-429a-b310-1587e8388341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'remark' and @id = 'remark' and @title = 'o']</value>
      <webElementGuid>9ccc5f37-6ace-4680-8ed6-fede02ef3789</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
