<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DEDUPE</name>
   <tag></tag>
   <elementGuidId>d71db62a-f3c2-4442-8239-9fccad32309b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ebddc4e-3e0f-4f78-906a-7a45788c9bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>dedupe.do?actionPerformed=displayDedupeCustomerList&amp;screenId=1000000080&amp;mode=E&amp;disName=DEDUPE</value>
      <webElementGuid>d19c6996-ffc2-415e-9eeb-5e29634428b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noLine</value>
      <webElementGuid>36efde0e-6407-4c11-b315-568f40b6e279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DEDUPE</value>
      <webElementGuid>f8694a14-d4da-4d01-b20a-396142a03e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;menu col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[2]/a[@class=&quot;noLine&quot;]</value>
      <webElementGuid>4d277c24-a042-4682-85a7-fb280fbabe45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div/div[2]/a</value>
      <webElementGuid>06a911ea-4001-4a1d-b46d-d3d7dc391ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DEDUPE')]</value>
      <webElementGuid>d3eedbba-c527-4c29-b93b-94964488b028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPLICANT'])[1]/following::a[1]</value>
      <webElementGuid>5612927f-501e-456b-8bff-2af38017e0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Dashboard'])[1]/following::a[2]</value>
      <webElementGuid>7573bc98-7e02-4268-b4a5-e8724b058b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTEPAD'])[1]/preceding::a[1]</value>
      <webElementGuid>f8482f0a-c495-4588-a27a-18b7011a79fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOCUMENT'])[1]/preceding::a[2]</value>
      <webElementGuid>ec0c6fb7-26c6-4572-adf4-020ac6bd185a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DEDUPE']/parent::*</value>
      <webElementGuid>b17e5fe6-7163-4e51-a371-e01749573cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'dedupe.do?actionPerformed=displayDedupeCustomerList&amp;screenId=1000000080&amp;mode=E&amp;disName=DEDUPE')]</value>
      <webElementGuid>71cde42f-c883-4c4a-9076-0a5331274ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/a</value>
      <webElementGuid>ee52b500-1280-4616-a51d-9bd1399c3d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'dedupe.do?actionPerformed=displayDedupeCustomerList&amp;screenId=1000000080&amp;mode=E&amp;disName=DEDUPE' and (text() = 'DEDUPE' or . = 'DEDUPE')]</value>
      <webElementGuid>37408af9-8c50-4dba-a10a-b508b3f555c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
