<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DMFIN1000008427</name>
   <tag></tag>
   <elementGuidId>e9ca2a8f-3df4-4a60-bcb4-807fbafbbec7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='existingTable']/tbody/tr/td[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e01fd3c5-4dab-459c-bbfb-cd0bcf56c4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f0af9b4c-1210-4cf6-8f8d-6b4895f5cd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>showDetail(quotation.DM_ID,quotation.DM_CODE,quotation.ASSET_FROM,quotation.LIMIT_EDIT_FLAG)</value>
      <webElementGuid>5f37f117-6241-4c27-8f31-6124d29fc9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>b532ac4b-e264-47c6-9215-3f3a3bf14f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>dcb32fe7-9b72-41f1-8f02-09c98f6f6b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DMFIN1000008427 </value>
      <webElementGuid>5bffb891-e2c3-40b6-9aba-a6db049166e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;existingTable&quot;)/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[5]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>48eaa1b6-e4f0-49fb-8375-8556e5d04546</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='existingTable']/tbody/tr/td[5]/a</value>
      <webElementGuid>3a409bf3-3c15-4a43-8482-1762b5336d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DMFIN1000008427')]</value>
      <webElementGuid>60f8a509-5e94-4a01-969d-756b1361c389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QU00023115'])[1]/following::a[1]</value>
      <webElementGuid>0d61814d-8bc0-435b-8d4c-d096bdfdec30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN00023114'])[1]/following::a[1]</value>
      <webElementGuid>fb67d7a2-9b06-43ae-808c-362da321b0ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROOHI DUPONT'])[1]/preceding::a[1]</value>
      <webElementGuid>e65168c0-101b-452a-9f43-bfa234823b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MARIE JACQUES DESIRE MICHEL'])[1]/preceding::a[1]</value>
      <webElementGuid>ea45319e-0238-42a9-a063-f904c60a007d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DMFIN1000008427']/parent::*</value>
      <webElementGuid>f710ed7b-c85e-448c-9d9a-acd82dbe0f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>88301d0a-d209-4ae2-bdc8-f885ed40d7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>4a5be9b1-f443-4604-9bcc-23b88fc77d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'DMFIN1000008427 ' or . = 'DMFIN1000008427 ')]</value>
      <webElementGuid>aedf4dae-22af-4693-91bf-b0d2ce3ebc2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
