<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DMFIN1000008443</name>
   <tag></tag>
   <elementGuidId>dfa53da0-c90f-4bb6-a9a4-5afff56c0e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='existingTable']/tbody/tr/td[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2e65794e-5e23-4892-8886-f6446c65f381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f074c8c2-60aa-4fc5-ae23-1f62d7d8093e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>showDetail(quotation.DM_ID,quotation.DM_CODE,quotation.ASSET_FROM,quotation.LIMIT_EDIT_FLAG)</value>
      <webElementGuid>915bdcd0-7612-407d-a669-90a814b2fd2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>e32ad7ca-4375-4f29-bea9-5afe60ecb740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>df369639-637f-484b-b4bc-7f53a449ab10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DMFIN1000008443 </value>
      <webElementGuid>3314b6e1-23a2-4bc0-93ef-5978797703fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;existingTable&quot;)/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[5]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>d9341c29-b80a-4f7c-8bd8-f6827d8aff99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='existingTable']/tbody/tr/td[5]/a</value>
      <webElementGuid>59bf3559-9cf1-4f3c-870e-1d8070b0144d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DMFIN1000008443')]</value>
      <webElementGuid>b0eab0e3-bba2-4a26-92a3-39bfb1faa695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QU00023147'])[1]/following::a[1]</value>
      <webElementGuid>f049d66d-5b38-459e-94e6-d5082eac9340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN00023146'])[1]/following::a[1]</value>
      <webElementGuid>a5057b9a-5514-4fd3-a523-0a0ab9e1783d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('SUMESH', &quot;'&quot;, 'S PAL')])[1]/preceding::a[1]</value>
      <webElementGuid>a85e47fd-8e3a-42cc-b127-545b06ff9d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNCIMF000003724'])[1]/preceding::a[1]</value>
      <webElementGuid>902c2023-da1d-4180-972e-ac388f255d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DMFIN1000008443']/parent::*</value>
      <webElementGuid>bc18bcd2-31fa-46cc-8125-01ec37bd85b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>68fad7c1-0700-46fb-b588-6084b4b08681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>5ae950b2-ec5d-4c7e-86c9-d4d8a80df73a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'DMFIN1000008443 ' or . = 'DMFIN1000008443 ')]</value>
      <webElementGuid>099109d4-6e19-4327-859c-47677f08f159</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
