<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LMCST0000006405</name>
   <tag></tag>
   <elementGuidId>5dc69328-9032-466f-9e39-6ca7b2bb96cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='allApplicantEntries']/table/tbody/tr[3]/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.tr_list_alternate > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e7d2ded5-2098-4036-819f-1c77eab4077b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:showDetail('1000009221');</value>
      <webElementGuid>87e9c308-678c-4577-8590-9c0245e452cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LMCST0000006405</value>
      <webElementGuid>5b27a2fd-6392-4aec-abed-085be754ed00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allApplicantEntries&quot;)/table[@class=&quot;tr_list&quot;]/tbody[1]/tr[3]/td[@class=&quot;tr_list_alternate&quot;]/a[1]</value>
      <webElementGuid>5137d388-9b1d-4f82-96fd-032589184906</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allApplicantEntries']/table/tbody/tr[3]/td/a</value>
      <webElementGuid>c32265c7-add5-4ccd-9bcd-de8e72f15229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LMCST0000006405')]</value>
      <webElementGuid>172a7ad1-b19a-4cb3-ab2f-c3fb746f489a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limit Status'])[2]/following::a[1]</value>
      <webElementGuid>e4582b9d-4c98-4800-b33a-aa79cf631fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiry Date'])[1]/following::a[1]</value>
      <webElementGuid>c7d884b1-4220-43aa-9d49-1ff74a1f3128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNCIMF000003846'])[1]/preceding::a[1]</value>
      <webElementGuid>19eea3cb-8374-4a30-b1b5-b277cf742941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SQATEST QATESM'])[1]/preceding::a[1]</value>
      <webElementGuid>5ffdfcec-5a45-42e8-b862-115b8f7ce9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LMCST0000006405']/parent::*</value>
      <webElementGuid>2a0ef28c-b7f1-44c0-8cb8-97068def2e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:showDetail('1000009221');&quot;)]</value>
      <webElementGuid>74ef0eec-3426-4a8c-8fdc-dd71caf3736f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>f4c35190-0997-4555-8b49-d1e87f0d59f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:showDetail(&quot; , &quot;'&quot; , &quot;1000009221&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = 'LMCST0000006405' or . = 'LMCST0000006405')]</value>
      <webElementGuid>e463d898-0b3f-4cbe-8bdd-4ec11c17009f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
