<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth_dob_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>0f834864-8095-426b-8149-df3bcd7850b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='dob']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;dob&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7093056a-a66c-49b0-a197-8a8a4e61b1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb319074-7039-43d3-b8a2-c65d3f8cd9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dob</value>
      <webElementGuid>c11b0caa-0e20-44ce-bd81-ad2956ff4690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>fb9ba4fa-587f-4d33-ac00-0cb3cc6d06bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:checkDateFormat(this,'Date of Birth');</value>
      <webElementGuid>7f79b711-3cc5-4566-acdd-34b00d6ba09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>09-jun-</value>
      <webElementGuid>349cd054-e9ed-4429-9712-105329c6b8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divCustEntityTypeInd&quot;)/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-lg-2 col-md-2 col-sm-3 col-xs-6&quot;]/input[1]</value>
      <webElementGuid>ae722a31-be90-4171-8556-60fb26c2140c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='dob']</value>
      <webElementGuid>00b9eaa2-adef-49ec-b9a2-89b8d9b228a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCustEntityTypeInd']/div/div/div[21]/input</value>
      <webElementGuid>00772f51-9e5e-4526-85f4-53d052ee5301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/input</value>
      <webElementGuid>c553573f-61ca-49c7-843d-ec28ce25a429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'dob' and @title = '09-jun-']</value>
      <webElementGuid>8c82c45a-d800-4850-afba-bb96064c1b62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
