<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DM Code_dmCode_1 (1)</name>
   <tag></tag>
   <elementGuidId>c0ceda5c-8d09-4534-9278-f3f28ea60aaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dmCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dmCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bbeaccb2-50e8-4de0-af4a-c3bb71722f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_header_cost ng-untouched ng-valid ng-dirty ng-valid-parse</value>
      <webElementGuid>6beb167e-1a5f-465c-b0c8-faa6acc5662a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3b3b9d80-5752-41df-b741-7712fd71c8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dmCode</value>
      <webElementGuid>5dd84935-4f45-4465-9cda-b903bd662496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>searchData.dmCode</value>
      <webElementGuid>11192e12-252b-49fd-a8a3-65aeab18986a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DMFIN1000008427</value>
      <webElementGuid>93a7e23d-c562-4efc-80f6-260144d2ecaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dmCode&quot;)</value>
      <webElementGuid>065cb2bc-314c-43fb-9f8d-9323776e9260</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dmCode']</value>
      <webElementGuid>c4a863a2-a04c-48ce-aaf5-f8e6d410516a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='dashbord_main']/form/div[5]/div/div/div[12]/input</value>
      <webElementGuid>b0632a23-82e5-4f12-b33a-376cef60446c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/input</value>
      <webElementGuid>d4f0fe74-2cbb-4a2b-9527-1a46a10bdecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dmCode' and @title = 'DMFIN1000008427']</value>
      <webElementGuid>d71e102b-6ef4-4808-a651-68aee1518472</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
