<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MICR Code_accountNameId_1</name>
   <tag></tag>
   <elementGuidId>8de1996e-1fb9-4f5b-b3a8-c0f45757a97f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='accountNameId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;accountNameId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4c3bb40-72fb-4cb2-b648-3aef9bc9e247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ab2bea7-8a9f-46be-8835-aaefb8cc9a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accountNameId</value>
      <webElementGuid>eb9c0a6a-4f20-44ea-84de-182f18f474e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>579516e5-8436-4d77-b735-0f6fb25fbb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkUniqueAccount(this,'2');</value>
      <webElementGuid>a9fa5cfe-563d-402e-9cf7-6f2951449e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ((event.keyCode>47 &amp;&amp; event.keyCode&lt;58) || (event.keyCode>64 &amp;&amp; event.keyCode&lt;91) || (event.keyCode>96 &amp;&amp; event.keyCode&lt;123) || event.keyCode==45);</value>
      <webElementGuid>6442e555-6592-4249-be2a-38f08058e984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>72c200be-c602-44e6-8df9-23b06fd458ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bankInfo&quot;)/tbody[1]/tr[2]/td[5]/input[1]</value>
      <webElementGuid>c0982e77-594c-4a44-9728-3a9f4765c5ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='accountNameId']</value>
      <webElementGuid>ea4d09fb-65d0-4d88-a83d-52ca5e35f0fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='bankInfo']/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>c5e52167-0a06-4221-9ee7-fa30e0675dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>50eed20b-5b58-48b0-b5ae-6a339324a3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'accountNameId' and @title = '1']</value>
      <webElementGuid>47749b42-3fc2-41bd-ab19-1f9e3995ba0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
