<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MICR Code_accountNameId_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>11145d5f-609f-444c-b5d0-985611d5886a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='accountNameId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;accountNameId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c59b493e-d814-45ef-b568-91a7425e1499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>769d2574-9470-418c-9e45-41c6f4a46550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accountNameId</value>
      <webElementGuid>13795d8f-f13d-48ec-8d9e-ad7b6838173f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>5badaff6-b1a0-4c73-99ba-e582c887cfd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkUniqueAccount(this,'2');</value>
      <webElementGuid>fc645da0-e6e3-479b-9480-bddde88639d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ((event.keyCode>47 &amp;&amp; event.keyCode&lt;58) || (event.keyCode>64 &amp;&amp; event.keyCode&lt;91) || (event.keyCode>96 &amp;&amp; event.keyCode&lt;123) || event.keyCode==45);</value>
      <webElementGuid>6d98bf9f-d52f-46e5-b15f-c16e4122dbb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>12345</value>
      <webElementGuid>7c26386d-ab82-4ba6-83bc-8b22fbb32cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bankInfo&quot;)/tbody[1]/tr[2]/td[5]/input[1]</value>
      <webElementGuid>894db4e1-ee9c-4a76-a2ba-306c162f2be1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='accountNameId']</value>
      <webElementGuid>3ee214f5-5f59-4def-a59b-a1304e7a9472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='bankInfo']/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>629b2bfe-dddb-4574-a52f-e8ddab55ed74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>31a2253d-8540-4776-89e9-9448b8b29938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'accountNameId' and @title = '12345']</value>
      <webElementGuid>a9c52f8e-c092-4b22-9b02-a0bc2eda3a41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
