<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Place of Birth_personalPlaceOfBirth_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>68f4af00-265f-4565-8ded-4b582ad58911</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='personalPlaceOfBirth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;personalPlaceOfBirth&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38f1fc99-ae74-4fa5-b75e-2a7d61d30342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>45ed18c2-a958-4cbe-b003-7d9cc894e45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personalPlaceOfBirth</value>
      <webElementGuid>1acad654-1599-4007-8829-e7508fd1e56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>02da7343-796f-4bb1-8212-ab3b264080fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>SSRN </value>
      <webElementGuid>a375f731-7829-4601-9b6a-e102d7527654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divCustEntityTypeInd&quot;)/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-lg-2 col-md-2 col-sm-3 col-xs-6&quot;]/input[1]</value>
      <webElementGuid>0bf682c1-2535-47c0-9921-6c53f676a364</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='personalPlaceOfBirth']</value>
      <webElementGuid>996ed16c-62c5-4a28-9f98-c53422378abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCustEntityTypeInd']/div/div/div[34]/div[12]/input</value>
      <webElementGuid>16c3e496-0788-4064-aa12-cbc3a518e5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[34]/div[12]/input</value>
      <webElementGuid>161ab4f3-1b27-452e-8633-82b1fbc1c121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'personalPlaceOfBirth' and @title = 'SSRN ']</value>
      <webElementGuid>b1f1443c-6be2-4300-b5ec-9e0319fff734</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
