<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MOBILE NO_selectApplicant</name>
   <tag></tag>
   <elementGuidId>8ea9b5a9-7612-46bd-bd35-6ffc201aaefa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='selectApplicant']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;selectApplicant&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02155d1c-a997-4eec-b8ea-0c67ecfbd232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8bdb0ada-c17a-4930-a3a1-0bd6aca1fc99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectApplicant</value>
      <webElementGuid>43543d97-5fad-40f8-b179-f188576a5f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>CNCIMF000003308</value>
      <webElementGuid>b7499dea-8ff9-4be6-89dd-b3ab7424ff23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selectResult(this.value)</value>
      <webElementGuid>69d1f6c4-2ab5-499b-9c6c-b405d3fc4402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;menuHavingBody&quot;]/form[1]/div[@class=&quot;container-fluid&quot;]/table[1]/tbody[1]/tr[1]/td[2]/div[1]/table[1]/tbody[1]/tr[@class=&quot;tr_list&quot;]/td[@class=&quot;tr_list_alternate&quot;]/input[1]</value>
      <webElementGuid>af88a1f0-2568-4373-a205-7cb61af4c96a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='selectApplicant']</value>
      <webElementGuid>9c8c4a4b-bb52-4eb0-9534-8e166182db82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>b34b3266-14ea-4304-bd13-de634b793a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'selectApplicant']</value>
      <webElementGuid>69ce9272-6ac7-4069-b88d-5565e8150eef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
