<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MICR Code_beneficiaryName_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>edc29a95-9e23-459a-a67a-8261b711b262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='beneficiaryName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;beneficiaryName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f7d5c9e-8355-4bf6-8af5-4a5f5a1e79c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58c0190e-2dd0-4a9e-a905-1e1eee171cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>beneficiaryName</value>
      <webElementGuid>84226c00-c5e6-4e3b-8252-efc0bb7c68bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>5d4fda38-d56b-4294-a5c9-2b150ecd2105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>3606378d-29c1-40b6-adab-3d860c239ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>TESTI</value>
      <webElementGuid>17937d3b-1dfc-4fda-93fc-cb4f3d81b251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bankInfo&quot;)/tbody[1]/tr[2]/td[2]/input[1]</value>
      <webElementGuid>42c752ba-34a1-48ea-8435-dd30b380cefd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='beneficiaryName']</value>
      <webElementGuid>a98ac807-88d6-4d2e-bad3-013b5ed9a6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='bankInfo']/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>54c781d2-a34f-4234-b785-b5342a4ae27b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>315e0c3c-f2fc-4bc4-84f3-82dac07c82b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'beneficiaryName' and @title = 'TESTI']</value>
      <webElementGuid>3d773660-8aa8-4b31-baca-862e7d80c229</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
