<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Approve_arApprove</name>
   <tag></tag>
   <elementGuidId>caaaba22-cc70-4b66-b28a-076e4347cf11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='arApprove']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;arApprove&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad6e2772-0a5e-4718-b9bf-caa47ff6fa5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0b49e04e-8d6a-439c-b88e-196710645698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>arApprove</value>
      <webElementGuid>fc156903-c800-4cfb-b8c2-58a8b97bfb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>A</value>
      <webElementGuid>0fd42bff-0210-4357-9673-317b29066798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:approveRejectToggle(document.forms[0].arApprove.value)</value>
      <webElementGuid>4827a313-b364-4450-8c86-fd6ce511b368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldSetId&quot;)/div[@class=&quot;col-lg-6 col-md-6 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-lg-3 col-md-3 col-sm-3 col-xs-6&quot;]/input[2]</value>
      <webElementGuid>c24fe5ea-d70e-417c-ad2e-e5686e36b196</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='arApprove']</value>
      <webElementGuid>1849cba9-4a4c-4ecc-92b6-e0ca78da0193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fieldSetId']/div[2]/div[2]/input[2]</value>
      <webElementGuid>f7ff19ec-e535-4219-b684-7af61d6aab66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div[2]/input[2]</value>
      <webElementGuid>aef00436-8816-4b61-9b87-750f491632b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'arApprove']</value>
      <webElementGuid>46cf3d56-f2c4-49b5-acc5-8a0de1151c49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
