<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DM Code_dmCode (1)</name>
   <tag></tag>
   <elementGuidId>a21fffa8-f8c6-4a1d-b1eb-50ae3ff6e0a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dmCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dmCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0eac2cb-07df-4dc9-95b7-8aa2320a7a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_header_cost ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>ef6cf7b5-11b4-4936-a84f-1c67c5455c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7ea14685-015b-4c97-b7a2-1da087b6bafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dmCode</value>
      <webElementGuid>377fb086-c3e8-4ef7-b19a-3d0d0f7a0e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>searchData.dmCode</value>
      <webElementGuid>6a2c6097-4600-4869-a3e4-a9400ec5a1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dmCode&quot;)</value>
      <webElementGuid>63d815ac-a0d4-48a2-883e-52d7f6fcccbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dmCode']</value>
      <webElementGuid>84e8f6e4-ab02-4899-accb-4e228e10c27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='dashbord_main']/form/div[5]/div/div/div[12]/input</value>
      <webElementGuid>3fbe6a27-55c7-4c35-983c-787c47849f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/input</value>
      <webElementGuid>30f9291e-ab8e-4a31-a138-9912daf97918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dmCode']</value>
      <webElementGuid>de5306ca-568d-4c68-b60d-76199f7211ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
