<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lease Period(Months)_lease_Period_1_2</name>
   <tag></tag>
   <elementGuidId>be2871f3-3495-435a-bca1-201f7131ec06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lease_Period']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lease_Period</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20b0f8c1-c146-43c1-9691-4f6a82c4c1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_header_cost ng-valid ng-valid-maxlength ng-touched ng-dirty ng-valid-parse</value>
      <webElementGuid>6d8b1bb9-14a7-4875-a24a-885c537e2f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9f1d3ff-1d4e-4119-ad9e-5bb2c40d1a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lease_Period</value>
      <webElementGuid>94a43db3-ed3d-4803-a655-9275fa8c9ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>LEASE_PERIOD</value>
      <webElementGuid>62040d10-1527-4d1e-a178-1341b19e1804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isLeasePeriodDisable</value>
      <webElementGuid>237eaeba-2078-4854-bd2a-dd954d2c1e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return event.charCode >= 48 &amp;&amp; event.charCode &lt;= 57</value>
      <webElementGuid>87840cf7-fb4c-4dd5-a5d8-62ca2fa13b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>76917d95-cd20-47c4-8a73-fd5f537f1993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>CheckLeasePeriod();getFrankingAmount('setZero')</value>
      <webElementGuid>c7bc8611-9555-4dcf-b6de-15c716ab3b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>049044ef-ca33-41f2-8d7a-9050f35863e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lease_Period&quot;)</value>
      <webElementGuid>7ecf5d41-87a6-4e31-aa9c-7001025c7bc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lease_Period']</value>
      <webElementGuid>0973a24d-ad7f-45b7-94b6-fff00e4c9af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='quotationBodyId']/div[7]/div/form/fieldset[2]/div/div[11]/input</value>
      <webElementGuid>fd774696-6c43-47be-89f4-46e2f91e7245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>a8c87ec2-38c7-4eda-93a0-8efb73efee02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lease_Period' and @title = '10']</value>
      <webElementGuid>1a96f698-151a-4061-ab25-164624d77d34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
