<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_National ID_aadhaarNo_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>68503968-d1f1-403f-84bc-fd4b0a6a9fa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='aadhaarNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;aadhaarNo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5053d9a0-4833-49f4-9821-e5ed5f0062ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e632d872-6480-4cc8-9db6-985d96ee725c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aadhaarNo</value>
      <webElementGuid>0443fe70-a50c-4d3c-a217-3d97d50d3a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>50d33acb-9c6f-4034-8029-74cef1174dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>T1234</value>
      <webElementGuid>ac07efe5-2922-4515-8020-3381c692732a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divCustEntityTypeInd&quot;)/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-lg-2 col-md-2 col-sm-3 col-xs-6&quot;]/input[1]</value>
      <webElementGuid>1bf70094-1644-4807-8b06-1aacd2be598a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='aadhaarNo']</value>
      <webElementGuid>039d839a-38f0-403d-9a9e-fd892c1963fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCustEntityTypeInd']/div/div/div[31]/input</value>
      <webElementGuid>44a1f9bf-7933-49fc-8f6d-eeb9170d788b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[31]/input</value>
      <webElementGuid>9ef5e12d-dadb-4fa5-92ba-b12262d59f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'aadhaarNo' and @title = 'T1234']</value>
      <webElementGuid>4afe3b18-739d-4602-be7d-c15eb1da8e89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
