<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MICR Code_accountNameId_1_2_3_4_5_6_7_8</name>
   <tag></tag>
   <elementGuidId>38ef922d-da12-412e-9a23-139703606eee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='accountNameId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;accountNameId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80bc1037-0c26-438a-a11b-fd1138049d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ccec8bd7-0286-43f9-a1dc-688dcb7c57a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accountNameId</value>
      <webElementGuid>e72ed346-76c8-4b1c-8e2f-7bf43bae5c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>fa940fc5-8ccd-4279-b3b6-9007958fb6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkUniqueAccount(this,'2');</value>
      <webElementGuid>ad12791b-4ad3-4ffb-be41-b413bf0aa1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return ((event.keyCode>47 &amp;&amp; event.keyCode&lt;58) || (event.keyCode>64 &amp;&amp; event.keyCode&lt;91) || (event.keyCode>96 &amp;&amp; event.keyCode&lt;123) || event.keyCode==45);</value>
      <webElementGuid>0a414e48-e40b-4a03-9e51-1230f8bd2f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>12345678</value>
      <webElementGuid>4e444990-3480-4dac-98da-43bd1a64fd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bankInfo&quot;)/tbody[1]/tr[2]/td[5]/input[1]</value>
      <webElementGuid>85fab4c4-4eff-4511-84e5-6f20c3d0b6f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='accountNameId']</value>
      <webElementGuid>355db100-c64f-424e-9800-9664d74cde1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='bankInfo']/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>ba8cd133-eaca-442c-a7b9-6345a28cdd93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>c7d6fcdb-b5a2-4f36-848f-6250207d2d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'accountNameId' and @title = '12345678']</value>
      <webElementGuid>43345fd4-adc4-4f6c-a6a9-53287aff44a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
