<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OperationsUser_SCHEDULE_PAYMENT0</name>
   <tag></tag>
   <elementGuidId>6313ba2a-7534-4e58-9607-731fe5264fb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SCHEDULE_PAYMENT0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SCHEDULE_PAYMENT0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7515cdc-3493-4579-bbc0-ec2fa23429ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>424f7598-79d3-4990-84f1-c20c794fa75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SCHEDULE_PAYMENT0</value>
      <webElementGuid>56ea1e7f-1fd4-41d3-8d8a-0526819fe99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>itr_dealerObj.SCHEDULE_PAYMENT</value>
      <webElementGuid>2203cf54-dec0-4fdd-8950-3a029efcc616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>(offlineDtlObj.CAPITALISATION_FLG=='N')?true:false</value>
      <webElementGuid>f8e54433-543b-4218-ba56-3cddbbb1f5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>changePaymentStatus(itr_dealerObj,'sp')</value>
      <webElementGuid>088e2f8a-3bdb-4cdd-a2ac-7d7f7de864bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>3df39307-861e-4d28-99b2-782be8a3302d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SCHEDULE_PAYMENT0&quot;)</value>
      <webElementGuid>ee1e2e59-9712-40d8-9644-ded102e97dde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SCHEDULE_PAYMENT0']</value>
      <webElementGuid>5d98a4d9-f8a4-4224-841c-f658a17a2349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/fieldset[2]/div[2]/div[7]/table/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>65fbcd8b-45de-4c51-9656-4971c5cd6b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>0b37dac1-fdd4-4042-a73c-984e5e0f0d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'SCHEDULE_PAYMENT0']</value>
      <webElementGuid>22ad4642-a9fc-4c62-8efb-d5a52bda4c1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
