<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Designation_designation_1_2</name>
   <tag></tag>
   <elementGuidId>585a0897-a38e-4c9e-a97e-69559f68d5d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;designation&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='designation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be9aa18d-1cf9-4943-8575-85477474f47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa0c6502-6435-49a1-9c1d-1a05af97cbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>designation</value>
      <webElementGuid>babefa0b-3068-41ba-9620-0fbc0a0adfab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>4af4a110-4465-42cd-9d78-e4b08bddd7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;constitutionId&quot;)/div[@class=&quot;col-lg-2 col-md-2 col-sm-3 col-xs-6&quot;]/input[1]</value>
      <webElementGuid>878a4b3d-6ec3-4f09-b994-c79881289ac9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='designation']</value>
      <webElementGuid>f6867446-3ac3-4d07-93bc-e35f9cbe8722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='constitutionId']/div[6]/input</value>
      <webElementGuid>a5a73786-73c3-40de-b074-884e811a7e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>b1e2ed71-a018-45d0-b2a3-6cba63597e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'designation']</value>
      <webElementGuid>055025b3-706b-4630-973b-9c958622a50d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
