<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECTCORPORATESMELARGE CORPORATEINDIVIDUAL</name>
   <tag></tag>
   <elementGuidId>075800a2-ed7c-4d49-a5d3-e368a56c948a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='customerSegment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customerSegment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>26c19390-373e-4c1c-b23c-4db8beaa5c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerSegment</value>
      <webElementGuid>3247c890-9e22-4b71-8def-5643c82ce609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customerSegment</value>
      <webElementGuid>4aabbc1f-620b-42ca-91ab-9aad17574995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>SELECT</value>
      <webElementGuid>e0b2f7d1-f7c1-445a-9a91-28c806913ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
																	SELECT
																	
																		CORPORATE
SME
LARGE CORPORATE
INDIVIDUAL</value>
      <webElementGuid>c2d35bc2-b54a-44d6-ad95-5d7a1f33806d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customerSegment&quot;)</value>
      <webElementGuid>18463406-8667-41ce-8a66-9780e99438be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='customerSegment']</value>
      <webElementGuid>d1dfd3b7-f2cd-40dd-afd1-d080a62a99c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custsegId']/div[5]/select</value>
      <webElementGuid>72d9523c-04a6-47d2-86f1-58c2461d40c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Segment'])[1]/following::select[1]</value>
      <webElementGuid>e0809800-76ad-424a-ac8c-cd3866a1b891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relation'])[1]/following::select[2]</value>
      <webElementGuid>2a7fd019-0bfb-4c28-910e-3e6abefa44a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salutation'])[1]/preceding::select[1]</value>
      <webElementGuid>52c62fa5-41db-42a3-b330-ab48cfefd6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marital Status'])[1]/preceding::select[2]</value>
      <webElementGuid>887efd8a-e5b9-4868-b6c5-a50c8f639448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>d06a1d45-197b-4860-be3c-ae3ffcf437f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'customerSegment' and @id = 'customerSegment' and @title = 'SELECT' and (text() = '
																	SELECT
																	
																		CORPORATE
SME
LARGE CORPORATE
INDIVIDUAL' or . = '
																	SELECT
																	
																		CORPORATE
SME
LARGE CORPORATE
INDIVIDUAL')]</value>
      <webElementGuid>a4caa9b1-1f12-4264-b2d9-38ab64bb07a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
