<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECTCHEQUERTGSBANK TRANSFERCASHDEM_da6496</name>
   <tag></tag>
   <elementGuidId>612f6658-3238-4dfb-b36f-166f31890727</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#INSTRUMENT_TYPE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='INSTRUMENT_TYPE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f9dd7a29-b139-444e-9394-839f2e659d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>INSTRUMENT_TYPE</value>
      <webElementGuid>38cc9d57-c101-48fc-9356-25a7ccdf5248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>offlineDtlObj.INSTRUMENT_TYPE</value>
      <webElementGuid>64fe3e4f-739d-48dd-a991-825b46e9c096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>(user_Type=='MKT'?false:true) || (offlineDtlObj.CAPITALISATION_FLG=='Y'?false:offlineDtlObj.CHK_DRY_CAPITALISE_ACQ==true?true:false )</value>
      <webElementGuid>c16e1238-b677-4ed1-bee9-621c883a1aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>SELECT</value>
      <webElementGuid>58ce4c74-279b-413a-9e30-cb39867e5d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>35142883-9186-471a-aa7e-79a77a33dcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					SELECT
					CHEQUERTGSBANK TRANSFERCASHDEMAND DRAFTOTC-CHQCCDCTPCCTPDCIBMPDF
					</value>
      <webElementGuid>b073384e-741e-4f79-b954-682dd234250b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;INSTRUMENT_TYPE&quot;)</value>
      <webElementGuid>f1ee967b-91a3-4131-a048-c1a3930495f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='INSTRUMENT_TYPE']</value>
      <webElementGuid>fd7668b7-bd36-493f-8931-a297e418c303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/fieldset[2]/div[2]/div[4]/select</value>
      <webElementGuid>71b85699-445c-4b91-ad19-d9331fa68670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instrument Type'])[1]/following::select[1]</value>
      <webElementGuid>7ddcdbee-4227-4c9f-8aea-22b1a4bd1bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dealer Name'])[1]/following::select[2]</value>
      <webElementGuid>54df6603-c554-4b49-92c1-d62b5a09ff1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SCHEDULE PAYMENTS'])[1]/preceding::select[1]</value>
      <webElementGuid>f69d6ab5-ae77-4e92-8b9c-0a0b1cd7d3ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sel'])[1]/preceding::select[1]</value>
      <webElementGuid>f7d02a8c-123f-48d8-a6ca-c801068007eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>8c38da86-10b8-49bd-bc0d-242b4822dd7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'INSTRUMENT_TYPE' and @title = 'SELECT' and (text() = '
					SELECT
					CHEQUERTGSBANK TRANSFERCASHDEMAND DRAFTOTC-CHQCCDCTPCCTPDCIBMPDF
					' or . = '
					SELECT
					CHEQUERTGSBANK TRANSFERCASHDEMAND DRAFTOTC-CHQCCDCTPCCTPDCIBMPDF
					')]</value>
      <webElementGuid>b83bca74-da8a-47ff-8ff5-c82b4fe5ff18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
