<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECTREJECT APPROVE SEND BACK TO PR_0bbc91</name>
   <tag></tag>
   <elementGuidId>002cdba4-4315-43f9-b841-662371f90a1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='actionbycrofficer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#actionbycrofficer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>be455814-68b1-47c4-b823-4652260479be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actionbycrofficer</value>
      <webElementGuid>f4b7c968-4daa-41b9-a7b9-537b00f369f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionbycrofficer</value>
      <webElementGuid>ceb24d37-658e-4528-a7b5-7d893ed4e7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>dis()</value>
      <webElementGuid>b315647e-7c2b-48bd-8814-21c39f742355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>SELECT</value>
      <webElementGuid>008de7f3-5bee-4554-8261-610a76c2717e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELECTREJECT APPROVE SEND BACK TO PREVIOUS LEVEL </value>
      <webElementGuid>f0b42e1b-83bb-4675-aec6-6a3023b315b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionbycrofficer&quot;)</value>
      <webElementGuid>7d986036-a688-4318-86aa-844bc0975472</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='actionbycrofficer']</value>
      <webElementGuid>5b5b945e-6891-408c-8802-288a75561c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='emiinfo']/tbody/tr[3]/td[4]/select</value>
      <webElementGuid>fc593fa5-d3c0-41bc-acb2-85ebea607b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validated By'])[1]/following::select[1]</value>
      <webElementGuid>410310e5-c26d-456e-b391-54e3bc66a188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ok'])[1]/following::select[1]</value>
      <webElementGuid>0315dda2-4890-440e-a8a0-0ddbaa63444d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject Code'])[2]/preceding::select[1]</value>
      <webElementGuid>271f9100-8af2-4d54-a1b3-d9d0d3dec46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decision Date'])[2]/preceding::select[2]</value>
      <webElementGuid>637cc605-aed8-4a20-8b04-f699919720cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/select</value>
      <webElementGuid>1c419716-7a96-40d4-b51c-9d6fc4e29213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'actionbycrofficer' and @id = 'actionbycrofficer' and @title = 'SELECT' and (text() = 'SELECTREJECT APPROVE SEND BACK TO PREVIOUS LEVEL ' or . = 'SELECTREJECT APPROVE SEND BACK TO PREVIOUS LEVEL ')]</value>
      <webElementGuid>e2471e87-f782-4351-a498-67eedd6a023b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
