<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECTEQUIPMENTVEHICLE</name>
   <tag></tag>
   <elementGuidId>78ccd01f-2c19-4466-bb8f-36047878e0ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='assetCategory']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#assetCategory</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4cc9c8a0-f501-42f9-aa71-1f92d16685db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assetCategory</value>
      <webElementGuid>16e5c13f-b520-4e6a-95e7-99e887c235b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>assetCategory</value>
      <webElementGuid>15753345-d77e-4af5-95ee-2857ea75e179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>SELECT</value>
      <webElementGuid>52f647dd-8687-461a-be5d-b916d51c30b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELECTEQUIPMENTVEHICLE</value>
      <webElementGuid>40798d18-fbf5-43b2-8973-8677dcc629dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assetCategory&quot;)</value>
      <webElementGuid>b21e70d8-9810-4590-8e28-f37aae0dc066</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='assetCategory']</value>
      <webElementGuid>ee981a39-6405-4082-bc44-e42f60ec2ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productDetailsDivId']/div[4]/select</value>
      <webElementGuid>d1f1dd76-691f-4203-abcc-f2a2506d9b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Category'])[1]/following::select[1]</value>
      <webElementGuid>4bcaec27-e25a-4d79-b5e0-b3d528009906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Interested In'])[1]/following::select[2]</value>
      <webElementGuid>6aed18bd-9717-41a3-9c1f-0b6498a04eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Competition'])[1]/preceding::select[1]</value>
      <webElementGuid>c49325dc-62f3-4a37-8fe5-02b13f8faf95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Type'])[1]/preceding::select[2]</value>
      <webElementGuid>2e2245eb-a31e-4cc5-aa80-491aa6b92a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div[4]/select</value>
      <webElementGuid>012eae4c-8adb-420e-bfc2-379f24d6d73f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'assetCategory' and @id = 'assetCategory' and @title = 'SELECT' and (text() = 'SELECTEQUIPMENTVEHICLE' or . = 'SELECTEQUIPMENTVEHICLE')]</value>
      <webElementGuid>baa5ad0c-0e02-41f5-934c-1201ee344000</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
