<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Remarks_arRemarks</name>
   <tag></tag>
   <elementGuidId>6bfe1874-976d-44c2-92dd-61100a53e3bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='arRemarksId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#arRemarksId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>58e29a76-8987-4207-896c-9b5f167313a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>arRemarks</value>
      <webElementGuid>332846f1-1fa6-4519-8a41-cfb4b6e5ad3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f8adbec9-2a21-4510-8b3d-e0ff90a675d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e7e1fbd0-dab7-47f0-9347-edc18e221984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkRemark(this,'Author Remark')</value>
      <webElementGuid>43fc6b84-0e32-43d9-94ee-827630f6fcb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arRemarksId</value>
      <webElementGuid>601fa9ce-afba-41cf-b72e-1a299d12682a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arRemarksId&quot;)</value>
      <webElementGuid>f491cdd2-ffbd-49f2-87a8-b5e6b49d872e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='arRemarksId']</value>
      <webElementGuid>a502f065-73ef-49bc-bb75-24aaa85964be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fieldSetId']/div[3]/div/div[2]/textarea</value>
      <webElementGuid>7881b1f9-2a2f-4c62-ba5f-43c6e58d299f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/textarea</value>
      <webElementGuid>8acaaa45-84ad-422a-9f47-6d8d6f28ccd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'arRemarks' and @id = 'arRemarksId']</value>
      <webElementGuid>aae2defc-1971-4390-9564-3e2def7c1393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
