<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MAKER</name>
   <tag></tag>
   <elementGuidId>12c6963e-71a9-47f8-9921-d7151bf70b5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;callLink('1000001046');return blockClick()&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#action1000001046 > div.fgfg.MenuLevel2Parent > div.modules_anchor1.MenuLevel2 > a.menu_L3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d0d592d-5bfb-499f-b226-49d9b3ce4bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu_L3</value>
      <webElementGuid>28b25932-f33a-4e78-b0b1-c9b66ef7ab7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>prospectListFrmNavAction.do?actionPerformed=displayProspectListInfo&amp;screenId=1000001046&amp;screenName=MAKER</value>
      <webElementGuid>ccc2a7fe-16f6-484f-a25f-121d9c86bc6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>callLink('1000001046');return blockClick()</value>
      <webElementGuid>7484dc3f-e54c-4478-8451-613a5c70de4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MAKER</value>
      <webElementGuid>77c16c98-bf9e-44af-bc72-2643ee5e8a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;action1000001046&quot;)/div[@class=&quot;fgfg MenuLevel2Parent&quot;]/div[@class=&quot;modules_anchor1 MenuLevel2&quot;]/a[@class=&quot;menu_L3&quot;]</value>
      <webElementGuid>60721731-7f11-4d95-8aa5-6c6ff67ea412</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;callLink('1000001046');return blockClick()&quot;]</value>
      <webElementGuid>7a594166-ec98-4368-aa97-d8040ef8babd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action1000001046']/div/div/a</value>
      <webElementGuid>e85e5f1c-5dfb-46e2-ad4b-53b8e43f6826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'MAKER')])[14]</value>
      <webElementGuid>ed7a1a45-cc4b-4d1d-8524-966f13006c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESCHEDULING CASE'])[1]/following::a[1]</value>
      <webElementGuid>9d645872-49f1-4570-ad6b-73fa61b391f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GENERATION'])[1]/following::a[2]</value>
      <webElementGuid>c22c492f-5cdd-48a8-b12d-cc1c05dee493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REPORTS'])[1]/preceding::a[1]</value>
      <webElementGuid>660d9f2f-d5e9-4456-ab35-7a2373fbed36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CREDIT OPERATION REPORT'])[1]/preceding::a[2]</value>
      <webElementGuid>511d9e1f-749c-4f60-b93f-bdb432c57cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'prospectListFrmNavAction.do?actionPerformed=displayProspectListInfo&amp;screenId=1000001046&amp;screenName=MAKER')]</value>
      <webElementGuid>900310a8-dea6-4219-9ec9-e84e2a65677f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[121]/div/div/a</value>
      <webElementGuid>9d8eaf56-1ae7-44d9-a4fe-a722fd2027bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'prospectListFrmNavAction.do?actionPerformed=displayProspectListInfo&amp;screenId=1000001046&amp;screenName=MAKER' and (text() = 'MAKER' or . = 'MAKER')]</value>
      <webElementGuid>b73fe4ba-5730-4c25-97b1-02af4b4cd57a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
