<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_CUSTOMER_img1000010288</name>
   <tag></tag>
   <elementGuidId>b1311e2a-2a44-4f6a-9905-179a5876fcfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='img1000010288']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img1000010288</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d231578b-5cab-4e73-98a5-3b91c591f581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img1000010288</value>
      <webElementGuid>3505e102-9806-4e72-be36-dc1076a524a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>c27e6f8f-bc2c-4e51-b6fe-51246f6b79b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5ea9ea84-6fc1-4b41-b08a-6ee796e0cc74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img1000010288&quot;)</value>
      <webElementGuid>4a7208f0-120b-47b7-9664-d1216eb27b38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='img1000010288']</value>
      <webElementGuid>8cabdde6-b76f-43c2-b397-2c265501d847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='imgDiv']/i)[4]</value>
      <webElementGuid>07dd7a72-6ff5-4f45-9260-2d8f937227a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/i</value>
      <webElementGuid>1a6e2c5b-8bf5-43b1-bb7f-413b3ad8cafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'img1000010288']</value>
      <webElementGuid>23ccd11f-93eb-4f43-9063-622eb40ebc7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
