<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECT  AFGHANISTANALBANIAALGERIAAME_60d157</name>
   <tag></tag>
   <elementGuidId>f5b712da-af95-465a-ab90-9b04ce6edd6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#identificationCountryResidence</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='identificationCountryResidence']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7749a355-2091-4e1f-a7ac-8c914e839bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identificationCountryResidence</value>
      <webElementGuid>8b963409-5977-45b4-8a7b-df0e54f0b107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>identificationCountryResidence</value>
      <webElementGuid>1775fb56-4162-45e1-9052-5a07968f8267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELECT
											 
											 AFGHANISTAN
ALBANIA
ALGERIA
AMERICAN SAMOA
ANDORRA
ANGOLA
ANGUILLA
ANTARCTICA
ANTIGUA AND BARBUDA
ARGENTINA
ARMENIA
ARUBA
AUSTRALIA
AUSTRIA
AUTRICIENNE
AZERBAIJAN
BAHAMAS (THE)
BAHRAIN
BANGLADESH
BARBADOS
BELARUS
BELGIAN
BELGIUM
BELIZE
BENIN
BERMUDA
BHUTAN
BOLIVIA (PLURINATIONAL STATE OF)
BONAIRE, SINT EUSTATIUS AND SABA
BOSNIA AND HERZEGOVINA
BOTSWANA
BOUVET ISLAND
BRAZIL
BRITISH INDIAN OCEAN TERRITORY (THE)
BRUNEI DARUSSALAM
BULGARIA
BURKINA FASO
BURUNDI
CABO VERDE
CAMBODIA
CAMEROON
CANADA
CAYMAN ISLANDS (THE)
CENTRAL AFRICAN REPUBLIC (THE)
CHAD
CHILE
CHINA
CHINESE
CHRISTMAS ISLAND
COCOS (KEELING) ISLANDS (THE)
COLOMBIA
COMOROS (THE)
CONGO (THE DEMOCRATIC REPUBLIC OF THE)
CONGO (THE)
COOK ISLANDS (THE)
COSTA RICA
CROATIA
CUBA
CURAï¿½AO
CYPRUS
CZECH
CZECHIA
Cï¿½TE D'IVOIRE
DENMARK
DEUTSCH
DJIBOUTI
DOMINICA
DOMINICAN REPUBLIC (THE)
DUTCH
ECUADOR
EGYPT
EL SALVADOR
ENGLISH
EQUATORIAL GUINEA
ERITREA
ESTONIA
ESWATINI
ETHIOPIA
FALKLAND ISLANDS (THE) [MALVINAS]
FAROE ISLANDS (THE)
FIJI
FINLAND
FRANCE
FRENCH GUIANA
FRENCH POLYNESIA
FRENCH SOUTHERN TERRITORIES (THE)
GABON
GAMBIA (THE)
GEORGIA
GERMANY
GHANA
GIBRALTAR
GREECE
GREENLAND
GRENADA
GUADELOUPE
GUAM
GUATEMALA
GUERNSEY
GUINEA
GUINEA-BISSAU
GUYANA
HAITI
HEARD ISLAND AND MCDONALD ISLANDS
HELVETIC
HOLY SEE (THE)
HONDURAS
HONG KONG
HUNGARY
ICELAND
INDIA
INDONESIA
IRAN (ISLAMIC REPUBLIC OF)
IRAQ
IRELAND
ISLE OF MAN
ISRAEL
ITALY
JAMAICA
JAPAN
JERSEY
JORDAN
KAZAKHSTAN
KENYA
KIRIBATI
KOREA (THE DEMOCRATIC PEOPLE'S REPUBLIC OF)
KOREA (THE REPUBLIC OF)
KUWAIT
KYRGYZSTAN
LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)
LATVIA
LEBANON
LESOTHO
LIBERIA
LIBYA
LIECHTENSTEIN
LITHUANIA
LUXEMBOURG
MACAO
MADAGASCAR
MALAWI
MALAYSIA
MALAYSIAN
MALDIVES
MALI
MALTA
MARSHALL ISLANDS (THE)
MARTINIQUE
MAURITANIA
MAURITIUS
MAYOTTE
MEXICO
MICRONESIA (FEDERATED STATES OF)
MOLDOVA (THE REPUBLIC OF)
MONACO
MONGOLIA
MONTENEGRO
MONTSERRAT
MOROCCO
MOZAMBIQUE
MYANMAR
NAMIBIA
NAURU
NEPAL
NETHERLANDS (THE)
NEW CALEDONIA
NEW ZEALAND
NICARAGUA
NIGER (THE)
NIGERIA
NIUE
NORFOLK ISLAND
NORTHERN MARIANA ISLANDS (THE)
NORWAY
OMAN
PAKISTAN
PALAU
PALESTINE, STATE OF
PANAMA
PAPUA NEW GUINEA
PARAGUAY
PERU
PHILIPPINES (THE)
PITCAIRN
POLAND
PORTUGAL
PUERTO RICO
QATAR
REPUBLIC OF NORTH MACEDONIA
REUNION
ROMANIA
RUSSIA
RUSSIAN FEDERATION (THE)
RWANDA
Rï¿½UNION
SAINT BARTHï¿½LEMY
SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA
SAINT KITTS AND NEVIS
SAINT LUCIA
SAINT MARTIN (FRENCH PART)
SAINT PIERRE AND MIQUELON
SAINT VINCENT AND THE GRENADINES
SAMOA
SAN MARINO
SAO TOME AND PRINCIPE
SAUDI ARABIA
SENEGAL
SERBIA
SEYCHELLES
SIERRA LEONE
SINGAPORE
SINT MAARTEN (DUTCH PART)
SLOVAKIA
SLOVENIA
SOLOMON ISLANDS
SOMALIA
SOUTH AFRICA
SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS
SOUTH SUDAN
SPAIN
SRI LANKA
SUDAN (THE)
SURINAME
SVALBARD AND JAN MAYEN
SWEDEN
SWITZERLAND
SYRIAN ARAB REPUBLIC
TAIWAN (PROVINCE OF CHINA)
TAJIKISTAN
TANZANIA, UNITED REPUBLIC OF
THAILAND
TIMOR-LESTE
TOGO
TOKELAU
TONGA
TRINIDAD AND TOBAGO
TUNISIA
TURKEY
TURKMENISTAN
TURKS AND CAICOS ISLANDS (THE)
TUVALU
UGANDA
UKRAINE
UNITED ARAB EMIRATES (THE)
UNITED KINGDOM
UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)
UNITED STATES MINOR OUTLYING ISLANDS (THE)
UNITED STATES OF AMERICA (THE)
URUGUAY
UZBEKISTAN
VANUATU
VENEZUELA (BOLIVARIAN REPUBLIC OF)
VIET NAM
VIRGIN ISLANDS (BRITISH)
VIRGIN ISLANDS (U.S.)
WALLIS AND FUTUNA
WESTERN SAHARA
YEMEN
ZAMBIA
ZIMBABWE
ï¿½LAND ISLANDS</value>
      <webElementGuid>ea034524-9d64-4e68-b52b-fe0cf0c79117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identificationCountryResidence&quot;)</value>
      <webElementGuid>98d7c1db-b012-4d5d-87ec-7b0e6b61998b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='identificationCountryResidence']</value>
      <webElementGuid>3c42ba5d-ba2a-4e8f-a29a-5aea923bc4ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='identificationId']/div[2]/div[23]/select</value>
      <webElementGuid>7a34b808-562a-46b9-a086-cf170cc4c325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country of Residence'])[1]/following::select[1]</value>
      <webElementGuid>3e73eed6-c26f-4e75-96c5-269f8db784b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Related Party to CFSL'])[1]/following::select[1]</value>
      <webElementGuid>0a4a919f-a516-4c38-9f6e-f28fafd15224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passport Country'])[1]/preceding::select[1]</value>
      <webElementGuid>5651b65c-f34f-4927-b9d8-602255683f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passport Expiry'])[1]/preceding::select[2]</value>
      <webElementGuid>c8779df5-d0b0-4813-96ae-5a07d175dcb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[23]/select</value>
      <webElementGuid>19bf79a0-beb4-44c3-ad86-7bb794c76143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'identificationCountryResidence' and @id = 'identificationCountryResidence' and (text() = concat(&quot;SELECT
											 
											 AFGHANISTAN
ALBANIA
ALGERIA
AMERICAN SAMOA
ANDORRA
ANGOLA
ANGUILLA
ANTARCTICA
ANTIGUA AND BARBUDA
ARGENTINA
ARMENIA
ARUBA
AUSTRALIA
AUSTRIA
AUTRICIENNE
AZERBAIJAN
BAHAMAS (THE)
BAHRAIN
BANGLADESH
BARBADOS
BELARUS
BELGIAN
BELGIUM
BELIZE
BENIN
BERMUDA
BHUTAN
BOLIVIA (PLURINATIONAL STATE OF)
BONAIRE, SINT EUSTATIUS AND SABA
BOSNIA AND HERZEGOVINA
BOTSWANA
BOUVET ISLAND
BRAZIL
BRITISH INDIAN OCEAN TERRITORY (THE)
BRUNEI DARUSSALAM
BULGARIA
BURKINA FASO
BURUNDI
CABO VERDE
CAMBODIA
CAMEROON
CANADA
CAYMAN ISLANDS (THE)
CENTRAL AFRICAN REPUBLIC (THE)
CHAD
CHILE
CHINA
CHINESE
CHRISTMAS ISLAND
COCOS (KEELING) ISLANDS (THE)
COLOMBIA
COMOROS (THE)
CONGO (THE DEMOCRATIC REPUBLIC OF THE)
CONGO (THE)
COOK ISLANDS (THE)
COSTA RICA
CROATIA
CUBA
CURAï¿½AO
CYPRUS
CZECH
CZECHIA
Cï¿½TE D&quot; , &quot;'&quot; , &quot;IVOIRE
DENMARK
DEUTSCH
DJIBOUTI
DOMINICA
DOMINICAN REPUBLIC (THE)
DUTCH
ECUADOR
EGYPT
EL SALVADOR
ENGLISH
EQUATORIAL GUINEA
ERITREA
ESTONIA
ESWATINI
ETHIOPIA
FALKLAND ISLANDS (THE) [MALVINAS]
FAROE ISLANDS (THE)
FIJI
FINLAND
FRANCE
FRENCH GUIANA
FRENCH POLYNESIA
FRENCH SOUTHERN TERRITORIES (THE)
GABON
GAMBIA (THE)
GEORGIA
GERMANY
GHANA
GIBRALTAR
GREECE
GREENLAND
GRENADA
GUADELOUPE
GUAM
GUATEMALA
GUERNSEY
GUINEA
GUINEA-BISSAU
GUYANA
HAITI
HEARD ISLAND AND MCDONALD ISLANDS
HELVETIC
HOLY SEE (THE)
HONDURAS
HONG KONG
HUNGARY
ICELAND
INDIA
INDONESIA
IRAN (ISLAMIC REPUBLIC OF)
IRAQ
IRELAND
ISLE OF MAN
ISRAEL
ITALY
JAMAICA
JAPAN
JERSEY
JORDAN
KAZAKHSTAN
KENYA
KIRIBATI
KOREA (THE DEMOCRATIC PEOPLE&quot; , &quot;'&quot; , &quot;S REPUBLIC OF)
KOREA (THE REPUBLIC OF)
KUWAIT
KYRGYZSTAN
LAO PEOPLE&quot; , &quot;'&quot; , &quot;S DEMOCRATIC REPUBLIC (THE)
LATVIA
LEBANON
LESOTHO
LIBERIA
LIBYA
LIECHTENSTEIN
LITHUANIA
LUXEMBOURG
MACAO
MADAGASCAR
MALAWI
MALAYSIA
MALAYSIAN
MALDIVES
MALI
MALTA
MARSHALL ISLANDS (THE)
MARTINIQUE
MAURITANIA
MAURITIUS
MAYOTTE
MEXICO
MICRONESIA (FEDERATED STATES OF)
MOLDOVA (THE REPUBLIC OF)
MONACO
MONGOLIA
MONTENEGRO
MONTSERRAT
MOROCCO
MOZAMBIQUE
MYANMAR
NAMIBIA
NAURU
NEPAL
NETHERLANDS (THE)
NEW CALEDONIA
NEW ZEALAND
NICARAGUA
NIGER (THE)
NIGERIA
NIUE
NORFOLK ISLAND
NORTHERN MARIANA ISLANDS (THE)
NORWAY
OMAN
PAKISTAN
PALAU
PALESTINE, STATE OF
PANAMA
PAPUA NEW GUINEA
PARAGUAY
PERU
PHILIPPINES (THE)
PITCAIRN
POLAND
PORTUGAL
PUERTO RICO
QATAR
REPUBLIC OF NORTH MACEDONIA
REUNION
ROMANIA
RUSSIA
RUSSIAN FEDERATION (THE)
RWANDA
Rï¿½UNION
SAINT BARTHï¿½LEMY
SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA
SAINT KITTS AND NEVIS
SAINT LUCIA
SAINT MARTIN (FRENCH PART)
SAINT PIERRE AND MIQUELON
SAINT VINCENT AND THE GRENADINES
SAMOA
SAN MARINO
SAO TOME AND PRINCIPE
SAUDI ARABIA
SENEGAL
SERBIA
SEYCHELLES
SIERRA LEONE
SINGAPORE
SINT MAARTEN (DUTCH PART)
SLOVAKIA
SLOVENIA
SOLOMON ISLANDS
SOMALIA
SOUTH AFRICA
SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS
SOUTH SUDAN
SPAIN
SRI LANKA
SUDAN (THE)
SURINAME
SVALBARD AND JAN MAYEN
SWEDEN
SWITZERLAND
SYRIAN ARAB REPUBLIC
TAIWAN (PROVINCE OF CHINA)
TAJIKISTAN
TANZANIA, UNITED REPUBLIC OF
THAILAND
TIMOR-LESTE
TOGO
TOKELAU
TONGA
TRINIDAD AND TOBAGO
TUNISIA
TURKEY
TURKMENISTAN
TURKS AND CAICOS ISLANDS (THE)
TUVALU
UGANDA
UKRAINE
UNITED ARAB EMIRATES (THE)
UNITED KINGDOM
UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)
UNITED STATES MINOR OUTLYING ISLANDS (THE)
UNITED STATES OF AMERICA (THE)
URUGUAY
UZBEKISTAN
VANUATU
VENEZUELA (BOLIVARIAN REPUBLIC OF)
VIET NAM
VIRGIN ISLANDS (BRITISH)
VIRGIN ISLANDS (U.S.)
WALLIS AND FUTUNA
WESTERN SAHARA
YEMEN
ZAMBIA
ZIMBABWE
ï¿½LAND ISLANDS&quot;) or . = concat(&quot;SELECT
											 
											 AFGHANISTAN
ALBANIA
ALGERIA
AMERICAN SAMOA
ANDORRA
ANGOLA
ANGUILLA
ANTARCTICA
ANTIGUA AND BARBUDA
ARGENTINA
ARMENIA
ARUBA
AUSTRALIA
AUSTRIA
AUTRICIENNE
AZERBAIJAN
BAHAMAS (THE)
BAHRAIN
BANGLADESH
BARBADOS
BELARUS
BELGIAN
BELGIUM
BELIZE
BENIN
BERMUDA
BHUTAN
BOLIVIA (PLURINATIONAL STATE OF)
BONAIRE, SINT EUSTATIUS AND SABA
BOSNIA AND HERZEGOVINA
BOTSWANA
BOUVET ISLAND
BRAZIL
BRITISH INDIAN OCEAN TERRITORY (THE)
BRUNEI DARUSSALAM
BULGARIA
BURKINA FASO
BURUNDI
CABO VERDE
CAMBODIA
CAMEROON
CANADA
CAYMAN ISLANDS (THE)
CENTRAL AFRICAN REPUBLIC (THE)
CHAD
CHILE
CHINA
CHINESE
CHRISTMAS ISLAND
COCOS (KEELING) ISLANDS (THE)
COLOMBIA
COMOROS (THE)
CONGO (THE DEMOCRATIC REPUBLIC OF THE)
CONGO (THE)
COOK ISLANDS (THE)
COSTA RICA
CROATIA
CUBA
CURAï¿½AO
CYPRUS
CZECH
CZECHIA
Cï¿½TE D&quot; , &quot;'&quot; , &quot;IVOIRE
DENMARK
DEUTSCH
DJIBOUTI
DOMINICA
DOMINICAN REPUBLIC (THE)
DUTCH
ECUADOR
EGYPT
EL SALVADOR
ENGLISH
EQUATORIAL GUINEA
ERITREA
ESTONIA
ESWATINI
ETHIOPIA
FALKLAND ISLANDS (THE) [MALVINAS]
FAROE ISLANDS (THE)
FIJI
FINLAND
FRANCE
FRENCH GUIANA
FRENCH POLYNESIA
FRENCH SOUTHERN TERRITORIES (THE)
GABON
GAMBIA (THE)
GEORGIA
GERMANY
GHANA
GIBRALTAR
GREECE
GREENLAND
GRENADA
GUADELOUPE
GUAM
GUATEMALA
GUERNSEY
GUINEA
GUINEA-BISSAU
GUYANA
HAITI
HEARD ISLAND AND MCDONALD ISLANDS
HELVETIC
HOLY SEE (THE)
HONDURAS
HONG KONG
HUNGARY
ICELAND
INDIA
INDONESIA
IRAN (ISLAMIC REPUBLIC OF)
IRAQ
IRELAND
ISLE OF MAN
ISRAEL
ITALY
JAMAICA
JAPAN
JERSEY
JORDAN
KAZAKHSTAN
KENYA
KIRIBATI
KOREA (THE DEMOCRATIC PEOPLE&quot; , &quot;'&quot; , &quot;S REPUBLIC OF)
KOREA (THE REPUBLIC OF)
KUWAIT
KYRGYZSTAN
LAO PEOPLE&quot; , &quot;'&quot; , &quot;S DEMOCRATIC REPUBLIC (THE)
LATVIA
LEBANON
LESOTHO
LIBERIA
LIBYA
LIECHTENSTEIN
LITHUANIA
LUXEMBOURG
MACAO
MADAGASCAR
MALAWI
MALAYSIA
MALAYSIAN
MALDIVES
MALI
MALTA
MARSHALL ISLANDS (THE)
MARTINIQUE
MAURITANIA
MAURITIUS
MAYOTTE
MEXICO
MICRONESIA (FEDERATED STATES OF)
MOLDOVA (THE REPUBLIC OF)
MONACO
MONGOLIA
MONTENEGRO
MONTSERRAT
MOROCCO
MOZAMBIQUE
MYANMAR
NAMIBIA
NAURU
NEPAL
NETHERLANDS (THE)
NEW CALEDONIA
NEW ZEALAND
NICARAGUA
NIGER (THE)
NIGERIA
NIUE
NORFOLK ISLAND
NORTHERN MARIANA ISLANDS (THE)
NORWAY
OMAN
PAKISTAN
PALAU
PALESTINE, STATE OF
PANAMA
PAPUA NEW GUINEA
PARAGUAY
PERU
PHILIPPINES (THE)
PITCAIRN
POLAND
PORTUGAL
PUERTO RICO
QATAR
REPUBLIC OF NORTH MACEDONIA
REUNION
ROMANIA
RUSSIA
RUSSIAN FEDERATION (THE)
RWANDA
Rï¿½UNION
SAINT BARTHï¿½LEMY
SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA
SAINT KITTS AND NEVIS
SAINT LUCIA
SAINT MARTIN (FRENCH PART)
SAINT PIERRE AND MIQUELON
SAINT VINCENT AND THE GRENADINES
SAMOA
SAN MARINO
SAO TOME AND PRINCIPE
SAUDI ARABIA
SENEGAL
SERBIA
SEYCHELLES
SIERRA LEONE
SINGAPORE
SINT MAARTEN (DUTCH PART)
SLOVAKIA
SLOVENIA
SOLOMON ISLANDS
SOMALIA
SOUTH AFRICA
SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS
SOUTH SUDAN
SPAIN
SRI LANKA
SUDAN (THE)
SURINAME
SVALBARD AND JAN MAYEN
SWEDEN
SWITZERLAND
SYRIAN ARAB REPUBLIC
TAIWAN (PROVINCE OF CHINA)
TAJIKISTAN
TANZANIA, UNITED REPUBLIC OF
THAILAND
TIMOR-LESTE
TOGO
TOKELAU
TONGA
TRINIDAD AND TOBAGO
TUNISIA
TURKEY
TURKMENISTAN
TURKS AND CAICOS ISLANDS (THE)
TUVALU
UGANDA
UKRAINE
UNITED ARAB EMIRATES (THE)
UNITED KINGDOM
UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)
UNITED STATES MINOR OUTLYING ISLANDS (THE)
UNITED STATES OF AMERICA (THE)
URUGUAY
UZBEKISTAN
VANUATU
VENEZUELA (BOLIVARIAN REPUBLIC OF)
VIET NAM
VIRGIN ISLANDS (BRITISH)
VIRGIN ISLANDS (U.S.)
WALLIS AND FUTUNA
WESTERN SAHARA
YEMEN
ZAMBIA
ZIMBABWE
ï¿½LAND ISLANDS&quot;))]</value>
      <webElementGuid>373edf78-53fc-4752-a282-9ed5c42e5b66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
