<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_CUSTOMER_img1000010289</name>
   <tag></tag>
   <elementGuidId>e0a486c1-53fb-4a64-a523-803860cc7aeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='img1000010289']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img1000010289</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>295dc45c-d832-4e71-b106-5a4aa38a8a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img1000010289</value>
      <webElementGuid>96a69b5a-9d47-4232-b702-ff4727e9576d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>b331d4e1-dbec-42a4-a909-6452b587a199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5964f647-b239-4ccc-843b-0a584764ebb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img1000010289&quot;)</value>
      <webElementGuid>72aaf98e-6982-45ce-aace-416b5657876a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='img1000010289']</value>
      <webElementGuid>317f324e-0f7a-4a16-a368-f9e561618b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='imgDiv']/i)[6]</value>
      <webElementGuid>11e0dd8c-8e7e-4d03-99ab-8f664e4d4ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/i</value>
      <webElementGuid>79718205-c5f1-4cb9-b9ca-7dfcf334ffb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'img1000010289']</value>
      <webElementGuid>9cbc7016-6281-49a7-8a72-8f2966782196</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
