<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MAURITIUS_OK</name>
   <tag></tag>
   <elementGuidId>ef815bbe-c707-4fd5-8245-c988a6abce2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='OK']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;OK&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3ba5c61-b019-41ca-9316-501fc50fbc8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cd5c61eb-8a34-4350-ac55-189dddc9b34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm</value>
      <webElementGuid>c24e806a-f622-474a-9c69-9a1a775ca981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>997bc4b7-9d70-45fc-848b-d55a4f01a9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>f621b58d-73dd-4b5c-825e-cc303823cbb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>submitForm();</value>
      <webElementGuid>7b31b08d-886b-4d79-84f1-b46920d6ca90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LovParent&quot;)/table[2]/tbody[1]/tr[@class=&quot;gray_tr&quot;]/td[1]/input[@class=&quot;btn btn-primary btn-sm&quot;]</value>
      <webElementGuid>cbdcfd16-8be8-4b4e-8821-725d7e65431b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='OK']</value>
      <webElementGuid>2f2d9aac-f293-45d1-a8e1-cf94442f3d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LovParent']/table[2]/tbody/tr/td/input</value>
      <webElementGuid>29247b40-e7d0-48f1-800b-e259d45bcdf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>09986d5d-0234-41ac-86a4-6771d1b0713b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'OK']</value>
      <webElementGuid>9645d5fa-2cad-4edf-bfed-a6a525521118</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
