<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_HIGH_tgl_nbtn</name>
   <tag></tag>
   <elementGuidId>3163e260-7754-459a-9a9a-d54afd055368</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tgl_nbtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fset_one']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ce5fef29-18c1-44af-ad7c-4028ba131b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tgl_nbtn</value>
      <webElementGuid>ce6f8b03-9436-4e09-8523-09ea61fbd326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fset_one&quot;)/div[@class=&quot;tgl_nbtn&quot;]</value>
      <webElementGuid>a91093dc-25c0-47e9-b763-669c40e67837</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fset_one']/div[2]</value>
      <webElementGuid>79de97f5-7e80-41ff-adc2-a928882384a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HIGH'])[1]/following::div[1]</value>
      <webElementGuid>80b768c6-87a7-449d-81a1-b732827782c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KYC RISK CATEGORY'])[1]/following::div[2]</value>
      <webElementGuid>af7db07b-bdec-4c9f-8e0c-bfb5affc8327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UTILITY'])[1]/preceding::div[3]</value>
      <webElementGuid>1acc2d4d-b06b-449a-8edf-67128ed5808c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHANGE PASSWORD'])[1]/preceding::div[6]</value>
      <webElementGuid>e278ba7c-7340-4f89-aa79-4376c3d16abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]</value>
      <webElementGuid>338c02de-3416-49f6-8c57-55bbe9849978</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
