<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Post Sanction</name>
   <tag></tag>
   <elementGuidId>d8dc9f88-5163-4018-82d9-a887945d4559</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='LEASE_DM_POST_SANCTION']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LEASE_DM_POST_SANCTION</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>10ec515f-2850-45eb-a25b-4b05d21e325b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>76ee1b15-0eba-4878-a78f-bbbba9e039af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>switchTabmenu('TABMENU_LEASE_DM_ID','LEASE_DM_POST_SANCTION');</value>
      <webElementGuid>93ff6f36-823d-47dd-b7bb-731138843744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LEASE_DM_POST_SANCTION</value>
      <webElementGuid>6080d286-9451-4caa-8e6f-599fe289f546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>e7fecbff-a827-4844-a3ac-2805481252f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabimenu</value>
      <webElementGuid>f2da8298-2c86-44d4-94e0-a5d810973ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Post Sanction</value>
      <webElementGuid>ccb2516f-6ce5-44c4-8a57-3f12c6ee485e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LEASE_DM_POST_SANCTION&quot;)</value>
      <webElementGuid>6919f410-b23f-4dd1-8e4e-3b9ba69ec0c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='LEASE_DM_POST_SANCTION']</value>
      <webElementGuid>eef09b0e-1d57-4d8d-b9ce-f080f5b1992c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TABMENU_LEASE_DM_ID']/a[2]</value>
      <webElementGuid>dd479591-9e53-4d2f-b879-06819c15145b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Post Sanction')])[2]</value>
      <webElementGuid>c537fa7f-34cf-46b6-abb4-3fe77697ea11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LEASE DM'])[1]/following::a[5]</value>
      <webElementGuid>a60ffeeb-1e63-453b-8b04-c6a5c8d56068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUOTATION'])[5]/following::a[6]</value>
      <webElementGuid>fefb746e-36a0-43af-bad1-a3b2c7a83bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Del'])[1]/preceding::a[2]</value>
      <webElementGuid>c337e89d-cec3-4893-bf25-189de14c5de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update'])[1]/preceding::a[2]</value>
      <webElementGuid>754c19dc-b7c6-498b-976a-2ae9c3aed5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[16]</value>
      <webElementGuid>279e89aa-22c0-4c90-abaf-b5021675a511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a[2]</value>
      <webElementGuid>8772c90b-ba71-4dbb-a0f6-7bf7f99168ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'LEASE_DM_POST_SANCTION' and @href = '#' and (text() = 'Post Sanction' or . = 'Post Sanction')]</value>
      <webElementGuid>cd28e8d6-ead7-4888-b15f-c1e3ed19dacf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
