<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pre Sanction</name>
   <tag></tag>
   <elementGuidId>016eac75-3904-44fe-8585-b337d5c1e902</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='LEASE_DM_PRE_SANCTION']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LEASE_DM_PRE_SANCTION</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c2dc859a-44c7-4e86-8ebe-fbcf112aaba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>1accb95f-3dc0-4127-9ea9-6908b2dd3651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>switchTabmenu('TABMENU_LEASE_DM_ID','LEASE_DM_PRE_SANCTION');</value>
      <webElementGuid>118d1d56-d4d3-458d-826d-dfd387cba89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LEASE_DM_PRE_SANCTION</value>
      <webElementGuid>81a8c4c1-3a04-4e02-af7d-41cc53baeff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabimenu</value>
      <webElementGuid>14ea3369-574e-4ca0-afb0-a4cfa20644a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>65cc3e14-48de-4b75-a166-b19b147f4d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pre Sanction</value>
      <webElementGuid>14988b8f-5de7-4546-891f-2cdb72d3cfae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LEASE_DM_PRE_SANCTION&quot;)</value>
      <webElementGuid>d7199812-e59e-496a-89b5-e621533d94be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='LEASE_DM_PRE_SANCTION']</value>
      <webElementGuid>38512adf-69a2-4ca3-8d4a-7bf11feefcf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TABMENU_LEASE_DM_ID']/a</value>
      <webElementGuid>014fff4d-8782-4916-9943-1099e4b619d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Pre Sanction')])[2]</value>
      <webElementGuid>aaca95eb-d0cb-40d1-9e14-e0edc3ad56d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LEASE DM'])[1]/following::a[4]</value>
      <webElementGuid>344f0842-f844-46c3-985c-c74dac4a16ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUOTATION'])[5]/following::a[5]</value>
      <webElementGuid>f9749c7e-0fbd-427b-aa37-9ab8ccadcb90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Del'])[1]/preceding::a[3]</value>
      <webElementGuid>d26d84be-1bb1-497d-9f71-6cffd909ad28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update'])[1]/preceding::a[3]</value>
      <webElementGuid>dfcc89c8-4fa6-44ea-8ce6-38f45aa1640f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[15]</value>
      <webElementGuid>3209ba07-7696-48c1-9bdb-7895d38f5cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div[2]/a</value>
      <webElementGuid>cc690154-ff87-4269-bfda-8182e74db0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'LEASE_DM_PRE_SANCTION' and @href = '#' and (text() = 'Pre Sanction' or . = 'Pre Sanction')]</value>
      <webElementGuid>1f0674df-9003-461b-98e3-509a053a6b9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
