<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SYSUSER_file(4)</name>
   <tag></tag>
   <elementGuidId>a89c08e7-15e8-42a4-9dac-c87e95bc2f24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FILENAME6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FILENAME4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55681160-a860-47f7-88cd-53bc80a7504b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>ec8aa577-1ceb-4ca0-b653-c20e252f278f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FILENAME6</value>
      <webElementGuid>eb187d04-2494-4316-8133-4f7f6a8aacf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>2a7dedeb-848f-4ae7-82bb-d3938b00ed08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>docDetail.FILENAME</value>
      <webElementGuid>a30e824a-e447-413e-b713-18e5e9a1b1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>docDetail.DOCCOLLECTIONSTATUSID=='1000000001'?false:true</value>
      <webElementGuid>abdff679-4d54-4d2a-a3d9-29ae7c894ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>b9b5335b-fc26-45b9-8ea7-ba275c52a765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FILENAME6&quot;)</value>
      <webElementGuid>7d540cf4-49b4-43f3-a16a-72295cb65eda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FILENAME4']</value>
      <webElementGuid>d2ca5ffa-04e0-4886-9785-18cb0f6cd74f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='documentTable']/tbody/tr[8]/td[8]/input</value>
      <webElementGuid>0069c287-22ea-4eb8-bc53-0f230b212b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[8]/input</value>
      <webElementGuid>8e4627b9-b42c-485b-a0c7-46e2eed669db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'FILENAME6' and @name = 'file']</value>
      <webElementGuid>5063d702-2969-4744-bb0e-8036797e116f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
