<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Updated Date_file</name>
   <tag></tag>
   <elementGuidId>e449040a-8cf2-48c5-a3c4-2c0b67180e5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FILENAME0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FILENAME0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cec63bf8-5d44-43f3-9997-a3b0946d19e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>d30feb9a-9866-4301-b5f5-3fc5f76f9bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FILENAME0</value>
      <webElementGuid>d5af0fdc-5d9b-4202-ae9c-b1ae3a567986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>cb00b325-7c73-4798-9e85-bc23b324a373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>docDetail.FILENAME</value>
      <webElementGuid>dd3759c6-dab9-4ca6-857c-ab5b56c2ff58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>docDetail.DOCCOLLECTIONSTATUSID=='1000000001'?false:true</value>
      <webElementGuid>3126c2f6-b6b9-44d9-be94-fe065fba3756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-touched</value>
      <webElementGuid>30f666c2-68bd-42ba-bc71-930569152a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FILENAME0&quot;)</value>
      <webElementGuid>f904839e-5ec5-4fb8-a552-a5f788b9ca80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FILENAME0']</value>
      <webElementGuid>d5c51fe4-841c-4835-bc94-d1d87b5d253a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='documentTable']/tbody/tr[2]/td[8]/input</value>
      <webElementGuid>cea52f94-ca8e-467b-8bdb-b6a1827bd554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/input</value>
      <webElementGuid>f268c83f-eac9-4e4a-b84e-2f0b310bb8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'FILENAME0' and @name = 'file']</value>
      <webElementGuid>2bd4a157-58bd-42ad-a4d5-f5aa9aba8df5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
