<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_LEASE RESIDUAL VALUE UPLOAD_img1100010049</name>
   <tag></tag>
   <elementGuidId>f2126a58-9c5e-4231-8d4f-74b4a2800b89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img1100010049</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='img1100010049']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9ec3da19-c0b9-4d00-ac4b-20c5db1e964b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img1100010049</value>
      <webElementGuid>979c2c0b-ffd8-45a0-9c54-1fd0d5c466f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>0a8589e8-d635-40d4-81f0-a72ee257216f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6e596ccb-a743-4a79-8448-8b234a1a5664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img1100010049&quot;)</value>
      <webElementGuid>ac6f3168-87f3-4d3d-a774-754e936ab0f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='img1100010049']</value>
      <webElementGuid>af892aae-3b08-43b2-b31f-a3d20b8b78be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='imgDiv']/i)[56]</value>
      <webElementGuid>08f0bb7a-a42f-447b-a333-e3847eb45fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[469]/div/div/i</value>
      <webElementGuid>19a43d79-2295-43e7-9db6-1e714b8c0503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'img1100010049']</value>
      <webElementGuid>79860816-c847-4c17-88f8-5bd178b7637f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
