<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DMFIN1000008514</name>
   <tag></tag>
   <elementGuidId>38b712ce-6af0-4502-8727-fb5497ba0e49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='existingTable']/tbody/tr/td[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a9542efc-a01d-4b93-a5b4-58fd4fc7448c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>1a86d00f-17fb-4ee9-86ae-45063a0167b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>showDetail(quotation.DM_ID,quotation.DM_CODE,quotation.ASSET_FROM,quotation.LIMIT_EDIT_FLAG)</value>
      <webElementGuid>4d2283c7-a2a6-4653-8a36-1f234d6cdad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>6c8a26ce-3204-47b8-94d1-4f2e23a0ebe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c5c7156f-ab7f-4123-bc9a-28269f453e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DMFIN1000008514 </value>
      <webElementGuid>5d463805-7cc0-41c4-aea8-3467ec9f2a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;existingTable&quot;)/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[5]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>11e49f3c-2c18-4ac6-851a-6bc851dcf54d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='existingTable']/tbody/tr/td[5]/a</value>
      <webElementGuid>c3294558-5469-423c-b5fc-ee7467091ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DMFIN1000008514')]</value>
      <webElementGuid>65ff2bcd-fd3e-4d69-bf2b-42477317da80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QU00023281'])[1]/following::a[1]</value>
      <webElementGuid>1b69fd2c-852e-4f11-a91d-28638be1fc63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN00023280'])[1]/following::a[1]</value>
      <webElementGuid>0a768984-ac19-4d61-99c8-8fc66b63349a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAQATEST CTESLAV'])[1]/preceding::a[1]</value>
      <webElementGuid>25e8e5bf-743b-44fa-ac2b-64326b565bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNCIMF000003874'])[1]/preceding::a[1]</value>
      <webElementGuid>94056f60-2d9b-4414-a0e6-7f51b5199990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DMFIN1000008514']/parent::*</value>
      <webElementGuid>4a009cbd-b459-4a76-9328-87a3192b54e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>cae775dd-4298-4f42-ace6-514b82ccd3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>0033eb46-7a13-4663-9fcb-60a909f0ff6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'DMFIN1000008514 ' or . = 'DMFIN1000008514 ')]</value>
      <webElementGuid>b3c424de-1750-4b4c-87bb-f18d4b59a89d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
