<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regression_Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>be73f6a0-b22e-43b2-b221-3e01adc8a51c</testSuiteGuid>
   <testCaseLink>
      <guid>b9e8b8b0-9424-453d-ad90-8da0d6af3a3b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Customer creation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54cb314a-6003-4752-a204-e21c43acc3b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17db29b5-8aaa-471f-aa8c-5b1294384b81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a03386a6-b0b9-4680-a1f9-2cfe94b86868</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cca82043-1c68-4833-92ae-e9d86984eaca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72132da1-02c8-4740-b0e4-5507c1d00d92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10d83f2f-560b-456e-ba3a-0cabbad6533a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2aad6ca7-35f8-4bda-8b06-1e1df54edb08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c1c2118-b6b0-488b-97aa-594bfe3e4ccc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>337977bd-c9b5-4ddb-a2ef-0ad935cefb76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d06cc18-8e2a-4a45-9a39-70456c5572b4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5f9a5e8b-88af-48ee-833a-b1dfeb5fd04b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/New_Cust_approval</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>faa9da51-cef7-4e5a-aef7-8a586e13dfa1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b48685fc-ed2f-41ca-aa59-5cd8aba7ba37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb4a0ec7-9c64-4e1a-b111-c53d577771a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7526db86-e454-4f0f-8198-60bdd76cc404</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/New Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9b42913-00a0-45b8-9190-1286432577b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b83d8554-644c-46a9-aec5-5a186a3f3052</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f065981-cfec-4d4c-8924-ca06f614485e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8a91c19-dcef-4db2-b7bd-222fcd3b5341</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Customer limit creation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8135b0d6-287e-4f7d-ad90-3667777f0d0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7e07c06-19c6-4f61-ad2c-9f92e770232c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5801a298-a77c-4e6b-9610-71b7dab6c31a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5cc0ce33-0382-4965-ac9c-a02080105477</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/New Quotation - Acceptance</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba6ef40a-4802-4d67-b4f1-9a5ee0a5490c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2fb8f70-2f42-4a0b-9671-c58c7b3540d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>89afa0ba-d93e-48c2-9db0-c3f9efe5d9c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/DM Creation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a63c94b3-4269-44fe-bfed-3461d8dbdf5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddd915ea-727a-43e7-9d8b-b1c0d3a73bdd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d97adcd6-f0a4-457a-a32b-e66605f36bbd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>25aa2684-83d4-4b18-9d03-a666f2ecabe1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/DM_Approval</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7036656-6ae1-42f6-b994-1e99c11752f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>761c1ab5-473c-462c-8cd7-43f955ef0f72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Post_Sanction_Documents</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53d5283e-87a4-4ad1-ac9f-63c7b3c02e7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f64141c-68ab-4b5b-9c35-6efdd577b6f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17bbf1c6-4838-4504-89b9-a8d4464958e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45eadd37-6cb1-4bdf-a43b-497845074357</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67765ae0-7179-4015-9b69-5e9bda54030b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Receipt creation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a498de17-94d8-467e-a885-a9df7ca14a45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3f85278-ed6c-4b9a-98c9-4b41b16ead02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1aac7426-4935-4111-9624-68499cbd1c3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1544a7e2-8290-45a7-b756-e7ddeca0872b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b986b0e-38bd-4315-b686-9aeba7c4e8cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/receipt approval</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3b6b1ae-5ee5-4599-8e1e-463ca0ef8b91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>abadcc67-cde7-4fb9-8609-498e8984e864</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Captalization_maker_Author</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85e94811-c82c-4637-8c77-b7e692cfa57c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d089f533-8f7c-4191-a7b9-758ddf782de7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Payment_Schedule_Maker_Author</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4eb30119-578d-4f2f-b81c-dcda7fbfa35f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>141b59d0-853a-41f6-8e28-32759361244f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Post_Disbursal_Document</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b20a1f2-f13f-40ac-87a4-1b8cd96b421c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e87253c-6b8a-4fb5-a45f-0d2822691d3d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ae9c6f2-b95d-479d-b8bb-509eebd48612</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/ManualAdvice_maker_Author</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>def5aa43-8586-45a2-956c-0a09c2372e99</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b45eb53c-8470-41d6-bb27-18931410dd44</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/KnockOff_Maker_Author</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4d9f58e-2dab-40e1-89d3-ee69b89d5ce1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8492d36f-c762-48cb-a964-d4660eb30f43</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Waive off</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62de8551-62eb-40ac-a4f2-6547a2ffbb17</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df684f23-0072-4ac6-b1f0-2e9aeb7ce41e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Rescheduling_Maker_Author</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e3074d4-1228-42bb-98cd-b84a3efff768</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b99e0efc-e9a2-4359-9740-b649dfe464cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/DM_PDE_Checks</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f00a3cb8-46b7-41ca-beda-bee5b2df6076</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dd6f6ce6-f579-44da-ba7a-1bca1a45f4cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/EOD</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c32f114d-38e7-4ebc-ab23-09e30866321e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CIM_FINANCE/Foreclosure_Maker_Author</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b48142d5-cd81-40dd-92ff-63b4ee0fb887</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
