<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DM QUOTATION</name>
   <tag></tag>
   <elementGuidId>5ffc4024-bf86-4c50-bac9-df7e2ea5bd8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#action1200004000 > div.fgfg.MenuLevel0Parent > div.modules_anchor1.MenuLevel0 > a.modules_anchor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;callLink('1200004000')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>64210909-1168-4c46-bca4-f23955cdfb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modules_anchor</value>
      <webElementGuid>0e15beb4-b8b0-4eda-b505-0684d22cc4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>callLink('1200004000')</value>
      <webElementGuid>ffd6306a-0b3b-408c-b43a-3086c0ea25cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DM QUOTATION</value>
      <webElementGuid>366f63aa-250c-4836-9920-e8748a682f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;action1200004000&quot;)/div[@class=&quot;fgfg MenuLevel0Parent&quot;]/div[@class=&quot;modules_anchor1 MenuLevel0&quot;]/a[@class=&quot;modules_anchor&quot;]</value>
      <webElementGuid>e3c15911-300a-4a0a-89a2-75eb76b3d3ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;callLink('1200004000')&quot;]</value>
      <webElementGuid>e6bfa793-4dd6-4feb-aa7c-002bed80ca03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action1200004000']/div/div[2]/a</value>
      <webElementGuid>e262d189-ea1f-48b8-9c75-f00b533b6383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DM QUOTATION')]</value>
      <webElementGuid>06678dc0-c924-48cd-b4c4-a1564c4e8108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEWER'])[1]/following::a[1]</value>
      <webElementGuid>d067f0db-c4f2-4b7b-ae49-d3b33e956176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACQUISITION'])[1]/following::a[2]</value>
      <webElementGuid>adc73233-68fd-4545-8218-3e4b1eff1d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW'])[4]/preceding::a[1]</value>
      <webElementGuid>a84a2013-4e7b-47be-a50a-6ff438e6f80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DM APPLICATION'])[1]/preceding::a[2]</value>
      <webElementGuid>ac048cbd-b694-42b2-92d6-be8afe332e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DM QUOTATION']/parent::*</value>
      <webElementGuid>b2b5ad93-7b7f-4067-9914-bca03d258d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[52]/div/div[2]/a</value>
      <webElementGuid>bb1effab-939b-4b58-8255-6aec1da75bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'DM QUOTATION' or . = 'DM QUOTATION')]</value>
      <webElementGuid>23dc360c-0771-4ba8-b9d4-d704b0c72d9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
