<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CASHFLOW</name>
   <tag></tag>
   <elementGuidId>6af7779c-b4bc-46db-84ab-d2f410a84b18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'CASHFLOW')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#action1200004008 > div.fgfg.MenuLevel2Parent > div.modules_anchor1.MenuLevel2 > a.menu_L3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6f1ef2e4-7866-4738-990c-26eab5bdf868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu_L3</value>
      <webElementGuid>40eec5fe-2822-4bdf-bd0f-74f59dac8a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>dmProspectList.sprg?screenId=1200004008&amp;screenName=CASHFLOW</value>
      <webElementGuid>aed4bdeb-0994-4b6e-82b3-e5bec949e908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>callLink('1200004008');return blockClick()</value>
      <webElementGuid>4cb7150d-2d20-43d2-96a3-4ca94f6bb5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CASHFLOW</value>
      <webElementGuid>d95b71f6-8bf8-4725-ba4d-93c05a80e0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;action1200004008&quot;)/div[@class=&quot;fgfg MenuLevel2Parent&quot;]/div[@class=&quot;modules_anchor1 MenuLevel2&quot;]/a[@class=&quot;menu_L3&quot;]</value>
      <webElementGuid>65175e48-6e53-4550-99aa-8bb57d04f6fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;callLink('1200004008');return blockClick()&quot;]</value>
      <webElementGuid>31422d96-48ed-4cb6-9882-c693dd2c1d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action1200004008']/div/div/a</value>
      <webElementGuid>e7b0655f-f1f5-4047-8e32-89f7b6d1a08c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'CASHFLOW')])[2]</value>
      <webElementGuid>ac4878a1-4d01-46d4-ab8a-d8e3790090c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUOTATION'])[3]/following::a[1]</value>
      <webElementGuid>9568de1d-2365-418b-beba-377d713b662e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASSET DETAILS'])[2]/following::a[2]</value>
      <webElementGuid>9a7836fa-d9db-4d74-8139-5a9eb7d951c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DM OFFLINE ACTION'])[1]/preceding::a[1]</value>
      <webElementGuid>ebbc6e54-6ff4-4b66-8b75-2f90bff827f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DM SANCTION'])[1]/preceding::a[2]</value>
      <webElementGuid>01495a04-c519-44d7-96e5-9e63ca3ebff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'dmProspectList.sprg?screenId=1200004008&amp;screenName=CASHFLOW')]</value>
      <webElementGuid>3b199dd9-3e46-4e57-b329-057bbe6d9730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[59]/div/div/a</value>
      <webElementGuid>1692f858-4863-42b3-9e8b-9d74cc48c595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'dmProspectList.sprg?screenId=1200004008&amp;screenName=CASHFLOW' and (text() = 'CASHFLOW' or . = 'CASHFLOW')]</value>
      <webElementGuid>60e6aea6-a817-44fd-b0bf-677fbfda5ba9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
