<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_DM APPLICATION_img1200004003</name>
   <tag></tag>
   <elementGuidId>e6a14102-fede-4165-a3c1-097d3161be23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img1200004003</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='img1200004003']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f8ffbfe5-c164-4632-8739-af4406b0e430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img1200004003</value>
      <webElementGuid>de7dff55-0624-45ae-b2f5-6dceb431e9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>b00a0450-6390-489f-bf04-020d5a2c8e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6b8fd7b1-0697-45cd-826c-2c8d0c468110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img1200004003&quot;)</value>
      <webElementGuid>414ad464-abc9-4bb3-bac7-a5d3bfa18663</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='img1200004003']</value>
      <webElementGuid>2d72e206-f3c8-4b3f-babd-664aa0c3b81b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='imgDiv']/i)[16]</value>
      <webElementGuid>032b1ab3-09da-4b99-a2e1-a1eec106fc45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[56]/div/div/i</value>
      <webElementGuid>4b7cd76a-836e-4b76-ad46-e44bc4ed990c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'img1200004003']</value>
      <webElementGuid>acc694a4-d00a-4719-84e2-d72d4afdfef2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
