<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>e0bab2a1-76db-4ee8-ad89-993dd7449434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cpMonthNavigation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'&lt;')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>674df854-4bec-4bf1-b7d5-2c8fa761589f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cpMonthNavigation</value>
      <webElementGuid>64a81986-1608-428c-8fd7-2489b2943713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:window.opener.CP_refreshCalendar(0,9,2023);</value>
      <webElementGuid>14dcf225-942d-4fc1-995d-abe786b4b325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;</value>
      <webElementGuid>8fbbbeb2-44f6-4e7b-ab80-16cb23a5717d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/center[1]/table[1]/tbody[1]/tr[1]/td[@class=&quot;cpMonthNavigation&quot;]/a[@class=&quot;cpMonthNavigation&quot;]</value>
      <webElementGuid>1b044857-e583-4769-af5d-1ef7e6a88ac2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'&lt;')]</value>
      <webElementGuid>f3c1dedf-1f2d-40c9-a4f2-89e765a0d0ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='October'])[1]/preceding::a[1]</value>
      <webElementGuid>cec6cfa7-97c6-450c-8490-afd3dac8eb41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[1]/preceding::a[1]</value>
      <webElementGuid>f3dc9706-9b52-4ade-a0de-9537e8dac12d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt;']/parent::*</value>
      <webElementGuid>1f763df7-c422-4863-8fa0-b0c603af53d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:window.opener.CP_refreshCalendar(0,9,2023);')]</value>
      <webElementGuid>4304a54c-ab8c-4b3a-af38-8306a5d7479a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>25987346-e5b3-4c11-b7f4-d227ba162c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:window.opener.CP_refreshCalendar(0,9,2023);' and (text() = '&lt;' or . = '&lt;')]</value>
      <webElementGuid>d55f52bd-4166-4770-955a-b02d924eaa22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
