<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ACCEPTANCE</name>
   <tag></tag>
   <elementGuidId>cff9afbe-0d07-49ed-9569-cad25e5c1d11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div/div[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>09056eb2-2a61-4b02-9f1b-bcb89fe51c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>acceptanceDetails.sprg?&amp;screenId=1200003016&amp;mode=E&amp;screenName=ACCEPTANCE</value>
      <webElementGuid>c8d8567c-6bce-4077-968f-58dabf10d992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noLine</value>
      <webElementGuid>a461f0f2-0100-4f5e-a98e-98c47832f899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACCEPTANCE</value>
      <webElementGuid>6015b7bd-45a7-45bc-9fe7-d0b57cd4a2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;menu col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[7]/a[@class=&quot;noLine&quot;]</value>
      <webElementGuid>80a1e6f0-b893-4068-9266-7716862b2bcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div/div[7]/a</value>
      <webElementGuid>108a0473-f124-4aa5-b2f9-4a83b2518cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'ACCEPTANCE')])[2]</value>
      <webElementGuid>58441216-ea19-4c72-be61-30624474ca11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGISTRATION DETAILS'])[3]/following::a[1]</value>
      <webElementGuid>08fd1377-1b04-4808-8b52-7ec5dd6cd52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASHFLOW'])[3]/following::a[2]</value>
      <webElementGuid>a7c930db-b331-4a49-a1f7-beb736019bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACQUISITION'])[2]/preceding::a[1]</value>
      <webElementGuid>0ce2974b-e164-4a34-b7b4-aa675944fb0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTEPAD'])[2]/preceding::a[2]</value>
      <webElementGuid>d38370df-aded-450d-80be-38e41a612cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'acceptanceDetails.sprg?&amp;screenId=1200003016&amp;mode=E&amp;screenName=ACCEPTANCE')]</value>
      <webElementGuid>09ef34be-855d-4980-837e-ce3376677734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/a</value>
      <webElementGuid>baec6004-1cc6-46cd-b6b0-dd2afe030c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'acceptanceDetails.sprg?&amp;screenId=1200003016&amp;mode=E&amp;screenName=ACCEPTANCE' and (text() = 'ACCEPTANCE' or . = 'ACCEPTANCE')]</value>
      <webElementGuid>dee3bee2-ed66-4c26-b012-5255d7d6f6b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
