<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CAPITALISATION  MAKER</name>
   <tag></tag>
   <elementGuidId>1f6aa5db-82ae-44ad-b599-cedf9ada03e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div/div[13]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fbd398d2-9d92-42ff-b55c-805c3f05fdee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>disbursalFrmNav.do?actionPerformed=displayDMDisbursalInfo&amp;screenId=1200004017&amp;mode=E&amp;screenName=CAPITALISATION</value>
      <webElementGuid>17067bea-9179-4460-aa85-3745417fc516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noLine</value>
      <webElementGuid>65c07b8e-cf81-44ea-b669-866c378408ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CAPITALISATION  MAKER</value>
      <webElementGuid>b4bf0976-fcbe-4706-90ee-638593d1120d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;menu col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[13]/a[@class=&quot;noLine&quot;]</value>
      <webElementGuid>93938874-ba61-44ba-86af-6ccd901f23d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div/div[13]/a</value>
      <webElementGuid>cee7d21f-5895-4707-a83e-348b04cf2fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'CAPITALISATION  MAKER')])[2]</value>
      <webElementGuid>13aea234-46bd-474c-823e-f00e21602121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DM OFFLINE ACTION'])[3]/following::a[1]</value>
      <webElementGuid>d6ec5346-98fa-4621-b917-e9834e37b418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOCUMENT'])[2]/following::a[2]</value>
      <webElementGuid>6d3993b0-d2ce-4cfa-ae01-fa88e255465c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROSPECT NO'])[1]/preceding::a[1]</value>
      <webElementGuid>8e4a4607-d1c1-4da9-afb2-94385b60b4ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DMFIN1000008259'])[1]/preceding::a[1]</value>
      <webElementGuid>f06ef2c5-0d5d-42c4-9775-f336222052f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'disbursalFrmNav.do?actionPerformed=displayDMDisbursalInfo&amp;screenId=1200004017&amp;mode=E&amp;screenName=CAPITALISATION')]</value>
      <webElementGuid>ffdc6eb5-5da6-4a58-87c3-f631016763c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/a</value>
      <webElementGuid>45e34e17-1da3-461b-bb5d-4a81a99dd2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'disbursalFrmNav.do?actionPerformed=displayDMDisbursalInfo&amp;screenId=1200004017&amp;mode=E&amp;screenName=CAPITALISATION' and (text() = 'CAPITALISATION  MAKER' or . = 'CAPITALISATION  MAKER')]</value>
      <webElementGuid>7c39a3e2-dc1f-4d65-a7b7-36273d6d50ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
