<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DMFIN1000008259_1 (1)</name>
   <tag></tag>
   <elementGuidId>9d62ea99-dfd0-4294-979c-aa65d8cc91ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='allProspectEntries']/table/tbody/tr/td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a1244901-86a6-48e8-8d55-e227e74d4c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:showDetail('DMFIN1000008259','','1000038416','1000008259','1000000008')</value>
      <webElementGuid>1ba506dc-5b62-406d-91ae-8313f19f5f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DMFIN1000008259 </value>
      <webElementGuid>5c1af4ba-ea4d-4d3d-8333-6edffbb7200e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allProspectEntries&quot;)/table[@class=&quot;tr_list&quot;]/tbody[1]/tr[@class=&quot;tr_list&quot;]/td[3]/a[1]</value>
      <webElementGuid>c0a8b1bf-0927-4384-af6d-9e2867fbc8ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allProspectEntries']/table/tbody/tr/td[3]/a</value>
      <webElementGuid>5538dda6-a4b4-42b9-b3d8-22d40ff1e5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DMFIN1000008259')]</value>
      <webElementGuid>cdd86f68-c27b-49bb-8b87-0d1f70772049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ONLY FIXED FINANCE LEASE'])[2]/following::a[1]</value>
      <webElementGuid>49ce2310-4337-4d1f-aa06-1bb7f76e72cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNCIMF000003205'])[1]/preceding::a[1]</value>
      <webElementGuid>13adbdb5-caa4-459d-a730-065919d45108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DMFIN1000008259']/parent::*</value>
      <webElementGuid>ba2d47a4-aa94-4009-9ddc-3a7a72516c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:showDetail('DMFIN1000008259','','1000038416','1000008259','1000000008')&quot;)]</value>
      <webElementGuid>f53c8a73-d415-4e1c-8e16-8fed9f40f7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>d5bd902e-e734-488a-8c8d-c7d4be330089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:showDetail(&quot; , &quot;'&quot; , &quot;DMFIN1000008259&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000038416&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000008259&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000000008&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'DMFIN1000008259 ' or . = 'DMFIN1000008259 ')]</value>
      <webElementGuid>c8fc8a60-c5db-4fd8-8d1d-9ecbd005787f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
