<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_INSURANCE</name>
   <tag></tag>
   <elementGuidId>104333c3-6c40-414a-b5e2-23aace8e3e28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>453df9e2-afa3-402e-a7e1-af5cfb9cd9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>insuranceQuotationDetails.sprg?&amp;screenId=1200003014&amp;mode=E&amp;screenName=INSURANCE</value>
      <webElementGuid>60b63a3b-daab-43ee-9855-39467d29abad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noLine</value>
      <webElementGuid>35b71230-fa31-4895-96ba-0ecdf0a4989a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INSURANCE</value>
      <webElementGuid>728def70-9efa-4f5d-bb8d-6d4783f196dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;menu col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[4]/a[@class=&quot;noLine&quot;]</value>
      <webElementGuid>e0d6822d-e2b7-4fdc-94b8-875357a6f3dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div/div[4]/a</value>
      <webElementGuid>d1ff2de5-eaf0-4f69-b8ed-649de41ec6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'INSURANCE')])[5]</value>
      <webElementGuid>6311d0f7-a96b-44ae-8504-c85b974d63bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUOTATION'])[5]/following::a[1]</value>
      <webElementGuid>8ae8bb3e-b913-4f61-9d4c-01f7bbb76705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASSET DETAILS'])[3]/following::a[2]</value>
      <webElementGuid>38860ab5-484e-4ea6-9528-09d7cdf82642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASHFLOW'])[3]/preceding::a[1]</value>
      <webElementGuid>5b74e935-63fe-4ea2-b84d-c7949c21fc25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGISTRATION DETAILS'])[2]/preceding::a[2]</value>
      <webElementGuid>7f9f0e4b-6ebc-4669-9a45-81735dc3a8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'insuranceQuotationDetails.sprg?&amp;screenId=1200003014&amp;mode=E&amp;screenName=INSURANCE')]</value>
      <webElementGuid>017506e4-859b-443e-9d84-fa09ce1e5b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>81c57317-8a17-488f-bb2d-d7ff07531f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'insuranceQuotationDetails.sprg?&amp;screenId=1200003014&amp;mode=E&amp;screenName=INSURANCE' and (text() = 'INSURANCE' or . = 'INSURANCE')]</value>
      <webElementGuid>151bc05a-c187-4229-b929-a6637ee45568</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
