<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_QUOTATION</name>
   <tag></tag>
   <elementGuidId>db481740-ceb1-4817-8fce-9012fed96436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e8861d6f-4ac9-4e7a-b227-30a39a42d039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>quotationDetails.sprg?&amp;screenId=1200003013&amp;mode=E&amp;screenName=QUOTATION</value>
      <webElementGuid>33d073d4-b119-4a0f-9309-1559b38b30d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noLine</value>
      <webElementGuid>dd100dc0-7f67-4e7a-97bc-46a6bd1fcb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QUOTATION</value>
      <webElementGuid>16de63f3-140c-4a12-a638-abc2ee62e254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;menu col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[3]/a[@class=&quot;noLine&quot;]</value>
      <webElementGuid>1da54277-f290-4979-a975-ed59a0c646e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div/div[3]/a</value>
      <webElementGuid>07a0897c-ea86-456f-bafd-368d2f74642e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'QUOTATION')])[6]</value>
      <webElementGuid>11fe59b8-1ad2-4756-976b-cc56c117e2b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASSET DETAILS'])[4]/following::a[1]</value>
      <webElementGuid>01427895-f458-4988-bb48-3d95cab64b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPLICANT'])[2]/following::a[2]</value>
      <webElementGuid>d22f244c-56e3-4dce-bbe0-ed90edec5cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INSURANCE'])[2]/preceding::a[1]</value>
      <webElementGuid>ec4860ef-1c1f-4c67-8caf-f8f2aea6270b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASHFLOW'])[3]/preceding::a[2]</value>
      <webElementGuid>f84b84d8-6fe8-4193-a647-fe60106e4eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'quotationDetails.sprg?&amp;screenId=1200003013&amp;mode=E&amp;screenName=QUOTATION')]</value>
      <webElementGuid>7e8e5117-7e46-43e1-9171-e3471c141786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>b8b5ae77-c896-4653-825f-4acfa54ccaa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'quotationDetails.sprg?&amp;screenId=1200003013&amp;mode=E&amp;screenName=QUOTATION' and (text() = 'QUOTATION' or . = 'QUOTATION')]</value>
      <webElementGuid>e3e9d605-3289-4f6b-b227-32b4c20904d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
