<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>font_123456789 (1)</name>
   <tag></tag>
   <elementGuidId>24865e1f-e8c1-4ad5-9d2b-a95b8f1a9ee1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='123456789']/table/tbody/tr/td[2]/a/font</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>font.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>304133a4-7e8d-48d8-85f6-8efe19c95571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>2px</value>
      <webElementGuid>9c122f52-b4a6-432e-8b90-e95cadf56d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>512912f9-e72f-41db-b650-ac0352d0e41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>123456789</value>
      <webElementGuid>84465314-33d5-4d99-ae67-0e026ab3cfe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;123456789&quot;)/table[1]/tbody[1]/tr[1]/td[2]/a[1]/font[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>bec2387f-6528-4c9a-ac4d-74b68695b897</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='123456789']/table/tbody/tr/td[2]/a/font</value>
      <webElementGuid>d6fd572f-9ff0-47c7-aa33-64b9923e20a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/following::font[1]</value>
      <webElementGuid>701693ff-1ee9-42d4-aea7-763f468dadb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[1]/following::font[2]</value>
      <webElementGuid>d68bf4b9-41c2-46a1-9304-cb42becdb002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/font</value>
      <webElementGuid>94324201-4b4d-4731-91c5-85c921e8565a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//font[(text() = '123456789' or . = '123456789')]</value>
      <webElementGuid>0948d6f5-9b6b-4ba9-8a2d-de830bc3293e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
