<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>font_123456789</name>
   <tag></tag>
   <elementGuidId>61021c8b-eaf8-4bd8-9d4d-c23bbbfbc5a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='123456789']/table/tbody/tr/td[2]/a/font</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>font.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>94a77308-1eec-417f-8729-6e809c326a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>2px</value>
      <webElementGuid>b4cdc85f-6e81-4e6f-a6e4-3c13e57c9106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>890acd10-4a6f-4532-924b-0095df8075d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>123456789</value>
      <webElementGuid>bdde57f1-bbdc-4a8e-b18e-263a5c0ce51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;123456789&quot;)/table[1]/tbody[1]/tr[1]/td[2]/a[1]/font[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>510cdf79-98ca-48f0-97af-2c218f089f5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='123456789']/table/tbody/tr/td[2]/a/font</value>
      <webElementGuid>a0cfd39a-d968-41d6-946d-9bab5b049bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/following::font[1]</value>
      <webElementGuid>981cf774-6c06-4175-b888-36cf37bd57bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[1]/following::font[2]</value>
      <webElementGuid>9d58972a-2f39-4fdb-a0fd-e6325d3858a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/font</value>
      <webElementGuid>188119bc-d597-4f8f-ac37-0bbd79bd9142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//font[(text() = '123456789' or . = '123456789')]</value>
      <webElementGuid>fba6e7ae-0654-4eed-acc7-a2266baea449</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
