<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_DM VIEWER_img1000000017</name>
   <tag></tag>
   <elementGuidId>02b882d3-9d6f-4331-b99d-1db40398dd0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='img1000000017']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img1000000017</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c05ce744-68a7-4c94-8cd7-e44cbb9711a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img1000000017</value>
      <webElementGuid>9362dae1-f6e9-4e13-90c7-21957a2c6e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>ef60e092-3174-4fc2-875e-6f17ddaea31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b99a82f-b80a-4d77-9589-8619b15af450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img1000000017&quot;)</value>
      <webElementGuid>9992edd7-ef77-4743-af8b-c93cf053f48d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='img1000000017']</value>
      <webElementGuid>952fcb84-681c-4d50-93ac-b7da363c82eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='imgDiv']/i)[19]</value>
      <webElementGuid>25d71c9f-bc3e-4574-97ac-a4b82fc39c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[74]/div/div/i</value>
      <webElementGuid>53b8cfa9-0bc1-47fe-9cf2-474e43cbb633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'img1000000017']</value>
      <webElementGuid>bcd7543a-af22-4f14-9980-1261649bae64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
