<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dealer Code_btndealerName_1_2</name>
   <tag></tag>
   <elementGuidId>eeaa015a-1b0e-4d50-babb-efed8c559ce5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CHR_DEALER_LOV_ID4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CHR_DEALER_LOV_ID4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b38460a-f59f-4d28-9d53-a4985f16b929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a243eff-da68-4982-84ea-fe7a9ef570da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm</value>
      <webElementGuid>8c17b6e5-4698-4537-b6b6-daab7fc21b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btndealerName</value>
      <webElementGuid>3310e34f-bdb7-47e9-9fbf-d0433411c122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>e903190f-2042-46d8-b6d8-e19d307e5c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CHR_DEALER_LOV_ID4</value>
      <webElementGuid>b6620a36-67d7-4696-86c3-d01ccc3c252a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>dealerChooser(&quot;ASSET DEALER LOV&quot;,&quot;cashFlowInFlowDtl&quot;,$index);</value>
      <webElementGuid>35c88c32-eb8f-4d99-84c9-af08123196a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CHR_DEALER_LOV_ID4&quot;)</value>
      <webElementGuid>16dedd5e-fd9e-41ea-9aff-ded4684812e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CHR_DEALER_LOV_ID4']</value>
      <webElementGuid>549bee4c-005d-4dfa-89bc-cec549af0bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='existingTable']/tbody/tr[6]/td[8]/input[2]</value>
      <webElementGuid>0a8ae6e8-6066-42ea-aa21-22ed17270449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[8]/input[2]</value>
      <webElementGuid>c1757064-338c-4b0b-9435-95b50465fdcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btndealerName' and @id = 'CHR_DEALER_LOV_ID4']</value>
      <webElementGuid>8527fcc5-6f0b-4ead-b6a8-4a063aa340fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
