<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remarks_REMARKS0</name>
   <tag></tag>
   <elementGuidId>58130539-86b0-46a3-b809-c81724e6ccfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='REMARKS0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#REMARKS0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ca99bf7-0769-423d-b619-df7c114226a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>4c0c704e-fe48-4737-bee6-da67ff226efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>REMARKS0</value>
      <webElementGuid>ca5744db-83fe-4767-a962-83ddc91d0db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>asset.REMARKS</value>
      <webElementGuid>ecfb9d23-eb93-4b78-9d02-1903ac9ba5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>disableSearchFlag? true: false</value>
      <webElementGuid>da86b3da-7104-4077-adb2-200552490e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>1d42432c-ae70-4eba-bd54-b780ec4ca2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;REMARKS0&quot;)</value>
      <webElementGuid>8bcb569a-3305-46fe-92f1-38e0cf93ee84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='REMARKS0']</value>
      <webElementGuid>31708a28-41c3-4012-b833-8f890f961b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/div/font/fieldset/div[2]/div[5]/div[2]/div/div[33]/input</value>
      <webElementGuid>704482ad-7431-4a84-a500-44b486b5e505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[33]/input</value>
      <webElementGuid>8027f196-537d-411d-a623-8dd3178aa134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'Text' and @id = 'REMARKS0']</value>
      <webElementGuid>7a567092-efee-43b6-9af5-06c761cfacbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
