<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_miFIN_password (2)</name>
   <tag></tag>
   <elementGuidId>6c310ddc-75e7-44cb-88c4-6a7f87a8a6e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8472313f-4767-469b-b8f9-aa2dc684e08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>17aa0cf0-1478-435f-b529-01150c52f254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1fd8c29d-b612-4bc1-95ed-5426e14da537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>16eae3e3-d2db-4bf3-8608-2ab4645c6855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6ade2e4c-3942-4733-82ed-b74f87fa2ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginPage_id&quot;)/form[1]/div[@class=&quot;main_divlogin&quot;]/div[@class=&quot;row-centered&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12 col-centered&quot;]/div[@class=&quot;login_inputBox&quot;]/div[@class=&quot;pass_td&quot;]/input[1]</value>
      <webElementGuid>1eeb818a-1aee-4234-8fbc-739e8e571022</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>26eccd07-9ec4-4ddb-b512-8f0dd4ba14ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='loginPage_id']/form/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>8601e6b7-8cee-4a7c-abe9-ba3ac3dd667a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>974af8a5-9d8d-4ea4-bffd-1be4ce29ce94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @type = 'password']</value>
      <webElementGuid>e8d79e8f-47d2-432b-8562-536432b6a192</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
