<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ENTITY CODE_entityCode</name>
   <tag></tag>
   <elementGuidId>40384df8-9345-496a-acf8-731a323820aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='entityCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;entityCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d1a4b28-1da3-4819-bbae-4669d2686f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20991cbf-d95f-43eb-af05-44859334d01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>entityCode</value>
      <webElementGuid>3cbb800e-78aa-46c1-8036-63ba480ce946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>766dbce7-1639-496a-85f9-20feed3af087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;menuHavingBody&quot;]/form[1]/div[@class=&quot;container-fluid&quot;]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;main_body&quot;]/tbody[1]/tr[2]/td[3]/input[1]</value>
      <webElementGuid>ad074a89-b4c0-4dd7-8fed-7f0728f36034</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='entityCode']</value>
      <webElementGuid>7e500ef2-ef3f-45ad-8443-b15da39c1f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/input</value>
      <webElementGuid>15cbb5f9-ae71-419b-8252-6ae553039120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'entityCode']</value>
      <webElementGuid>13d4972e-6856-4722-9579-0bb6e0a296a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
