<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SPA_PAYMENT_DATE1</name>
   <tag></tag>
   <elementGuidId>f913839b-b943-433f-b0dd-a7c6e1e4d23c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PAYMENT_DATE1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PAYMENT_DATE1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>388a2f1e-7313-45f1-9185-09c4c49cc72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d11c2fa-8ff4-4570-a559-851d2ab86cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PAYMENT_DATE1</value>
      <webElementGuid>31187450-40cd-4ec8-a801-b5cddadf71b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>itr_dealerObj.PAYMENT_DATE</value>
      <webElementGuid>92db8b88-142a-48db-92e5-5f58ce2f5157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8afa35e5-261e-4bbb-a3b2-356181b41db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:checkDateFormat(this,'PAYMENT DATE');</value>
      <webElementGuid>d51f2784-090b-4290-8235-bcfc2db9dafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD-MON-YYYY</value>
      <webElementGuid>143cd407-baed-49e8-80a4-e45b89dae741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>rowDisabled</value>
      <webElementGuid>1939a0ec-5756-4630-88b5-5ae0ca22b1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-valid-maxlength</value>
      <webElementGuid>4e7d529e-c4c7-4809-8ab0-de02c22a181d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PAYMENT_DATE1&quot;)</value>
      <webElementGuid>e9baa084-956f-49c3-9fb2-d9e19dfb2cd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PAYMENT_DATE1']</value>
      <webElementGuid>78e2c6c4-4f74-4f0b-a675-2b2e8947ee4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/fieldset[2]/div[2]/div[7]/table/tbody/tr[3]/td[16]/input</value>
      <webElementGuid>9755e335-12ee-4d90-9d7b-64343f190833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[16]/input</value>
      <webElementGuid>e78967cd-07f7-4974-9fbe-8e3315f0428c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'PAYMENT_DATE1' and @placeholder = 'DD-MON-YYYY']</value>
      <webElementGuid>299a9210-45ac-4d28-a098-9cf1be20aa9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
