<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address 1_FLATNO</name>
   <tag></tag>
   <elementGuidId>b243ffa1-c37f-498d-bfa8-967373b05a44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FLATNO']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FLATNO</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6940f743-4052-4123-bf4a-2e1a05298eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7b67d72-42ee-47b9-b261-6a9c9260f8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FLATNO</value>
      <webElementGuid>1f32266b-1629-41af-b4d0-899eb3d71724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>address.FLATNO</value>
      <webElementGuid>c984100d-bb7a-4a87-b59b-44307b90c198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>140</value>
      <webElementGuid>ee6e79e4-5689-40de-93bd-256c3bf5c733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>{'background-color': address.ADDRESS_TYPE!='1200000009' ?  '#ffffff' : '#ebf3ff'}</value>
      <webElementGuid>f976c7aa-45bf-4cbd-84f1-559bf62e5028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-valid-maxlength</value>
      <webElementGuid>f5367b48-dadf-44e4-8bdc-5c21a883fe30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FLATNO&quot;)</value>
      <webElementGuid>2869a670-7551-404a-93f0-7b4139dd175d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FLATNO']</value>
      <webElementGuid>72a5bc85-f002-4bb6-957a-3a0ff3625eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addressDivForDisabled']/div[4]/input</value>
      <webElementGuid>7de66130-2017-49bb-b7d1-a3466cf0f229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/fieldset/div/div[4]/input</value>
      <webElementGuid>75c7976c-df6e-4536-9087-26134f13fb21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FLATNO']</value>
      <webElementGuid>1a9c500e-6627-47ec-9b5d-0257bc575550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
