<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SPA_PAYMENT_DATE1_1_2_3 (1)</name>
   <tag></tag>
   <elementGuidId>02703314-7ee9-481c-a04c-86978e5fb821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PAYMENT_DATE1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PAYMENT_DATE1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8cf91d9-e46d-4485-b820-199a5d4c9a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e9d1f97d-eadf-4aab-8872-b9053ac9455e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PAYMENT_DATE1</value>
      <webElementGuid>b409106c-952f-4f98-8726-4fc99360b030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>13-JAN-2023</value>
      <webElementGuid>a383252d-b020-469e-990f-bebff5f5b0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>itr_dealerObj.PAYMENT_DATE</value>
      <webElementGuid>856bf4db-b693-4c40-bec1-3f4326275a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>7c5e8fa9-2419-4457-b738-deffc0c8a881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:checkDateFormat(this,'PAYMENT DATE');</value>
      <webElementGuid>8cb451e3-3a7d-4caa-9402-03f3c3639e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD-MON-YYYY</value>
      <webElementGuid>6fbfb087-5a91-4184-a1bc-f2485238338d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>rowDisabled</value>
      <webElementGuid>f4dfe3d7-fa7a-441a-b176-8d50f1c17ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-valid ng-valid-maxlength ng-dirty ng-valid-parse ng-touched</value>
      <webElementGuid>5f3d7918-59aa-4a11-8446-729328674df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PAYMENT_DATE1&quot;)</value>
      <webElementGuid>47ea8399-31de-41c0-b60d-8ef48ba499a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PAYMENT_DATE1']</value>
      <webElementGuid>9fa9baa6-0dfe-4e95-bbcd-c21a479093f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/fieldset[2]/div[2]/div[7]/table/tbody/tr[3]/td[16]/input</value>
      <webElementGuid>74601b0a-cd19-4332-8748-324361bd5fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[16]/input</value>
      <webElementGuid>f32d98b4-5f2c-48a3-a2b8-6eda0d664878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'PAYMENT_DATE1' and @title = '13-JAN-2023' and @placeholder = 'DD-MON-YYYY']</value>
      <webElementGuid>e73b1612-8bbe-4ce2-aa19-d66c5326faa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
