<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SPA_ROW_SELECT2</name>
   <tag></tag>
   <elementGuidId>01ac1b67-5df3-4114-9aa0-7913eda7c4c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ROW_SELECT2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ROW_SELECT2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e295082-bbc0-4699-8e46-58841304928c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5ab27bdd-312c-4b10-b616-e1dc88f431b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ROW_SELECT2</value>
      <webElementGuid>529dd9c4-50e9-4bf0-ac77-2e58201961f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>itr_dealerObj.ROW_SELECT</value>
      <webElementGuid>3943f95d-5187-4107-a2da-94dac50ff88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>(offlineDtlObj.CAPITALISATION_FLG=='N')?true:false</value>
      <webElementGuid>bfe9a952-76a8-407a-90cd-428e024e6b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>(itr_dealerObj.CURR_TRANS_ST=='' || itr_dealerObj.CURR_TRANS_ST=='1000000001' &amp;&amp; user_Type=='MKT')?true:false</value>
      <webElementGuid>fdd80612-9526-4c2b-aabf-8718188bd575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>5938dd23-249b-441c-b912-8c4b619102d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ROW_SELECT2&quot;)</value>
      <webElementGuid>4d0e6be8-c08a-4943-8c54-bdf7f0b44c41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ROW_SELECT2']</value>
      <webElementGuid>975c7172-1b3a-4158-ae51-549d1e4165cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/fieldset[2]/div[2]/div[7]/table/tbody/tr[4]/td/input</value>
      <webElementGuid>497b1958-8fd0-40ee-833e-dc23f9e8670e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>dcf1f15b-a76d-470a-b617-1ac7c9816c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ROW_SELECT2']</value>
      <webElementGuid>47188503-54bc-4afc-b0b0-cf714c38ce80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
