<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Send To Author_mrSendToAuthor (1)</name>
   <tag></tag>
   <elementGuidId>885393af-8448-4abd-b538-79ddae6e77f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='approveCheck']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#approveCheck</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79932898-2fea-47c9-a6ed-ae3c96d1113f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9cc98abc-0151-4f67-9d22-2e9b1fb84fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>approveCheck</value>
      <webElementGuid>e17a97c5-e31b-4532-908b-34acb8c5ff64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mrSendToAuthor</value>
      <webElementGuid>ea79aaf5-f1f4-43ed-ab33-1d13492a056a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>635e8fe9-275e-4651-9c78-504cf6709731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:approveRejectToggle(document.forms[0].mrSendToAuthor.value);toggleRejectReason('P')</value>
      <webElementGuid>334b04ba-35cb-4881-a39b-052895d7c060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;approveCheck&quot;)</value>
      <webElementGuid>4457f20f-18f5-4282-b8e5-38db2cc5edf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='approveCheck']</value>
      <webElementGuid>7dedb17c-7beb-45a2-9e7c-c058605e9606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/input</value>
      <webElementGuid>f9504bfd-bf70-4f82-be77-7e006493c87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'approveCheck' and @name = 'mrSendToAuthor']</value>
      <webElementGuid>84a753ec-9f64-49d4-a5e6-3c5113720ee4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
