<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SPA_PAYMENT_DATE0_1_2_3_4_5_6_7_8_9_10_11_12_13</name>
   <tag></tag>
   <elementGuidId>05744b7a-482a-4a7a-9c2e-fef1ec8a9b7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PAYMENT_DATE0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PAYMENT_DATE0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a85537e-757a-4af8-9179-c7e456d4c1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f1281ea-7786-4d0c-bf09-48fbcbe62021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PAYMENT_DATE0</value>
      <webElementGuid>c1e160cc-8cce-45c3-be2a-e566f532fc77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>06-2022</value>
      <webElementGuid>927ab20d-eda5-4807-8fa5-bd47acb18b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>itr_dealerObj.PAYMENT_DATE</value>
      <webElementGuid>640f3dbb-53f0-4634-8147-745e1d47e0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>395fc128-a199-4f86-b5ac-39a48a75939b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:checkDateFormat(this,'PAYMENT DATE');</value>
      <webElementGuid>15c1bc82-2f07-48f2-a517-be0930ab6137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD-MON-YYYY</value>
      <webElementGuid>89b7bb0a-72a1-4014-9aea-0d50d4b1ade7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>rowDisabled</value>
      <webElementGuid>3dbeaab9-5fe5-4517-b910-6a8b2c095bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-valid ng-valid-maxlength ng-dirty ng-valid-parse ng-touched</value>
      <webElementGuid>19ba7027-bfac-4097-9f03-dbd212ed833b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PAYMENT_DATE0&quot;)</value>
      <webElementGuid>6b026c63-98fc-4ed1-9fcf-5b6cf8a9c82f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PAYMENT_DATE0']</value>
      <webElementGuid>37dda255-e830-4a1d-a55e-526a52fbb8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/fieldset[2]/div[2]/div[7]/table/tbody/tr[2]/td[16]/input</value>
      <webElementGuid>a64fe629-ebcc-4aa0-939c-f788d3c0a34d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[16]/input</value>
      <webElementGuid>ccabd4b8-a241-4ce0-a4d7-9c822d9be1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'PAYMENT_DATE0' and @title = '06-2022' and @placeholder = 'DD-MON-YYYY']</value>
      <webElementGuid>2a77552f-c44b-46da-8615-5b2889d68ba0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
