<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_OK (1)</name>
   <tag></tag>
   <elementGuidId>374ca43e-534d-411d-a0a8-1b932f71a44a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='OK']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;OK&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fbf00228-1a5c-4e01-8006-c07927114adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>695c72c7-f5cb-4b59-80e0-eb0631bf204e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm</value>
      <webElementGuid>9cfb6ad4-d566-4720-add0-07d365a78584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>3e8af852-decd-410a-89eb-1fe202798329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>9e697e64-55e2-490f-8f98-34bc81965db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>submitForm();</value>
      <webElementGuid>4e490fd1-a34c-4ff9-861c-2b7ad2fd4933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LovParent&quot;)/table[2]/tbody[1]/tr[@class=&quot;gray_tr&quot;]/td[1]/input[@class=&quot;btn btn-primary btn-sm&quot;]</value>
      <webElementGuid>3e67b203-845a-49db-b46c-b2e2def5d60b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='OK']</value>
      <webElementGuid>492af60f-4d9d-43ef-a2f5-4d7bc16d3382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LovParent']/table[2]/tbody/tr/td/input</value>
      <webElementGuid>33dfcc7a-48d6-4d50-a0ba-4c26de09584b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>a15b2c7a-010d-4ba1-a05a-939e1b1c93e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'OK']</value>
      <webElementGuid>742e9998-da16-4322-9b8f-242b0f719f66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
