<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dealer Code_btndealerName_1</name>
   <tag></tag>
   <elementGuidId>20e4d115-dfdd-4edb-8200-7f03a81bbc0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CHR_DEALER_LOV_ID3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CHR_DEALER_LOV_ID3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8d709a8-0e38-4382-af45-476d7876b322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>84f4fbfc-2519-4627-b79b-66caddd7f1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm</value>
      <webElementGuid>3fcc4e38-24dd-4f04-96e7-fcb2771c8111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btndealerName</value>
      <webElementGuid>e724f808-e288-459d-8340-d758a59aad81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>c0764934-927b-42bb-8ace-f55ebebf018f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CHR_DEALER_LOV_ID3</value>
      <webElementGuid>49077103-2a0c-4b7f-9ec9-4e131b23e772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>dealerChooser(&quot;ASSET DEALER LOV&quot;,&quot;cashFlowInFlowDtl&quot;,$index);</value>
      <webElementGuid>8b609c95-3972-4b32-a07b-f34ad9ce033f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CHR_DEALER_LOV_ID3&quot;)</value>
      <webElementGuid>2595aa77-1d44-43d0-ae2e-f5843a83f393</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CHR_DEALER_LOV_ID3']</value>
      <webElementGuid>f6dfa640-c938-4a7d-b587-6c4afddf5dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='existingTable']/tbody/tr[5]/td[8]/input[2]</value>
      <webElementGuid>455fc6c6-746c-4061-8a98-3e941bfd9e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[8]/input[2]</value>
      <webElementGuid>f9b62fd6-c224-4020-a37d-8d592658c024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btndealerName' and @id = 'CHR_DEALER_LOV_ID3']</value>
      <webElementGuid>22ab2c45-326f-4a23-96a3-25fb4b063547</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
