<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SPA_ROW_SELECT1</name>
   <tag></tag>
   <elementGuidId>e231f0b7-6651-422c-8ce1-ebe158d25312</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ROW_SELECT1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ROW_SELECT1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8d17055-cad0-41bb-b164-4d9dc36ed5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>52bbf022-5846-43e6-85d9-dd002868c68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ROW_SELECT1</value>
      <webElementGuid>25aff91e-2506-4244-9c01-e85adbb433e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>itr_dealerObj.ROW_SELECT</value>
      <webElementGuid>09003185-b02a-41af-b3e6-97c682cc2fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>(offlineDtlObj.CAPITALISATION_FLG=='N')?true:false</value>
      <webElementGuid>ee684739-a7fe-4b4c-b86c-95be0fa5ea5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>(itr_dealerObj.CURR_TRANS_ST=='' || itr_dealerObj.CURR_TRANS_ST=='1000000001' &amp;&amp; user_Type=='MKT')?true:false</value>
      <webElementGuid>8e30916b-ba8d-40a6-a80a-5f734e5f5ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>e00be7d7-9681-41d8-bb33-8e2e6ef34a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ROW_SELECT1&quot;)</value>
      <webElementGuid>bca4010e-5bba-468c-8a9b-3cccbabea8b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ROW_SELECT1']</value>
      <webElementGuid>cb42c9a7-da72-4c88-a819-27bdbe4d38b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/fieldset[2]/div[2]/div[7]/table/tbody/tr[3]/td/input</value>
      <webElementGuid>c607b0bb-f4e2-4f96-9041-3ae22786bf37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/table/tbody/tr[3]/td/input</value>
      <webElementGuid>b7cca904-0db5-4a6e-a4ea-21c29972ebf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ROW_SELECT1']</value>
      <webElementGuid>e7c2cd3d-ac01-4118-b45a-7d5fed153017</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
