<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Actual Delivery Date_ACT_DELIVERY_DT</name>
   <tag></tag>
   <elementGuidId>8ae645ce-123f-430e-87b3-e8eb56da735b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ACT_DELIVERY_DT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ACT_DELIVERY_DT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd5310cc-b66b-4a78-b82d-d9059750d81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_header_cost ng-pristine ng-untouched ng-valid ng-valid-maxlength</value>
      <webElementGuid>1eccccd1-cf49-4bf8-99e7-81d671412181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>096058da-85df-4762-98c0-a27dee240e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ACT_DELIVERY_DT</value>
      <webElementGuid>de9c10e2-d720-423c-8033-a6cb9fa3483f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>offlineDtlObj.ACT_DELIVERY_DT</value>
      <webElementGuid>8d220850-4e7a-4edc-95e3-604fa5235f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>54b03b01-e0ad-4650-9965-0d24cf19c273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:checkDateFormat(this,'ACTUAL DELIVERY DATE');</value>
      <webElementGuid>7c03a0a9-7009-480f-b760-b1fdf1a64c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD-MON-YYYY</value>
      <webElementGuid>134eba83-81a0-4877-8e5e-714dd80cccee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>offlineDtlObj.ENABLE_ACTUAL_DELIVERY_DATE_FLAG</value>
      <webElementGuid>10ede3c2-7d91-415a-ac97-97efdd2ed68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ACT_DELIVERY_DT&quot;)</value>
      <webElementGuid>1b4b0c09-3baa-4d46-82c0-301bd19ce37d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ACT_DELIVERY_DT']</value>
      <webElementGuid>8ebc988b-bb09-49a9-b1a4-e4e2fa2d4ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/fieldset/fieldset/div[2]/div[4]/input</value>
      <webElementGuid>4a706221-84ad-46a0-96e5-b2e7eb781f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>532fb986-489f-4a49-9fed-def0c949084b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ACT_DELIVERY_DT' and @placeholder = 'DD-MON-YYYY']</value>
      <webElementGuid>806b29a2-c854-488a-945e-e44d078ddfed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
