<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pincode_btnZip</name>
   <tag></tag>
   <elementGuidId>b770dc7c-cd76-43c6-ad78-5931d412d2fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pinCodeLobId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pinCodeLobId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf4bbe97-ca8d-4354-9f1c-700664b6aa42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7dde3bc5-2806-4a43-985c-e4edbcc3bd7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm</value>
      <webElementGuid>68340443-1788-4e45-9c7a-a5f0d27fd101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnZip</value>
      <webElementGuid>eed28a17-9f74-4e32-b284-d35db3ebcbc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>db23b5ea-17b1-42cf-8f3e-1b0671f31bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pinCodeLobId</value>
      <webElementGuid>2c002c5d-b345-4959-b1d1-2d00eccc0c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>pinChooser('QM_PINCODEMASTER');</value>
      <webElementGuid>9b7103d4-0aad-4ff6-b2fc-9a3a7823b2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pinCodeLobId&quot;)</value>
      <webElementGuid>cc0891fd-b573-41b8-9df1-47c602cb5190</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pinCodeLobId']</value>
      <webElementGuid>b264584d-d021-4f7a-aa54-9026d20120da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addressDivForDisabled']/div[20]/input[3]</value>
      <webElementGuid>8075fa4b-527a-4957-b44b-2dfe3aa38d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/input[3]</value>
      <webElementGuid>dae73363-7f0d-4ddf-b6cb-3790851191fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btnZip' and @id = 'pinCodeLobId']</value>
      <webElementGuid>a7050e5b-9f45-425c-9833-79a33d381859</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
