<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SPA_PAYMENT_DATE0_1_2_3</name>
   <tag></tag>
   <elementGuidId>434675c9-0e72-4119-9915-12982d7f1c75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PAYMENT_DATE0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PAYMENT_DATE0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21e4e6ed-25ae-400f-9a16-dff56a398885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5fb9aae0-08dd-433d-8466-6cb626b9cee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PAYMENT_DATE0</value>
      <webElementGuid>2f919cc6-61a1-4b98-9a37-4f430680a109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>20-</value>
      <webElementGuid>caa12f3e-ac40-4c1d-95e8-48304b609c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>itr_dealerObj.PAYMENT_DATE</value>
      <webElementGuid>956c8600-7e2f-40f5-98e8-135732649be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>b1b7e657-42a6-4280-b959-f2f2d4465887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:checkDateFormat(this,'PAYMENT DATE');</value>
      <webElementGuid>416744af-ad99-4a21-8914-5607a61b0445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD-MON-YYYY</value>
      <webElementGuid>6f059dfa-f3e3-436d-b38e-3e6ba7e9bfb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>rowDisabled</value>
      <webElementGuid>3d35d9f8-de43-45f5-85b1-aa74745a59e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ng-valid-maxlength ng-dirty ng-valid-parse</value>
      <webElementGuid>d356b505-39e6-485d-b76e-3634f1eee606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PAYMENT_DATE0&quot;)</value>
      <webElementGuid>cb6675ca-c65e-4c59-9f8f-f3f8b2b0394f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PAYMENT_DATE0']</value>
      <webElementGuid>5c7896fb-4901-4979-a7f9-22f6b0e91604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/fieldset[2]/div[2]/div[7]/table/tbody/tr[2]/td[16]/input</value>
      <webElementGuid>f8c64a1c-8d2e-4340-8f22-d4137fb4055c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[16]/input</value>
      <webElementGuid>aba66437-b109-4cd8-9ae4-2c5cc6aed623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'PAYMENT_DATE0' and @title = '20-' and @placeholder = 'DD-MON-YYYY']</value>
      <webElementGuid>d1439490-e076-42ff-89cf-e686d8928a13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
