<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dealer Code_CHARGE_AMOUNT3</name>
   <tag></tag>
   <elementGuidId>f625e73d-835e-4b77-83d8-0bbbc6f55981</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CHARGE_AMOUNT3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CHARGE_AMOUNT3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a32c9cfe-d3fd-40c1-8ce4-7f2bacc0fbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>65d7e31a-e2b3-4484-8c65-4c3c68a5e2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qt_txt_Align ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>9d8abc8a-2ebb-4881-8797-2c55346eb0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CHARGE_AMOUNT3</value>
      <webElementGuid>b2f1a11d-a836-4261-b10a-01c68f675413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return event.charCode >= 48 &amp;&amp; event.charCode &lt;= 57 || event.charCode == 46</value>
      <webElementGuid>174b2ceb-d737-4724-808b-fecce416a979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>format</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>f4928623-f77b-4d31-afc4-183bc8b0c843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inflow.CHARGE_AMOUNT</value>
      <webElementGuid>d90e5e0b-68e2-4b88-9ac7-4b421949c225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>inflow.CHARGE_ID == '1200000001' || inflow.CHARGE_ID == '1200000046'?true:false</value>
      <webElementGuid>07af25f9-cea7-4384-988c-add10f88da61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keyup</name>
      <type>Main</type>
      <value>checkLength('cashFlowInFlowDtl','CHARGE_AMOUNT',$index);calculateVat('cashFlowInFlowDtl',$index)</value>
      <webElementGuid>708f0dba-0bbb-4996-9103-d9580f985004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CHARGE_AMOUNT3&quot;)</value>
      <webElementGuid>4fed5657-4efe-4e4d-b2cc-c3a5491093d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CHARGE_AMOUNT3']</value>
      <webElementGuid>4f631dbf-2275-4c9d-9768-baf24af46b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='existingTable']/tbody/tr[5]/td[4]/input</value>
      <webElementGuid>33cb9227-dde8-417b-8f74-ef856a9554f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[4]/input</value>
      <webElementGuid>5b588a3a-3c47-489e-b8f7-288c5a02cb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CHARGE_AMOUNT3']</value>
      <webElementGuid>500744eb-3d40-4b17-9377-5e390228ed55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
