<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remarks_AUTHOR_REMARKS_ID_1_2</name>
   <tag></tag>
   <elementGuidId>8328b555-f0bc-4999-94b7-650efe8acfad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AUTHOR_REMARKS_ID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AUTHOR_REMARKS_ID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>500bf741-c741-4d55-b49b-9655e9ffb449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0fbcb162-5668-4079-a8e7-6196a0d733df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AUTHOR_REMARKS_ID</value>
      <webElementGuid>97f054ec-b81b-4013-b8c3-9de171fdec1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>AUTH_REMARKS</value>
      <webElementGuid>c3865739-ba51-4d89-a46d-9dccd7403b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>efda9c7d-e95a-4b75-a2e1-9e0e6c832653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>f35bab45-6c07-49e1-bbb4-438b35c55edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ng-dirty ng-valid-parse</value>
      <webElementGuid>d3e2f8c3-ba50-4695-8dbf-9ebc1748e856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ok</value>
      <webElementGuid>534d8839-8637-498d-b983-257f38b45eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AUTHOR_REMARKS_ID&quot;)</value>
      <webElementGuid>a680a5aa-93f8-4d90-bbe0-1b358386de43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AUTHOR_REMARKS_ID']</value>
      <webElementGuid>a24a3427-590d-40d7-ba02-a62744e237a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/div/fieldset/fieldset[2]/div/div[3]/div[2]/input</value>
      <webElementGuid>86d2f248-4d70-4fb0-9f52-6bd737c45df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>a6093946-5951-4492-805a-d470e42d0c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'AUTHOR_REMARKS_ID' and @title = 'ok']</value>
      <webElementGuid>5eb5e631-5c90-4dd9-b050-4ce94e93902c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
