<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SYSUSER_DOCUMENT_DESCRIPTION2</name>
   <tag></tag>
   <elementGuidId>78a33b92-78e7-45b3-9c6d-b6944d68797e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DOCUMENT_DESCRIPTION2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DOCUMENT_DESCRIPTION2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1926e08-397b-4620-a601-3e63f561b9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4927cb9-fe9c-4bb4-a767-3c21eeb2d327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DOCUMENT_DESCRIPTION2</value>
      <webElementGuid>e923c577-f134-4a80-9edc-b721a4bf378c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>docDetail.REMARKS</value>
      <webElementGuid>a2ba93ea-df57-4258-9c33-8d8b85c531ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>d1b221ce-30bb-4e22-b1a1-951ef4c9c53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-valid-maxlength</value>
      <webElementGuid>95b454c3-8a84-4b37-a092-b0c85aac6cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DOCUMENT_DESCRIPTION2&quot;)</value>
      <webElementGuid>34e6be77-6979-4bb2-9378-92a939a26b03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DOCUMENT_DESCRIPTION2']</value>
      <webElementGuid>d417d75c-36aa-4998-990b-a5b066a4e49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='documentTable']/tbody/tr[4]/td[7]/input</value>
      <webElementGuid>f545c37d-c3dd-4d70-99f0-f32d5f2ee751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[7]/input</value>
      <webElementGuid>484a00c7-33ab-4518-8f2f-f65381fe0aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DOCUMENT_DESCRIPTION2']</value>
      <webElementGuid>d2d9c29e-9604-45a7-80c4-0ba12e63c35a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
