<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SPA_SCHEDULE_PAYMENT2</name>
   <tag></tag>
   <elementGuidId>ef840bf7-a34f-4550-b073-9177752cbb69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SCHEDULE_PAYMENT2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SCHEDULE_PAYMENT2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35b909bf-fbaa-404e-8569-545e5a0c9527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1f9209f4-3766-4389-8749-728cfcee29ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SCHEDULE_PAYMENT2</value>
      <webElementGuid>b1086338-dad0-4cb8-bd98-b059e2d44207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>itr_dealerObj.SCHEDULE_PAYMENT</value>
      <webElementGuid>347d4e00-dc05-4fc8-85a1-e6935ba6ec21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>(offlineDtlObj.CAPITALISATION_FLG=='N')?true:false</value>
      <webElementGuid>b08a3e89-2e75-470e-a2c4-9a7348a59beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>changePaymentStatus(itr_dealerObj,'sp')</value>
      <webElementGuid>a287ca0f-85ac-44a2-97db-a3574d0ae98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>ccebd2a0-93fe-46f5-b516-db95c9d9bfaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SCHEDULE_PAYMENT2&quot;)</value>
      <webElementGuid>24cfd6ed-40bc-4ea8-b37b-90ee5654d58f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SCHEDULE_PAYMENT2']</value>
      <webElementGuid>7323a2ca-2579-47bd-bfdc-22b5732065cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/fieldset[2]/div[2]/div[7]/table/tbody/tr[4]/td[4]/input</value>
      <webElementGuid>528af02e-ba38-444e-ac87-21d7acfbf00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/input</value>
      <webElementGuid>4472e5e7-03fc-4a9a-85ea-5f1d2e1cf601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'SCHEDULE_PAYMENT2']</value>
      <webElementGuid>759d730c-ad45-4d73-b06e-1c8d1f73d04e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
