<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SPA_SCHEDULE_PAYMENT1 (1)</name>
   <tag></tag>
   <elementGuidId>1008fe16-8dd9-4456-b3d9-3f0914764302</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SCHEDULE_PAYMENT1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SCHEDULE_PAYMENT1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b45f677-5cec-4623-b2c7-5bd3dbbe80b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9e878847-ea94-4254-8c29-a3280930118d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SCHEDULE_PAYMENT1</value>
      <webElementGuid>7d335117-4fa2-4941-bdd5-b45c0db83281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>itr_dealerObj.SCHEDULE_PAYMENT</value>
      <webElementGuid>79dc1d8d-3762-4f4a-a169-07cfc3b9d739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>(offlineDtlObj.CAPITALISATION_FLG=='N')?true:false</value>
      <webElementGuid>095189e9-2d93-4bd0-a04e-f15ee8ea165e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>changePaymentStatus(itr_dealerObj,'sp')</value>
      <webElementGuid>e8826156-18df-4f71-930a-1a771dfc2198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>11d04622-5624-45a2-a455-c7afe8cecada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SCHEDULE_PAYMENT1&quot;)</value>
      <webElementGuid>1f353773-e34d-448c-8822-8e1408988d5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SCHEDULE_PAYMENT1']</value>
      <webElementGuid>ab8c5cc9-49d7-41d6-9ff1-514f7ad9816c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/fieldset[2]/div[2]/div[7]/table/tbody/tr[3]/td[4]/input</value>
      <webElementGuid>265b0f54-2107-49be-88ec-a2a1dcd1f3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/input</value>
      <webElementGuid>f88c77bc-da77-4670-b433-28a880b42087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'SCHEDULE_PAYMENT1']</value>
      <webElementGuid>6bad12f9-596b-4335-aa58-e03ae802addf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
