<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PORT LOUIS_OK</name>
   <tag></tag>
   <elementGuidId>46269cc7-70ee-4747-b733-6d41f611cd11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='OK']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;OK&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72daf830-8448-4a73-a134-88a8e785d6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3091caa3-889e-4db0-a6a6-bde8035dbc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm</value>
      <webElementGuid>890a6cbe-cb77-4936-b078-a4a692481390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>5304e596-fb81-4677-8e09-45d5eac96e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>cf58851d-39ee-42b6-a252-d0e7360b7ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>submitForm();</value>
      <webElementGuid>86d2645a-dd22-4bf5-a0a1-e1c226f176c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LovParent&quot;)/table[2]/tbody[1]/tr[@class=&quot;gray_tr&quot;]/td[1]/input[@class=&quot;btn btn-primary btn-sm&quot;]</value>
      <webElementGuid>0e2f9e8c-04aa-41c5-8349-ebc468173d1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='OK']</value>
      <webElementGuid>52cff402-71c9-4bfb-b40a-ac105b366b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LovParent']/table[2]/tbody/tr/td/input</value>
      <webElementGuid>0e9101ab-a260-4fe0-9d5b-537738a41492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>7c0b36f1-e2b2-4fb2-a0d5-2d07901ee2a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'OK']</value>
      <webElementGuid>303f1f8e-66d5-4166-bdff-d19cb96613ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
