<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SPA_PAYMENT_DATE0_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27</name>
   <tag></tag>
   <elementGuidId>237f6bcf-d813-49a7-8f1e-e451fd77b663</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PAYMENT_DATE0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PAYMENT_DATE0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94f64c58-60bd-4efd-bc49-29f1d90fcbcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c57f16c-3aec-4d03-ac4a-11ef28d50078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PAYMENT_DATE0</value>
      <webElementGuid>6cb6a888-c397-4c08-a6b0-487a1914bfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>13-JAN-202</value>
      <webElementGuid>db076945-67ff-4cbd-86be-a7ec9d8a16a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>itr_dealerObj.PAYMENT_DATE</value>
      <webElementGuid>eb8efc04-0359-4ff9-b3e6-b877a8d7247e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>5fb517e8-9ec6-42ce-ab4a-e617f7347de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:checkDateFormat(this,'PAYMENT DATE');</value>
      <webElementGuid>89f3f3e3-88ca-42b8-bf5d-ab969e98008e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD-MON-YYYY</value>
      <webElementGuid>ec554705-6f21-41fc-ac9c-c419460ce87e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>rowDisabled</value>
      <webElementGuid>914b8280-9ef0-4bab-a91b-a21c377f1444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-valid ng-valid-maxlength ng-dirty ng-valid-parse ng-touched</value>
      <webElementGuid>15f80a1e-b30f-4726-bb2a-7ba4d767fb70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PAYMENT_DATE0&quot;)</value>
      <webElementGuid>fa6585d3-27a8-4b46-a7bc-c536454743ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PAYMENT_DATE0']</value>
      <webElementGuid>73970803-0951-4c26-8e3f-6b955521762a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/fieldset[2]/div[2]/div[7]/table/tbody/tr[2]/td[16]/input</value>
      <webElementGuid>6be84243-7685-43b4-9ea7-129734085c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[16]/input</value>
      <webElementGuid>5730f594-34e3-42a8-b3ca-0b28fac51976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'PAYMENT_DATE0' and @title = '13-JAN-202' and @placeholder = 'DD-MON-YYYY']</value>
      <webElementGuid>4a890d29-1d7d-4572-a17e-264d65a935c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
