<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Assignation in favour of CFSL_INS_STA_d425d5_1</name>
   <tag></tag>
   <elementGuidId>3542131e-b4d0-4d4d-bf48-82b540d42893</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='INS_START_DATE0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#INS_START_DATE0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df7dc410-b508-448f-85a1-98839417a60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ea0c2ca-b594-4cd1-b270-9d56efa5fb33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>INS_START_DATE0</value>
      <webElementGuid>a5c9776c-1483-4a94-a601-0f8f8a2a55a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7818468c-ce85-40a9-befa-50a98a8904c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inflow.INS_START_DATE</value>
      <webElementGuid>f1d1d8a1-b423-44da-af15-b38ce57a0b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>a5f8591b-f335-4b1d-a931-4807286bee03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:checkDateFormat(this,'INS. START DATE');</value>
      <webElementGuid>a0d564f0-05ba-47c9-909a-1f1455b7faf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD-MON-YYYY</value>
      <webElementGuid>c27f1315-459e-4805-9d45-9f185554e9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ng-valid-maxlength ng-dirty ng-valid-parse</value>
      <webElementGuid>8d141536-3f78-4d93-9cdf-45ca28a7f500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;INS_START_DATE0&quot;)</value>
      <webElementGuid>860ae1e2-91b4-4117-bde9-095ac0873ca8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='INS_START_DATE0']</value>
      <webElementGuid>9fc6c6f0-77dd-418c-9e6d-7c72856c2f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='command']/div/fieldset/fieldset[3]/div[2]/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>995f34e8-959e-4918-bfb2-fe88015f9c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>96bc2e83-c3c8-4907-bd55-9c0062de8e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'INS_START_DATE0' and @title = '1' and @placeholder = 'DD-MON-YYYY']</value>
      <webElementGuid>a156f159-b8cf-423f-9ea8-f30f550f6b3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
