<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Send To Author_mrSendToAuthor</name>
   <tag></tag>
   <elementGuidId>4b164618-6ab8-4093-b392-5bbf939b1f1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='approveCheck']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#approveCheck</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91c7f585-4ad6-4863-b415-6b31b2b2a4db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6820a7c3-c215-4024-873d-7eade9c4726d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>approveCheck</value>
      <webElementGuid>ab3041af-b651-4fd4-af53-dda7c791c136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mrSendToAuthor</value>
      <webElementGuid>8bc07ba1-02cd-4402-b7ef-c58b6d58d6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>bd4e1f55-94b6-4ae1-9728-37dd391b8af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:approveRejectToggle(document.forms[0].mrSendToAuthor.value);toggleRejectReason('P')</value>
      <webElementGuid>84abe019-d5af-467c-b64a-7d3cb505c8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;approveCheck&quot;)</value>
      <webElementGuid>9fd228b3-5f23-4d0e-b5a4-1c831871cc6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='approveCheck']</value>
      <webElementGuid>bc7e865a-8376-4212-a4f5-adfa5a6c09c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/input</value>
      <webElementGuid>d13cd28f-6b43-4039-9857-f6e62700b285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'approveCheck' and @name = 'mrSendToAuthor']</value>
      <webElementGuid>38450153-9783-466f-b2de-527a266742cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
