<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DM Code_dmCode_1</name>
   <tag></tag>
   <elementGuidId>fbecdb40-b6f1-480c-89c3-1a7cda1cc67a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dmCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dmCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3597745d-15ba-46c3-9363-8b9e411504a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_header_cost ng-untouched ng-valid ng-dirty ng-valid-parse</value>
      <webElementGuid>0c7589b1-405a-4e8e-b151-787764028fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee8a81b3-d88d-4bc3-9cb9-a9e022de8ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dmCode</value>
      <webElementGuid>d35d949e-f018-4137-b472-2a4aa896dc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>searchData.dmCode</value>
      <webElementGuid>f45783d5-8e49-4da8-99ec-61a9b923a433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DMFIN1000008259</value>
      <webElementGuid>377c38a8-358a-4661-ae05-f7a438367017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dmCode&quot;)</value>
      <webElementGuid>d9f2ee91-f8e0-4b64-ae4c-150c3fe7c190</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dmCode']</value>
      <webElementGuid>081370a7-cdcb-48c3-a9ba-89a8644d9c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='dashbord_main']/form/div[5]/div/div/div[12]/input</value>
      <webElementGuid>1560d768-e73b-4804-9d67-a5306f2ff1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/input</value>
      <webElementGuid>79060cef-81a6-4824-9598-15538defc120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dmCode' and @title = 'DMFIN1000008259']</value>
      <webElementGuid>b2836885-f9f1-4cf5-a869-78260ff006e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
