<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DMFIN1000008259_instDate</name>
   <tag></tag>
   <elementGuidId>6e2296cb-4f43-4fe7-8c90-966a6bea319e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='instDate1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#instDate1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea0a6f78-9661-4a80-87e6-6259d9d53531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>050cb7c1-98e2-4299-beef-1b83277eb80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>instDate</value>
      <webElementGuid>9e090099-8912-47cc-8e6a-b8d8d352148b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>instDate1</value>
      <webElementGuid>7c46f43a-5c4e-4929-87c7-66d6b0e44e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>a6bafc63-afe7-4a0b-a9f5-813fad728a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>26</value>
      <webElementGuid>987c087f-8734-4a88-ac75-517b859a5aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>dateCheck(1);</value>
      <webElementGuid>d630560d-70e4-4155-bd9c-81aaa179b02c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;instDate1&quot;)</value>
      <webElementGuid>c6c86fb9-a11b-4929-8f08-0151f410a7ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='instDate1']</value>
      <webElementGuid>25390365-bd3b-45f0-91b9-35f0fa483499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='addRow']/tbody/tr[2]/td[10]/table/tbody/tr/td/input</value>
      <webElementGuid>ce24d3cc-0fe0-46f5-9581-771c24d7c639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/table/tbody/tr/td/input</value>
      <webElementGuid>10759f01-3c03-4539-8ae5-480e4dc1e0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'instDate' and @id = 'instDate1']</value>
      <webElementGuid>db9234ee-0830-4d44-b470-d94a2d3e2223</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
