<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DMFIN1000008259_instNo</name>
   <tag></tag>
   <elementGuidId>991e81ee-b4b5-4db5-bfac-291110bae0b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='instNo1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#instNo1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7c495db-3737-4d6d-9fad-72457ab6b30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b8da71e5-c6a7-475a-94d8-0bb11c4da894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>instNo</value>
      <webElementGuid>69d40fd7-27d3-4333-98b9-6eded95e3fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>instNo1</value>
      <webElementGuid>7ded7453-6205-4da5-a732-9e3fac3803b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>8bfc296c-aded-4d5a-a542-2987cb9c027e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>4063dcbc-d0ab-4738-9772-1a531a976eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;instNo1&quot;)</value>
      <webElementGuid>bcaeeb8c-8ed1-41f7-bed2-f5cf97df91e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='instNo1']</value>
      <webElementGuid>50f3e6ba-ab68-4717-9b96-d76b0cca36a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='addRow']/tbody/tr[2]/td[9]/input</value>
      <webElementGuid>da67785f-0433-4125-9226-07181b4e1be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/input</value>
      <webElementGuid>7818cc3a-def5-4fab-a6af-059a330af169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'instNo' and @id = 'instNo1']</value>
      <webElementGuid>c7cb943a-48da-4972-9811-2e36cdb3a383</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
