<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Updated Date_UPDATED_CHK0</name>
   <tag></tag>
   <elementGuidId>187f2478-90ce-47e3-96cf-db950e94bf97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UPDATED_CHK0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#UPDATED_CHK0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ab6b1f8-3039-44e5-9d9a-8711af492d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a3903c5a-f32e-4d83-85c5-c941ae9322ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UPDATED_CHK0</value>
      <webElementGuid>cb9d257c-db53-46ee-b8c2-796fd7027eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>docDetail.UPDATED</value>
      <webElementGuid>6d68e770-f9bc-47f4-8bae-cd7b09d703d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-checked</name>
      <type>Main</type>
      <value>docDetail.UPDATED=='Y'?true:false</value>
      <webElementGuid>4436d813-a6e7-4f20-91f6-42b83cf172b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>deleteUpdateChecked(docDetail,'U',$index)</value>
      <webElementGuid>94883b88-6932-414c-8126-73e69827306c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>docDetail.ALLOW_UPDATE_FLAG=='N'?true:false</value>
      <webElementGuid>29ebf0c6-ff54-4337-8445-7c9da241ecc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>014e20bc-799f-4dfe-8e3c-d3d455df5f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UPDATED_CHK0&quot;)</value>
      <webElementGuid>76b6a2a6-e25b-4f50-bb2f-9b5c97a73745</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UPDATED_CHK0']</value>
      <webElementGuid>1c7432f1-2f7f-403b-b711-55bbe701b14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='documentTable']/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>61a03cdf-079b-4dfa-a325-54ba7afa8141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>6e40a5bf-4965-455f-b397-b04ee258a9d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'UPDATED_CHK0']</value>
      <webElementGuid>b5d26681-7050-4425-8c15-c271ba380566</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
