<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectRECEIVEDPENDINGDEFERRED_1</name>
   <tag></tag>
   <elementGuidId>62384f68-d758-4691-b3fe-c781728a5338</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DOCCOLLECTION_STATUS1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DOCCOLLECTION_STATUS1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f6e8aa7a-396f-41f5-b456-3694dadee6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DOCCOLLECTION_STATUS1</value>
      <webElementGuid>428da1c6-a883-4227-a74b-a42bb62b3afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>setStatusDates(docDetail,$index)</value>
      <webElementGuid>d172f942-017a-401f-a6b0-8a17afc98483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>docDetail.DOCCOLLECTIONSTATUSID</value>
      <webElementGuid>8e305a66-7d02-49ae-a71a-cf40bf3e5f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>03cafad2-c807-43c3-b03c-813bdacd4f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					   Select
						RECEIVEDPENDINGDEFERRED
						</value>
      <webElementGuid>f299735e-9b0e-428a-8f72-8e5cef5918f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DOCCOLLECTION_STATUS1&quot;)</value>
      <webElementGuid>52f40cc4-d55e-4619-9571-2e5486373125</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DOCCOLLECTION_STATUS1']</value>
      <webElementGuid>eb8c1b03-2efb-4d9a-8c28-1ca64c499740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='documentTable']/tbody/tr[3]/td[10]/select</value>
      <webElementGuid>d3abdcec-727a-40eb-b05f-48bbc580ca07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYSUSER'])[1]/following::select[5]</value>
      <webElementGuid>d60a7e7b-37b7-4e8f-982e-ae9039165f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Document'])[1]/following::select[7]</value>
      <webElementGuid>e322db98-b71a-437e-9f49-e7311007a936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYSUSER'])[2]/preceding::select[2]</value>
      <webElementGuid>55021cd3-48ab-44d3-9d64-33b8912eb4c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qualtech Consultants Pvt. Ltd.'])[1]/preceding::select[2]</value>
      <webElementGuid>60f30411-c921-4f58-aa95-fb2e00b1c24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[10]/select</value>
      <webElementGuid>8d346d43-c7bc-4724-8da2-3ae974055b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DOCCOLLECTION_STATUS1' and (text() = '
					   Select
						RECEIVEDPENDINGDEFERRED
						' or . = '
					   Select
						RECEIVEDPENDINGDEFERRED
						')]</value>
      <webElementGuid>f7850bfd-d5ba-4592-87a0-e7ed15487c46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
