<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECTREJECTAPPROVE</name>
   <tag></tag>
   <elementGuidId>749fdf93-5e9c-451c-bff3-f15b94c2eb3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ACTION_BY_VALUE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ACTION_BY_VALUE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b4343f53-4f93-4569-8169-6da915ec705b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_header_cost ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>9f1ba7f7-41a1-4486-9098-567de1c76e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ACTION_BY_VALUE</value>
      <webElementGuid>39559d86-1cbc-47e2-bf14-f70c5925492f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>x.ACTION_BY_VALUE</value>
      <webElementGuid>bd2bba61-335f-4823-98ce-f354509bd0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>value.ID as value.NAME for value in x.statusList </value>
      <webElementGuid>a3af9bdd-6885-4d3d-bd46-65f43270c09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>x.rowDisabled</value>
      <webElementGuid>c3b22d3a-a473-46b5-af8e-02e1b7f6935e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELECTREJECTAPPROVE</value>
      <webElementGuid>5e289fd5-399f-431b-a08b-a747b1f8ea90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ACTION_BY_VALUE&quot;)</value>
      <webElementGuid>b7489d15-260a-473c-8314-2792c5857a2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ACTION_BY_VALUE']</value>
      <webElementGuid>09025f18-3700-43df-9fe9-4dab49e9d2a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='existingTable']/tbody/tr/td[2]/select</value>
      <webElementGuid>b388772e-1271-4f60-b838-f1d83ae51e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTION BY SUPERUSER/SALES/COPSUSER'])[1]/following::select[1]</value>
      <webElementGuid>bdc1d123-cfa1-4d6d-b33f-8631ec67ff5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCEPTANCE STATUS'])[1]/following::select[1]</value>
      <webElementGuid>7cb9f219-4c3e-48f7-ad67-cbbd25df5694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REJECT CODE'])[1]/preceding::select[1]</value>
      <webElementGuid>71059ca8-ea4a-4a62-b699-0c09987c91dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTION DATE'])[1]/preceding::select[2]</value>
      <webElementGuid>e9d73b47-8eed-4c28-8c5a-af4b396f1e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
      <webElementGuid>c5dfdb9d-a1cc-4f78-b9db-dcb3f85339a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ACTION_BY_VALUE' and (text() = 'SELECTREJECTAPPROVE' or . = 'SELECTREJECTAPPROVE')]</value>
      <webElementGuid>aa7d2707-f9f8-4703-9c35-4a456b8f8193</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
