<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECTTRI PARTYBI PARTY</name>
   <tag></tag>
   <elementGuidId>f0a5c036-a865-4a73-be66-41cacdc5f7d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='agreement_type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#agreement_type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8dfb6b7f-3b9a-4c20-b603-b885121c56f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_header_cost ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>e92abba4-c846-413b-bdd3-bc79fa313a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agreement_type</value>
      <webElementGuid>94a39969-c637-40f5-8ab0-e9e203663393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>AGREEMENT_TYPE_VALUE</value>
      <webElementGuid>341ed003-d1cc-47b1-b53d-7cb10fc80b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>createMonthlyCharges('Y')</value>
      <webElementGuid>e625e6ff-a64c-47c5-b89f-c87e69de4264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>value.ID as value.NAME for value in AGREEMENT_TYPE</value>
      <webElementGuid>1f43ea14-a3ff-4a30-be08-f7931f396dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELECTTRI PARTYBI PARTY</value>
      <webElementGuid>c4e0a751-45df-4e67-b9fc-bdd4d417d1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agreement_type&quot;)</value>
      <webElementGuid>3a9521c2-00e9-495f-aed3-28b8306932db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='agreement_type']</value>
      <webElementGuid>c0f2bfc7-66c7-4dd5-9b48-262a04e60bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='quotationBodyId']/div[7]/div/form/fieldset[2]/div/div[25]/select</value>
      <webElementGuid>23abed9e-9f24-4724-9657-872535ee36f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agreement Type'])[1]/following::select[1]</value>
      <webElementGuid>853f999b-a90c-44dd-bf7a-6c205d3e762a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rental Mode'])[1]/following::select[2]</value>
      <webElementGuid>fd432906-c947-4d9e-874d-6070cec8aab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Day'])[1]/preceding::select[1]</value>
      <webElementGuid>0fb8fede-3338-4cc0-86fb-67bfd1eaa1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[25]/select</value>
      <webElementGuid>f623ae14-c32c-4d56-98ac-2bda840e540e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'agreement_type' and (text() = 'SELECTTRI PARTYBI PARTY' or . = 'SELECTTRI PARTYBI PARTY')]</value>
      <webElementGuid>e81da639-0195-4e2a-a318-055a05b55e4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
