<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECT9911001</name>
   <tag></tag>
   <elementGuidId>eca71112-2306-4ea0-ad69-d883a0b3ead6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='FIXED_RV_TYPE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FIXED_RV_TYPE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>423b53ee-40af-472e-885c-3d6d3c590a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_header_cost ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>e230260b-56c3-459e-a05c-5879439e49cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FIXED_RV_TYPE</value>
      <webElementGuid>9a393d59-2f1c-44d4-8ac2-3d2255d92146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>FIXED_RV_TYPE</value>
      <webElementGuid>c4bd7f71-049a-4299-aa61-9a1b36ca5cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>setRvAdvice()</value>
      <webElementGuid>1d8e8ea2-7a24-41c7-937e-29ad4c6bd9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>boolFexedRVType=='true' </value>
      <webElementGuid>2ccb94be-5b04-43dd-a834-21f0f44a2d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					SELECT99+1100+1
				</value>
      <webElementGuid>2606e48c-91db-4b24-917d-9be326015ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FIXED_RV_TYPE&quot;)</value>
      <webElementGuid>ddae2f06-79e3-402a-a178-86abc6e1a86a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='FIXED_RV_TYPE']</value>
      <webElementGuid>9290e6eb-8dd4-4b06-a273-4b40ec48b7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='quotationBodyId']/div[7]/div/form/fieldset[3]/div/div[2]/div[4]/select</value>
      <webElementGuid>3446e271-61e7-4f73-9612-ca46e4a156b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Residual Value Type'])[1]/following::select[1]</value>
      <webElementGuid>8ec37ce3-05c6-4f26-affc-7f6cc82576ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RV Type'])[1]/following::select[2]</value>
      <webElementGuid>4464d902-2288-4502-acd2-cb9e0779fe57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RV/Buy Back Calculation'])[1]/preceding::select[1]</value>
      <webElementGuid>05f28e4b-b459-48ee-b080-22dd1fccfa13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Market RV Slab'])[1]/preceding::select[2]</value>
      <webElementGuid>396d2f54-0665-4f7c-9437-177b5aca5901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>d985289f-3622-4414-9279-2e8514e604c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'FIXED_RV_TYPE' and (text() = '
					SELECT99+1100+1
				' or . = '
					SELECT99+1100+1
				')]</value>
      <webElementGuid>ac78b6a0-640d-442d-8eed-d67e3aeace06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
