<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECTDEPOSIT PAID AT CIMVAT ON EX-S_44a36b_1_2</name>
   <tag></tag>
   <elementGuidId>f6f7902b-8ada-4a8f-846c-1ccb539ea103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CHARGE_ID4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CHARGE_ID4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>64ea84ed-87bf-4d72-9e99-c1ab96141752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CHARGE_ID4</value>
      <webElementGuid>fa63d82a-85d2-4506-a71a-d12d44d836e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inflow.CHARGE_ID</value>
      <webElementGuid>285607ce-7267-402e-9e32-6f5f894cde10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>setVatFlags($index);setImpactonFA();</value>
      <webElementGuid>64f10a4c-8dc9-40a5-bea5-4c8eb6249c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>81ae62e7-bff4-4838-ac76-15661ef82936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					   SELECTDEPOSIT PAID AT CIMVAT ON EX-SHOWROOM PRICECAR REGISTRATION FEE/ROAD TAXFRONT END FEEREGISTRATION DUTYSURVEYOR FEEMAINTENANCE
					 </value>
      <webElementGuid>bfdd4d26-4baa-4ec8-bafb-8dab8ab0cfc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CHARGE_ID4&quot;)</value>
      <webElementGuid>d47c047d-f7af-41cd-94ef-cd9eec1924b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CHARGE_ID4']</value>
      <webElementGuid>2c1865a8-27fe-457f-b5af-cfe709dee346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='existingTable']/tbody/tr[6]/td[2]/span/select</value>
      <webElementGuid>89bf9660-8ede-4fb4-8e1d-fed2c972248b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dealer Code'])[2]/following::select[13]</value>
      <webElementGuid>9c32b28d-520a-41fc-bfc1-d1a734646138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dealer Name'])[2]/following::select[13]</value>
      <webElementGuid>2502d950-de11-4d0f-898f-b035179bd428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COST (Amount In Rs.)'])[1]/preceding::select[3]</value>
      <webElementGuid>2ef416a7-379c-403f-a135-579236860757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finance Amount'])[1]/preceding::select[3]</value>
      <webElementGuid>2848ccf0-ac31-4b28-96aa-f6ffd1af8994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/span/select</value>
      <webElementGuid>fa82b54f-f676-4c41-80cc-6a5524de217a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CHARGE_ID4' and (text() = '
					   SELECTDEPOSIT PAID AT CIMVAT ON EX-SHOWROOM PRICECAR REGISTRATION FEE/ROAD TAXFRONT END FEEREGISTRATION DUTYSURVEYOR FEEMAINTENANCE
					 ' or . = '
					   SELECTDEPOSIT PAID AT CIMVAT ON EX-SHOWROOM PRICECAR REGISTRATION FEE/ROAD TAXFRONT END FEEREGISTRATION DUTYSURVEYOR FEEMAINTENANCE
					 ')]</value>
      <webElementGuid>15f5f72b-3288-4179-bd9f-f613d756ca32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
