<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectRECEIVEDPENDINGDEFERRED_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>417314b8-18f3-4bdd-8f84-77f31dd5ccd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DOCCOLLECTION_STATUS6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DOCCOLLECTION_STATUS6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f3e5021f-d968-4608-be2d-5c45292cf6d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DOCCOLLECTION_STATUS6</value>
      <webElementGuid>742a8fbb-5860-4965-a868-5f96685c78ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>setStatusDates(docDetail,$index)</value>
      <webElementGuid>dd9ebfce-d04c-4e10-9f0c-ec4951d02aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>docDetail.DOCCOLLECTIONSTATUSID</value>
      <webElementGuid>b445a4a9-95ab-4f79-bdf2-c58d39b8ccda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>fa3dc834-d99d-4d94-916b-6872cc4bc2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					   Select
						RECEIVEDPENDINGDEFERRED
						</value>
      <webElementGuid>c81f27e4-46ae-44e4-8083-9af555b50073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DOCCOLLECTION_STATUS6&quot;)</value>
      <webElementGuid>418de1bc-226a-4e78-89d7-385ab3aaf732</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DOCCOLLECTION_STATUS6']</value>
      <webElementGuid>ef060384-d0cc-46cd-9682-715a573d234c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='documentTable']/tbody/tr[8]/td[10]/select</value>
      <webElementGuid>671aaadb-ac05-41b4-af6f-f7159cf56f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYSUSER'])[6]/following::select[5]</value>
      <webElementGuid>c5d0c343-af49-4785-952b-aaf925daf402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Document'])[6]/following::select[7]</value>
      <webElementGuid>807d08c1-1520-4ef8-8033-bb1621cbf0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYSUSER'])[7]/preceding::select[2]</value>
      <webElementGuid>3f70888f-731c-4a74-96e4-7d4766b707e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qualtech Consultants Pvt. Ltd.'])[1]/preceding::select[2]</value>
      <webElementGuid>1ea391a7-2def-472b-9514-96d7d6885f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[10]/select</value>
      <webElementGuid>0d2d52a3-d8ae-483f-9bbf-7fe14b8881cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DOCCOLLECTION_STATUS6' and (text() = '
					   Select
						RECEIVEDPENDINGDEFERRED
						' or . = '
					   Select
						RECEIVEDPENDINGDEFERRED
						')]</value>
      <webElementGuid>a107115f-0cdb-461e-8e07-af03c964b849</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
