<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectRECEIVEDPENDINGDEFERRED</name>
   <tag></tag>
   <elementGuidId>4f9a1170-8eb6-40df-aaa3-e9457f70961c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DOCCOLLECTION_STATUS0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DOCCOLLECTION_STATUS0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6c5be3aa-2fcb-4f5a-b7d2-68197810a201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DOCCOLLECTION_STATUS0</value>
      <webElementGuid>bc0148e8-fe7c-4772-af56-9424dfd44244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>setStatusDates(docDetail,$index)</value>
      <webElementGuid>5319f629-ac06-4c3e-9800-8ab37c3e351d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>docDetail.DOCCOLLECTIONSTATUSID</value>
      <webElementGuid>7e8d264d-b093-4ab7-95a7-12329cc92772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>62fcee80-c5c1-4e31-afce-b763dc0af72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					   Select
						RECEIVEDPENDINGDEFERRED
						</value>
      <webElementGuid>db578ea3-c7b7-4edb-b0cb-c192d45fb487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DOCCOLLECTION_STATUS0&quot;)</value>
      <webElementGuid>029eef02-589f-4149-9176-aa5ff2890b55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DOCCOLLECTION_STATUS0']</value>
      <webElementGuid>5282781a-ac5d-4208-9685-68229b59f200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='documentTable']/tbody/tr[2]/td[10]/select</value>
      <webElementGuid>e632d4b8-0ac6-4087-a80d-6d14e94f2e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Updated Date'])[1]/following::select[5]</value>
      <webElementGuid>513c59a2-5200-47a5-8312-fb56d993c58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Updated By'])[1]/following::select[5]</value>
      <webElementGuid>9a41d187-28e0-4cea-9592-9afade2b6e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYSUSER'])[1]/preceding::select[2]</value>
      <webElementGuid>0d04ded0-a834-4215-b8a1-f594c9481d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SYSUSER'])[2]/preceding::select[8]</value>
      <webElementGuid>34ebe784-9c36-4901-aea3-1aac1ef4a121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/select</value>
      <webElementGuid>49e4dd10-1842-45c0-b8f4-a2f8364a85f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DOCCOLLECTION_STATUS0' and (text() = '
					   Select
						RECEIVEDPENDINGDEFERRED
						' or . = '
					   Select
						RECEIVEDPENDINGDEFERRED
						')]</value>
      <webElementGuid>6731b501-09d4-4373-8066-f3b3904f6102</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
