<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECTHEAD OFFICE_1 (1)</name>
   <tag></tag>
   <elementGuidId>0c5f40f2-3586-445a-a1c7-abc21c475432</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='cashTakingBranchId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;cashTakingBranchId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b7096965-e624-4e01-bf5b-de443e4c6a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cashTakingBranchId</value>
      <webElementGuid>6e5ce3c3-fed1-4e04-b8b6-cfbca8568f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>SELECT</value>
      <webElementGuid>3a587938-73d5-44ee-87eb-721d563c0244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELECT
HEAD OFFICE</value>
      <webElementGuid>8f2cc0a9-e2da-40b5-b7c1-f6a1e82996c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;menuHavingBody&quot;]/form[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;col-lg-2 col-md-2 col-sm-3 col-xs-6&quot;]/select[1]</value>
      <webElementGuid>8d782768-3869-4f74-b4ad-24eda5234786</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='cashTakingBranchId']</value>
      <webElementGuid>9bece2d3-2459-4f5b-b2d4-2fe905c39e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>f233b5fb-6c1d-47bf-9f60-b98e4bc135a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instrument Details'])[1]/preceding::select[1]</value>
      <webElementGuid>38c97cc1-507c-4b8e-89f8-517ae7dd980d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0502b78e-c065-4d2c-96c8-da7019023bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cashTakingBranchId' and @title = 'SELECT' and (text() = 'SELECT
HEAD OFFICE' or . = 'SELECT
HEAD OFFICE')]</value>
      <webElementGuid>bfe1d3c1-2738-45f9-b182-b3bdb009e09f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
