<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_SELECTREJECTAPPROVE</name>
   <tag></tag>
   <elementGuidId>ed0fcbf8-207d-4e33-b83b-dd4db275419d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//table[@id='existingTable']/tbody/tr/td[2])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>38a48425-720e-4317-9916-50da006be9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20%</value>
      <webElementGuid>32a977ca-4cf8-4e77-b177-28e8d344f8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						     SELECTREJECTAPPROVE 
					    </value>
      <webElementGuid>7fb894c2-7931-4dcb-99c8-de1b4c62d9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptanceStatusDiv&quot;)/fieldset[1]/table[@id=&quot;existingTable&quot;]/tbody[1]/tr[@class=&quot;tr_list ng-scope&quot;]/td[2]</value>
      <webElementGuid>317c5c33-e480-4157-9b44-f8d9bd783334</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//table[@id='existingTable']/tbody/tr/td[2])[3]</value>
      <webElementGuid>ca91d1f8-5135-431e-aa92-5d189b766878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTION BY SUPERUSER/SALES/COPSUSER'])[1]/following::td[1]</value>
      <webElementGuid>fdf640b6-b623-4e67-94f8-752cb8242367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCEPTANCE STATUS'])[1]/following::td[2]</value>
      <webElementGuid>30fe7a78-866f-4220-9d7f-a4f0d39b5741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REJECT CODE'])[1]/preceding::td[1]</value>
      <webElementGuid>bf539177-b133-4e13-9345-76e3644db7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTION DATE'])[1]/preceding::td[3]</value>
      <webElementGuid>76420309-3515-4199-8f6d-14ed00b1729e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/table/tbody/tr/td[2]</value>
      <webElementGuid>6f9fb564-0e1e-4d38-8aa7-8131e3378346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
						     SELECTREJECTAPPROVE 
					    ' or . = '
						     SELECTREJECTAPPROVE 
					    ')]</value>
      <webElementGuid>7b8c0d91-1873-47f5-b6eb-d93e5720d309</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
