<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Remarks_arRemarks</name>
   <tag></tag>
   <elementGuidId>544653fc-d60d-4e60-b246-d6fe028ef304</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='arRemarksId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#arRemarksId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a17b5ffc-6399-46d4-897d-059ab68404ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>arRemarks</value>
      <webElementGuid>7b4a38f8-3b97-4aab-9a61-623cb757ab97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>09f89780-5d24-482f-8802-cf5cb4e8f9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>813296fb-eb91-4648-84a9-aeefe0310552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>checkRemark(this,'Author Remark')</value>
      <webElementGuid>5a36253c-4df3-4809-9a41-bd55cfe80608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arRemarksId</value>
      <webElementGuid>35eab3b3-002f-40fe-91ac-7c5239f8d97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arRemarksId&quot;)</value>
      <webElementGuid>03527872-e939-4f78-bb38-c94d449653bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='arRemarksId']</value>
      <webElementGuid>31e8a0c6-2db2-49b7-b9ce-6943928d3309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fieldSetId']/div[3]/div/div[2]/textarea</value>
      <webElementGuid>75ebaa30-eae3-45f6-a625-f9a9545f3fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/textarea</value>
      <webElementGuid>ab67d35c-f6ce-46b3-8c8a-d55d12015d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'arRemarks' and @id = 'arRemarksId']</value>
      <webElementGuid>0f6fbcb9-2eb8-42f5-8257-de45a748d420</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
