<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_National IDBRNPP No_generalFilter (1)</name>
   <tag></tag>
   <elementGuidId>1d073b85-fd2c-4295-980c-af707ee7f893</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='generalFilter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#generalFilter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1809d509-a8cf-4733-8027-ae759ce8a6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_header_cost ng-valid ng-touched ng-dirty ng-valid-parse</value>
      <webElementGuid>efb4eda2-7e23-4a91-b71b-a379e5dfe0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6cc21dcc-9ca2-40c2-81ef-088b35de4703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>generalFilter</value>
      <webElementGuid>e69256a7-3d4d-418c-8c06-d018eb70a9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>searchData.generalFilter</value>
      <webElementGuid>01bd05f1-cec3-437d-b01c-695dfb012b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;generalFilter&quot;)</value>
      <webElementGuid>17f51233-9397-4ba0-85b4-175aa659baf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='generalFilter']</value>
      <webElementGuid>4ed88616-9176-4ad5-9250-4e8cd5fb498f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='dashbord_main']/form/div[5]/div/div/div[18]/input</value>
      <webElementGuid>e79e91ca-e0ea-4506-bac0-e6d647ba936f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/input</value>
      <webElementGuid>efe3bba9-02f7-4b48-8c54-b05f8100ff56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'generalFilter']</value>
      <webElementGuid>ebb11c91-b765-471d-83ed-3e96a09f0ac4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
