<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DMFIN1000008259</name>
   <tag></tag>
   <elementGuidId>65df7952-ad60-469e-8471-a16856d759ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='allProspectEntries']/table/tbody/tr/td[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a77f1f2b-80da-456f-ba48-a7268ff8bd97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:showDetail('DMFIN1000008259','1000008259','1000038416','1000008259','1000000008')</value>
      <webElementGuid>4c4aff9b-e0ca-4453-9b2d-fd75f7e48891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DMFIN1000008259 </value>
      <webElementGuid>ec842355-8ac1-4b5a-9c77-a755ca508250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allProspectEntries&quot;)/table[@class=&quot;tr_list&quot;]/tbody[1]/tr[@class=&quot;tr_list_bgred&quot;]/td[3]/a[1]</value>
      <webElementGuid>2da05fa6-8323-4783-abbe-57de8880e39f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allProspectEntries']/table/tbody/tr/td[3]/a</value>
      <webElementGuid>9b54faf0-b947-4211-b4b7-13493254fa6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DMFIN1000008259')]</value>
      <webElementGuid>c705cd02-3bb4-410d-8505-71f9736ef5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ONLY FIXED FINANCE LEASE'])[2]/following::a[1]</value>
      <webElementGuid>1ae9d7c5-c143-4e5e-8790-63d36d130ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNCIMF000003205'])[1]/preceding::a[1]</value>
      <webElementGuid>09197f61-57ba-486b-91b3-1095d2439d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DMFIN1000008259']/parent::*</value>
      <webElementGuid>dd2e7b89-462f-42cf-bd42-1239a51d0bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:showDetail('DMFIN1000008259','1000008259','1000038416','1000008259','1000000008')&quot;)]</value>
      <webElementGuid>c676727d-8112-45c1-947f-9f384794e0be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>cf9700c0-0c84-4fc9-9934-fef5b3e4869e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:showDetail(&quot; , &quot;'&quot; , &quot;DMFIN1000008259&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000008259&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000038416&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000008259&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000000008&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'DMFIN1000008259 ' or . = 'DMFIN1000008259 ')]</value>
      <webElementGuid>257443a9-b4c2-45a1-b096-719d881187c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
