<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Approve_authAction</name>
   <tag></tag>
   <elementGuidId>b7e3dbed-4341-4f93-b197-e9e222d43480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aApprove</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='aApprove']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3bc7064-32cb-4fdd-be3c-6ca9130400ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bd9a3154-2154-43e2-a922-4cf996b21441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>authAction</value>
      <webElementGuid>e3ef4bcd-2ef8-4e73-8f94-918a598395b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aApprove</value>
      <webElementGuid>40d1d079-da8d-4450-b306-e8c64ab1bf74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>A</value>
      <webElementGuid>2dc0d1b4-eb45-494b-bb9a-f2b9b7642022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aApprove&quot;)</value>
      <webElementGuid>db896bdf-c7e2-4ad1-b07b-649947bd4d06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='aApprove']</value>
      <webElementGuid>504fa6b5-71fa-4f69-b088-1991f81fbe0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>81dc1446-659d-41f1-8912-819273bbabea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'authAction' and @id = 'aApprove']</value>
      <webElementGuid>37de2186-8e6b-4ded-8d28-37e1e8b6e3fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
