<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LMS</name>
   <tag></tag>
   <elementGuidId>2599a1ab-d768-4077-a463-355b08eedab9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;callLink('1000000017')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#action1000000017 > div.fgfg.MenuLevel0Parent > div.modules_anchor1.MenuLevel0 > a.modules_anchor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c2061b85-8460-42f2-b78a-1bf94d18e8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modules_anchor</value>
      <webElementGuid>4adc259b-b8fa-49fe-bc7e-4a88c3c31b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>callLink('1000000017')</value>
      <webElementGuid>c6fb6bb4-2c4f-41b2-a528-390f57830f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LMS</value>
      <webElementGuid>ba64910b-f6a6-4777-ac1c-1ee28f6c5757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;action1000000017&quot;)/div[@class=&quot;fgfg MenuLevel0Parent&quot;]/div[@class=&quot;modules_anchor1 MenuLevel0&quot;]/a[@class=&quot;modules_anchor&quot;]</value>
      <webElementGuid>640429f9-97f8-43bf-a74f-94dd62c89e33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;callLink('1000000017')&quot;]</value>
      <webElementGuid>9c93c612-a611-4d58-8afe-0e15736a539a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action1000000017']/div/div[2]/a</value>
      <webElementGuid>dfdd7234-1489-4e6b-a67a-01aa90b14fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LMS')]</value>
      <webElementGuid>69d2c8ab-3d87-4567-9bd8-d0d9626aa137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DM VIEWER'])[1]/following::a[1]</value>
      <webElementGuid>4d9fcf65-88bc-498c-8533-f55e4a0ab774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEWER'])[3]/following::a[2]</value>
      <webElementGuid>ba68b6ac-0a4e-44b9-8468-dbaaac0e6381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INVOICE'])[1]/preceding::a[1]</value>
      <webElementGuid>1392ac48-c0f2-4677-be6c-ac65593a3077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INVOICE'])[2]/preceding::a[2]</value>
      <webElementGuid>3fdaaf15-c26f-4c17-93b5-8489188d5439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LMS']/parent::*</value>
      <webElementGuid>1148b1cc-654a-42aa-914d-47091907f203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[68]/div/div[2]/a</value>
      <webElementGuid>621fab86-eebc-4983-86c5-afe833d3850f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'LMS' or . = 'LMS')]</value>
      <webElementGuid>bb53f758-c4be-4f36-87fd-4f3d04852e13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
