<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_APPLICANT</name>
   <tag></tag>
   <elementGuidId>08fce4ab-6293-4598-95ff-d2b0a902042c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.noLine</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b429e4e4-69e8-41fd-a7d0-ac70ed0f01ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>applicantList.do?actionPerformed=displayCustomerList&amp;screenId=1000000079&amp;mode=E&amp;disName=APPLICANT</value>
      <webElementGuid>700314fc-8c27-4298-a63f-d4500d58fbb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noLine</value>
      <webElementGuid>5cc9d9e9-6090-45a2-844a-88a3649fc320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>APPLICANT</value>
      <webElementGuid>f2a091cd-f0cb-4f93-a64c-3acac2a359ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;menu col-lg-12 col-md-12 col-sm-12 col-xs-12&quot;]/div[1]/a[@class=&quot;noLine&quot;]</value>
      <webElementGuid>59d0e681-2748-4806-ba00-961ea555afdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div/div/a</value>
      <webElementGuid>e07d2605-5a21-4565-a38c-3d3050b6c635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'APPLICANT')]</value>
      <webElementGuid>00741fbf-dbee-4a34-a3a7-ac09ff1a7be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::a[1]</value>
      <webElementGuid>51dc2ce6-a82f-4602-a3ab-f6a7759df62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save &amp; Exit'])[1]/following::a[2]</value>
      <webElementGuid>9d59af5a-9f4b-4923-8bc2-940166d934c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEDUPE'])[2]/preceding::a[1]</value>
      <webElementGuid>b24942ef-43a1-40a5-b3e1-5b1dfad38155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTEPAD'])[1]/preceding::a[2]</value>
      <webElementGuid>24dcb40c-1c15-427e-9fb8-f13ba95f8f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='APPLICANT']/parent::*</value>
      <webElementGuid>f540e98f-5ebb-4cbd-9fbe-a9595c584c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'applicantList.do?actionPerformed=displayCustomerList&amp;screenId=1000000079&amp;mode=E&amp;disName=APPLICANT')]</value>
      <webElementGuid>63db9dbe-fd90-45f6-83a5-0d0e48e179e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a</value>
      <webElementGuid>0fcb5940-1fd6-4ec8-a57c-2d022c208c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'applicantList.do?actionPerformed=displayCustomerList&amp;screenId=1000000079&amp;mode=E&amp;disName=APPLICANT' and (text() = 'APPLICANT' or . = 'APPLICANT')]</value>
      <webElementGuid>275802c3-2b55-4a5e-b412-39066f6686c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
