<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DMFIN1000008259</name>
   <tag></tag>
   <elementGuidId>9f5af23f-49ae-4003-a4e7-a23bcc268457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='allProspectEntries']/table/tbody/tr/td[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c25bbbb9-c296-4727-b75f-12a28083000b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:showDetail('DMFIN1000008259','1000001','1000038416','1000008259','1000000008')</value>
      <webElementGuid>446ea070-890b-49f6-bb89-32f49c8cdc54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DMFIN1000008259 </value>
      <webElementGuid>61ae7f65-1b77-45a8-881d-d53926b73a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allProspectEntries&quot;)/table[@class=&quot;tr_list&quot;]/tbody[1]/tr[@class=&quot;tr_list_bgred&quot;]/td[3]/a[1]</value>
      <webElementGuid>e56bb803-eacc-4aa8-b70b-f1b277b4d954</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allProspectEntries']/table/tbody/tr/td[3]/a</value>
      <webElementGuid>ba95390b-df46-4cfa-9516-88968fe6301e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DMFIN1000008259')]</value>
      <webElementGuid>1c9cfd3a-0eca-4825-9dc7-2c0fa92559d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ONLY FIXED FINANCE LEASE'])[2]/following::a[1]</value>
      <webElementGuid>a26fe149-cef8-4de1-944d-f9312df35bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNCIMF000003205'])[1]/preceding::a[1]</value>
      <webElementGuid>bee623d2-f831-4d7d-a4a9-a67ff30a72a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DMFIN1000008259']/parent::*</value>
      <webElementGuid>86374018-8305-43fe-9403-bbd098320ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:showDetail('DMFIN1000008259','1000001','1000038416','1000008259','1000000008')&quot;)]</value>
      <webElementGuid>40021188-75c5-4fbd-805d-fd1104a67d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>b8cc6da9-b1b0-4fc7-89f7-655e3fd440b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:showDetail(&quot; , &quot;'&quot; , &quot;DMFIN1000008259&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000001&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000038416&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000008259&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1000000008&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'DMFIN1000008259 ' or . = 'DMFIN1000008259 ')]</value>
      <webElementGuid>d4f9841b-bc7d-4f87-8bcf-98e49bfdf307</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
