<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Send To Author_makeRemarks0</name>
   <tag></tag>
   <elementGuidId>c106288f-7b3f-410a-acf6-44e830e58c6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#makeRemarks0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='makeRemarks0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c5c6e54-99e5-40e2-b880-40cede1d35af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d5ef462-fb2d-48e9-a731-586a5e752924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>79250e64-d769-42d0-a666-fdde4b732d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:isValidRemarks(this,'Maker Remarks')</value>
      <webElementGuid>deb0b94c-6bb4-44df-b594-fe50b06e9b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>makeRemarks0</value>
      <webElementGuid>08f3f6df-cf43-47ea-8e1b-d4d64a7f5208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;makeRemarks0&quot;)</value>
      <webElementGuid>ff4f3cb8-1fbe-432e-9fe3-d0b3ff150d1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='makeRemarks0']</value>
      <webElementGuid>750a716b-3d45-4bd4-af95-3e4770c364c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='chargerowtable0']/tbody/tr/td[12]/input</value>
      <webElementGuid>0365c9bd-6424-4f36-b7a5-4ad0a2b6036a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/input</value>
      <webElementGuid>0c6990a6-bac4-443f-9fff-5c7bcebb05c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'makeRemarks0']</value>
      <webElementGuid>3bb86c9a-b6a3-4e21-ae58-f4bfe5c56d2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
