<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Send To Author_misBillId0</name>
   <tag></tag>
   <elementGuidId>dbf501a1-9cb4-4da0-995e-a5bc807b4c4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#misBillId0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='misBillId0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a00826ac-a75f-41ad-a3f8-52b59f3e06d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f7554b80-5046-46c4-8c45-775723d6c620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>misBillId0</value>
      <webElementGuid>16f24acf-4e3c-4683-b882-4eb8c086f0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>enableDisableInvoiceNo(this,0,&quot;N&quot;,&quot;misl&quot;);</value>
      <webElementGuid>c7a39d0d-7bb8-4039-a4e5-25f0f351ed8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;misBillId0&quot;)</value>
      <webElementGuid>2f4e5891-f819-46c8-a651-d86a905ba53b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='misBillId0']</value>
      <webElementGuid>71b8da9d-4d32-4bcc-9a80-68a5dd11835b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='chargerowtable0']/tbody/tr/td[4]/input</value>
      <webElementGuid>95a18250-9bb1-4e04-9ba6-559dd7dbef05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>5e772712-c882-409a-bc72-57aed53471d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'misBillId0']</value>
      <webElementGuid>02428d7f-e4fd-46d1-b983-acf26d6db5fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
