<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectReceivablePayable_1</name>
   <tag></tag>
   <elementGuidId>dd9e2ff5-7693-442e-b81d-88f73f7d1289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chargeType1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='chargeType1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d481b161-d805-4f8c-93e4-b9390c5e563d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chargeType1</value>
      <webElementGuid>637f3c1b-36ee-4574-b778-9150ac20c208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript: populateChargeId(this.value,1,null,'M');</value>
      <webElementGuid>57e26f65-e454-46f4-a5ea-08bc568b08e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectReceivablePayable</value>
      <webElementGuid>f4ad55d9-2ae2-4b94-a8fd-80ba2d2f8326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chargeType1&quot;)</value>
      <webElementGuid>3fd2cb56-c471-4886-b43f-c503ee9dbe88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='chargeType1']</value>
      <webElementGuid>94fb3b1f-378b-471a-b97d-d90fd9e761b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='chargerowtable1']/tbody/tr/td[2]/select</value>
      <webElementGuid>0a7b7173-d86d-4cf4-a96e-65d7f4e68a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maker Remarks'])[1]/following::select[3]</value>
      <webElementGuid>1bb9bde2-14e8-41fd-af86-8ce57e8fcaa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qualtech Consultants Pvt. Ltd.'])[1]/preceding::select[2]</value>
      <webElementGuid>29587fc7-6373-456a-a567-f34f82128f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VERSION 1.0.1.295'])[1]/preceding::select[2]</value>
      <webElementGuid>33f51efe-f70b-4292-b7ec-f2cd9bfaa685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td[2]/select</value>
      <webElementGuid>8ec60a70-a85f-4c3b-97d7-7548275cbfad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'chargeType1' and (text() = 'SelectReceivablePayable' or . = 'SelectReceivablePayable')]</value>
      <webElementGuid>5cfd2d7b-9a25-466a-8992-36c56a83875b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
