<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectPRO RATA INTEREST</name>
   <tag></tag>
   <elementGuidId>df41625a-0481-44e9-91bf-f4e3f0b76201</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chargeId0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='chargeId0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b1e1f0c4-21fb-4992-ab26-f607443e696c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chargeId0</value>
      <webElementGuid>0412d6bd-68d6-4ce8-ac8a-e3605c7112df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectPRO RATA INTEREST</value>
      <webElementGuid>02c21bc1-bea6-4625-8f3d-dbe3a32037b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chargeId0&quot;)</value>
      <webElementGuid>a542bb47-f0aa-43e2-9ddb-0e8b9b2e7028</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='chargeId0']</value>
      <webElementGuid>1859b4e3-8e43-428f-adcc-d0bc7a5efb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='chargerowtable0']/tbody/tr/td[6]/select</value>
      <webElementGuid>16225c9e-200d-47e9-9239-42e9e747f9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maker Remarks'])[1]/following::select[2]</value>
      <webElementGuid>dfd0ec35-c391-44ac-8aa2-3b841f568a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qualtech Consultants Pvt. Ltd.'])[1]/preceding::select[1]</value>
      <webElementGuid>f9ba20d3-f1bd-4e13-b0e4-aa57cbbeaf23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VERSION 1.0.1.295'])[1]/preceding::select[1]</value>
      <webElementGuid>93b0900c-234c-42cb-947e-a372387d94ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/select</value>
      <webElementGuid>d18031f9-92c2-41b0-8b87-292dc1b0b067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'chargeId0' and (text() = 'SelectPRO RATA INTEREST' or . = 'SelectPRO RATA INTEREST')]</value>
      <webElementGuid>f5b972f8-273d-476a-888b-58b0c39b5b01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
