<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Payment From_paymentFrom_1</name>
   <tag></tag>
   <elementGuidId>4eb7b9f6-3b2c-4661-9b38-cac0ffeebf4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paymentFrom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paymentFrom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>508b3648-43c9-49c5-b96b-4eedd27f2be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8334cf59-6aef-499a-8f1d-e20c5743557b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentFrom</value>
      <webElementGuid>66bdba01-935b-4a06-aa61-cd6632bac550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>0c706bce-f58e-4605-bf71-87060828a3ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>e68504ae-4a78-45d5-8630-57bac5ade8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:checkDateFormat(this,'Payment From');</value>
      <webElementGuid>391a82e7-cc7e-4ddc-b7ee-4aa50cd58b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentFrom</value>
      <webElementGuid>cd88949b-6d95-4c7a-a21d-031eee49e45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>25-JUL-2023</value>
      <webElementGuid>2abd11cb-8c60-411c-91e3-44091b277fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentFrom&quot;)</value>
      <webElementGuid>e382b639-5926-4260-8023-bb8b1aad4588</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paymentFrom']</value>
      <webElementGuid>239a9c61-7108-4f60-a681-cb7f059f1522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fieldsetId']/div[2]/div[6]/input</value>
      <webElementGuid>e415cb61-ba3b-44d2-99fa-dcfbc44f2e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>00322430-2fe7-4b8d-91fd-1214f47503cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'paymentFrom' and @id = 'paymentFrom' and @title = '25-JUL-2023']</value>
      <webElementGuid>899a081a-3027-4e2a-9cb8-bea84ef53ff5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
