<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remarks_waiveOffCumulative(6)</name>
   <tag></tag>
   <elementGuidId>3b9ef2d0-c9f4-4c71-96ca-03ef6c3235ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='waiveOffCumulative'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>066f6f47-9a43-49f3-9646-9943b2f7b80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3f7bf2e4-cc93-49e6-ab14-e0d94b24eb45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>waiveOffCumulative</value>
      <webElementGuid>11199949-914c-40df-833a-2f325135a6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>b0337c52-faf0-409b-8f50-7f1702ffbeb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:reflectWaiveOffChecked();cumulativeReceiptAmountTemp();</value>
      <webElementGuid>8ae55db5-49ef-4f56-a2c6-98803e9c3d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cumulative&quot;)/table[@class=&quot;main_body&quot;]/tbody[1]/tr[7]/td[4]/input[1]</value>
      <webElementGuid>01ae25f7-8f73-4073-beca-98417d7b18ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='waiveOffCumulative'])[6]</value>
      <webElementGuid>c954cd86-2529-41ad-bc8c-61c9fe374a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cumulative']/table/tbody/tr[7]/td[4]/input</value>
      <webElementGuid>8c228ca3-49f3-41f9-8719-421508fabfee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[7]/td[4]/input</value>
      <webElementGuid>7a270862-c141-405e-ae89-605259d83fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'waiveOffCumulative']</value>
      <webElementGuid>6053b70b-caf3-4eb9-9c7a-0b0f1bb32044</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
