<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>font_ACTIVITY IN PROGRESS</name>
   <tag></tag>
   <elementGuidId>c15e78c7-7f47-47f7-8da4-ac6e8613238c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='foreclouserId']/form/div[3]/table/tbody/tr/td/font</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>font.menu_text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>2c5019eb-6700-4840-9cc5-1b30839f529c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>035488fc-388d-4190-a29f-b95863838e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu_text</value>
      <webElementGuid>0dabe52f-3d7f-4d9d-893a-c3c4f923ece5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACTIVITY IN PROGRESS</value>
      <webElementGuid>356e86ee-7289-41c6-ada0-eea51050466f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;foreclouserId&quot;)/form[@class=&quot;ng-pristine ng-invalid ng-invalid-maxlength&quot;]/div[@class=&quot;container-fluid&quot;]/table[@class=&quot;static_info_head&quot;]/tbody[1]/tr[1]/td[1]/font[@class=&quot;menu_text&quot;]</value>
      <webElementGuid>ecaa6661-c3ee-42f1-b2b7-9be97febec62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='foreclouserId']/form/div[3]/table/tbody/tr/td/font</value>
      <webElementGuid>0e9775c7-9bf1-4628-bdfa-77139732db6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penalty %'])[1]/following::font[1]</value>
      <webElementGuid>05598da7-96c3-4483-99e4-e6c9ddb9b57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenure To'])[1]/following::font[1]</value>
      <webElementGuid>58c4373d-754c-4bdb-a752-6bd90d52dc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sr. No.'])[1]/preceding::font[1]</value>
      <webElementGuid>743bec32-bff5-4e97-8ce6-944b8bd829c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity Description'])[1]/preceding::font[1]</value>
      <webElementGuid>e82c7736-5f08-480d-aa8f-032efe2a9e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ACTIVITY IN PROGRESS']/parent::*</value>
      <webElementGuid>bc5d0793-b878-4764-ab38-53a6e18b2bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//font</value>
      <webElementGuid>bd1cb293-e718-40ef-a7c7-67e4888cbfd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//font[(text() = 'ACTIVITY IN PROGRESS' or . = 'ACTIVITY IN PROGRESS')]</value>
      <webElementGuid>2262964d-4cc9-42b6-b18d-7667fc1c52d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
