<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RV Sales Deed Release_rvSalesDeedRelease</name>
   <tag></tag>
   <elementGuidId>b07d2bc2-1eae-444b-be32-2a95260a4882</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rvSalesDeedRelease']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rvSalesDeedRelease</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78e2c15c-318d-4522-8089-2591df1b32da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f8c0f884-f629-478c-96a8-cc67fc5da811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rvSalesDeedRelease</value>
      <webElementGuid>db037a6d-378b-4929-8f9e-f6d777861fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rvSalesDeedRelease</value>
      <webElementGuid>00a5c164-0ce9-4732-8766-75d2cff1a94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setRVSalesDeedRelFlag();</value>
      <webElementGuid>08273186-d67d-481c-8003-6c5ce0008544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rvSalesDeedRelease&quot;)</value>
      <webElementGuid>87d2a2d9-f970-4415-8fdd-194371a8ff9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rvSalesDeedRelease']</value>
      <webElementGuid>2f216417-797c-4702-ac7b-caced9d7b503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='foreclouserId']/form/div[3]/div/div[4]/div[12]/input</value>
      <webElementGuid>69e73f6d-d0c4-4229-90f6-29e1c1d1eae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/input</value>
      <webElementGuid>53ae1800-68c9-4a69-b537-4c406aa8b5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'rvSalesDeedRelease' and @id = 'rvSalesDeedRelease']</value>
      <webElementGuid>cae4df78-ea03-459f-9c1c-4cd3b3b48564</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
